### ISSUE TITLE
IDDESPeriodicHillEdge failing nightlies

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#1011]
`IDDESPeriodicHillEdge` is failing nightly testing with `Error: Requested field does not exist: total_dissipation_rate`.

PRs that merged between the last time the nightlies were passing and the first time the failure appeared are #1001, #1007.

@psakievich @marchdf can you take a look?

**Comment by jamelvin** [comment]
@marchdf @psakievich @tasmith4 Looks like we're missing a `break` statement:

https://github.com/Exawind/nalu-wind/blob/f94c5d82b67316299eaed7f51789cd9e5ff5004b/src/TurbKineticEnergyEquationSystem.C#L306

I'll fix this and double-check this didn't introduce any other errors.

**Comment by jamelvin** [comment]
Actually, this is address in @rcknaus PR: #1010

**Comment by marchdf** [comment]
I think this is fixed? I don't see it broken in the dashboard.

**Comment by psakievich** [comment]
Yes I believe it was resolved in #1010
