### ISSUE TITLE
KEChannelEdge is broken on the dashboard

### ISSUE THREAD

**Issue by marchdf** [Exawind/nalu-wind#1014]

**Comment by tasmith4** [comment]
looks like an out-of-date or non-existent gold file.  @jrood-nrel and I probably need to update the NREL and Sandia versions, respectively, of the gold file database.

**Comment by tasmith4** [comment]
I've done this on the Sandia side, so hopefully this test shows clean tomorrow morning on the SNL dashboard.

**Comment by marchdf** [comment]
KOChannel and SSTLRChannel are definitely missing golds. But KEChannel has a more serious problem maybe: https://my.cdash.org/test/60154151

**Comment by tasmith4** [comment]
ok that's interesting, I was looking at the Intel line which seemed to run to completion.
