### ISSUE TITLE
Clang build error:  Default constructor of NGPApplyCoeff implicitly deleted

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#1016]
On the nightly dashboard, clang 12 is reporting a build error with message:

```
include/SolverAlgorithm.h:75:14: /.../spack-src/include/SolverAlgorithm.h:
note: default constructor of 'NGPApplyCoeff' is implicitly deleted because field 'linSysOwnsCoeffApplier' of const-qualified type 'const bool' would not be initialized  const bool linSysOwnsCoeffApplier;

             ^
  const bool linSysOwnsCoeffApplier;
             ^
In file included from [src/AssembleNGPNodeSolverAlgorithm.C:10:
In file included from [include/AssembleNGPNodeSolverAlgorithm.h:13:
```

Sandia internal link is [here](https://sierra-cdash.sandia.gov/viewBuildError.php?buildid=504342), unfortunately the clang build on rhodes isn't reporting back today so I'm unsure if it's reproduced there.

This error appeared since yesterday, and the only commit to merge in that time was #1013.  However even after reviewing the commit I can't tell how it could possibly have caused this issue.

**Comment by psakievich** [comment]
Vanilla build of `nalu-wind%clang@12.0.1` did not reproduce this error. Trying now with all the TPL's enabled.

**Comment by psakievich** [comment]
I built 
```
nalu-wind@master~asan~boost~catalyst~cuda+fftw+hypre~ipo+openfast+pic~rocm~stk_simd+tests+tioga~wind-utils abs_tol=1e-15 build_type=Release cxxstd=14 dev_path=/scratch/psakiev/nalu-nightly/nalu-wind rel_tol=1e-12
```
with nalu-wind at commit `efc371004fe3542ebddaf7dd4c811b7618b82086` on `ascicgpu22` and was not able to reproduce this failure.

**Comment by tasmith4** [comment]
so weird.  I guess we can wait until Monday and see if it magically goes away

**Comment by psakievich** [comment]
yeah that seems reasonable to me.

**Comment by tasmith4** [comment]
gone this morning, so I guess we can close ... super weird though ...
