### ISSUE TITLE
nrel5MWactuatorDisk broken

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#1019]
See [the my.cdash dashboard](https://my.cdash.org/test/60434338) and [Sandia internal version](https://sierra-cdash.sandia.gov/test/220978205).  The dashboard failures appeared on the evening of August 12, PRs merged that day include:  #889, #1017, #934

@lawrenceccheung @psakievich @marchdf

**Comment by psakievich** [comment]
This is a diff due to #889.  It can be reblessed. @tasmith4 @jrood-nrel

**Comment by tasmith4** [comment]
After rebless, test is passing this morning.
