### ISSUE TITLE
edgeHybridFluids test diffing

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#1026]
The edgeHybridFluids test is diffing on the SNL nightly dashboard ([internal link]()) since Aug. 25 at 10pm MDT.  The diff seems to not be large, and the fact that it doesn't appear on the NREL dashboard implies that either something has changed slightly in Trilinos develop or it's system noise on the SNL machine.

@jhux2 were there any Trilinos solver changes of note around that time?

@psakievich who owns this test and can confirm whether a rebless is appropriate?

**Comment by psakievich** [comment]
@tasmith4 this is fine for a rebless.

**Comment by tasmith4** [comment]
Test is still diffing this morning, because I made a mistake when reblessing yesterday.  Updated gold file should be good for tonight's run.

**Comment by tasmith4** [comment]
Passing this morning after a correct rebless
