### ISSUE TITLE
Clang warnings about overridden functions

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#1028]
The nightly dashboards report several clang warnings about overridden functions in the master element code.  @overfelt these warnings began to appear after #1022 merged, although I'm a little confused about why that PR caused those warnings.  Can you take a look?

**Comment by tasmith4** [comment]
https://sierra-cdash.sandia.gov/index.php?project=Nalu-Wind

https://my.cdash.org/index.php?project=Nalu-Wind

**Comment by sayerhs** [comment]
@tasmith4 clang will complain if you add `override` to certain `virtual` functions that are overridden but not others. In this case, I suspect it is unhappy about `shape_fcn` and others that are overridden but don't have override directives. To remove warnings, you will either have to mark all overridden functions with `override` or remove `override` from the lines added in #1022

**Comment by tasmith4** [comment]
Fixed by #1030.  Thanks @overfelt!
