### ISSUE TITLE
Segfaults on Summit for Trilinos GPU tests for 2+ devices

### ISSUE THREAD

**Issue by PaulMullowney** [Exawind/nalu-wind#1060]
These failiures could be related to UVM removal:
Trilinos hash: b7afc20ebb6f95e8f05d02c5afe8299135d336fe
Nalu hash: 941c2322d06c025c994011c2639c005018d770d2

I tested:
ablNeutralNGPTrilinos.yaml
airfoilRANSEdegNGPTrilinos.rst

After building, one go to the build test subdir and run via:
 /sw/summit/xalt/1.2.1/bin/jsrun --smpiargs="-gpu" -n 2 -r 2 -a 1 -c 1 -g 1 ../../../naluX -i ../../../../reg_tests/test_files/airfoilRANSEdgeNGPTrilinos.rst/airfoilRANSEdgeNGPTrilinos.rst.yaml -c output.log

**Comment by marchdf** [comment]
No access to Summit anymore for many of us. Closing.
