### ISSUE TITLE
Add a github action to automatically apply style changes

### ISSUE THREAD

**Issue by psakievich** [Exawind/nalu-wind#1075]
I don't think we need a style check as much as we should just automatically call clang-format on all PR's coming in.  It would reduce a lot of the churn on PR's.

**Comment by jrood-nrel** [comment]
I tend to disagree with this unless there is a way to have the user's account do it and not a bot?

**Comment by psakievich** [comment]
I imagine there is a way to trigger a github action for it.  I'll poke around. This is a low priority to me, but I wanted to document it so I don't forget it.
