### ISSUE TITLE
Improve installation documentation regarding the existence of a docker container

### ISSUE THREAD

**Issue by neumantm** [Exawind/nalu-wind#1088]
I recently wanted to check out nalu-wind, but struggled with the installation.
Later I learned (by reading issues), that there is a docker container which I could have used.
Knowing this, would probably have helped me getting started with nalu-wind.

**Comment by neumantm** [comment]
If this is desired and there a no reasons against it, I could also create a PR.

**Comment by psakievich** [comment]
@neumantm that would be very helpful and appreciated!
