### ISSUE TITLE
Extend project development infrastructure documentation

### ISSUE THREAD

**Issue by neumantm** [Exawind/nalu-wind#1105]
As an external contributor I'd appreciate to have more documentation about the existing software development infrastructure.
This would help understanding how things work and what is going on.

Specific points I'm thinking about:
- About the docker container [ecpe4s/exawind-snapshot](https://hub.docker.com/r/ecpe4s/exawind-snapshot)
  - Where is it defined? / What is the Dockerfile?
  - How, when, from which version of the Dockerfile is it built? / What exactly is the workflow for building it? / Where is the ci building it defined?
- (Less important, as it can be determined by reading the ci definition) What does the ci do?
  - Which static analysis is run?
  - Does it also check the docs?
  - Which tests does the ci run and which tests does the ci not run?

**Comment by psakievich** [comment]
@neumantm the docker container is created for us by an external collaborator in the E4S project.  @eugeneswalker will you provide the link to the correct repo that contains the definition?

Essentially it is just a base ubuntu image with a gcc@9.4.0 pre-installed.  We then use [spack-manager](https://github.com/sandialabs/spack-manager) to install `exawind+hypre+openfast`.

The CI re-uses all the TPLS and then just rebuild nalu-wind, and we only run the unit-tests.  I'd like to add in a subset of regression tests at some point too, but we currently don't store up-to-date golds in the repo so we'd need to update that process for the CI.

That static analysis right now is only doing a style check of the cpp code and doesn't check docs.  We are using clang-format from clang@13 for our style checks.

Improving the CI is definitely something on the todo list so if you want to contribute there we'd be more than happy to have the assistance 😁.

**Comment by eugeneswalker** [comment]
> @neumantm the docker container is created for us by an external collaborator in the E4S project. @eugeneswalker will you provide the link to the correct repo that contains the definition?

The Dockerfile and CI are here:
* https://gitlab.e4s.io/uo-public/exawind-snapshot

This runs once a day, in the morning, and generates the exawind-snapshot container image and pushes it to DockerHub.

**Comment by neumantm** [comment]
Thank you for this infos.
I'd create a MR adding this to the developer docs, if that is alright.

**Comment by psakievich** [comment]
> > @neumantm the docker container is created for us by an external collaborator in the E4S project. @eugeneswalker will you provide the link to the correct repo that contains the definition?
> 
> The Dockerfile and CI are here:
> 
> * https://gitlab.e4s.io/uo-public/exawind-snapshot
> 
> This runs once a day, in the morning, and generates the exawind-snapshot container image and pushes it to DockerHub.

@ajpowelsnl this is the docker container you should look at to see how we use spack-manager.  I gave you the wrong link in our meeting the other day.

**Comment by ajpowelsnl** [comment]
Hi @psakievich, @jrood-nrel  -- Thanks!  I'll look into getting this info into the working base image on Perlmutter.
