### ISSUE TITLE
FYI: Package definition for Nalu-Wind for the nix package manager

### ISSUE THREAD

**Issue by neumantm** [Exawind/nalu-wind#1131]
I just wanted to let you know that I have packaged Nalu-Wind for the [nix package manager](https://nixos.org/).
The package definition can be found under [neumantm/nalu-wind-nix](https://github.com/neumantm/nalu-wind-nix).

Basically it just is a machine-readable (in the nix language) description of how to install Nalu-Wind, Nalu-Wind-Utils from source (including all their dependencies).

If you see any value for the nalu-wind project in it I'm open to discuss how to proceed (add a link to the docs, transfer the repo to Exawind, ...).
Otherwise, feel free to just close this issue.

**Comment by psakievich** [comment]
We're pretty in on Spack right now. Nix is a little off my radar, but the easier the code is to build the better.  I don't know if we need to add a docs section since none of the core development team is using it and would support it, but thanks for doing it none-the-less.
