### ISSUE TITLE
Possibility to delete results of running unittestX

### ISSUE THREAD

**Issue by neumantm** [Exawind/nalu-wind#1134]
Is there a way to easily delete all the files created by the unit tests when running `unittestX`?

If not, It might be useful to add this.

**Comment by psakievich** [comment]
Each unit test should cleanup after itself so we can run them in isolation.

**Comment by alanw0** [comment]
I'm working on the unit tests currently, I agree that each unit test should clean up after itself if it makes a file. Do we know particular unit tests? I guess I can just run them all and see what's left behind.
