### ISSUE TITLE
Testfailures in docker container

### ISSUE THREAD

**Issue by neumantm** [Exawind/nalu-wind#1136]
When running `unittestX` in [the docker container](https://hub.docker.com/r/ecpe4s/exawind-snapshot) I get test failures in the following tests.
```
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] ActuatorBulkFastTests.NGP_initializeActuatorBulk
[  FAILED  ] ActuatorBulkFastTests.NGP_epsilonTowerAndAnisotropicEpsilon
[  FAILED  ] ActuatorFunctorFastTests.NGP_runUpdatePoints
[  FAILED  ] ActuatorFunctorFastTests.NGP_runAssignVelAndComputeForces
[  FAILED  ] ActuatorBulkDiskFastTest.NGP_fastPointIndexLocator
[  FAILED  ] ActuatorBulkDiskFastTest.NGP_computeSweptPointCountUniform
[  FAILED  ] ActuatorBulkDiskFastTest.NGP_computeSweptPointCountVaried
[  FAILED  ] ActuatorBulkDiskFastTest.NGP_sweptPointsPopulatedUniform
[  FAILED  ] ActuatorBulkDiskFastTest.NGP_sweptPointsPopulatedVaried
```
Log of the relevant section:
[nalu-test-failure-in-container.txt](https://github.com/Exawind/nalu-wind/files/10707679/nalu-test-failure-in-container.txt)

I can reproduce this in at least the containers with the following tags: [2023-02-05](https://hub.docker.com/layers/ecpe4s/exawind-snapshot/2023-02-05/images/sha256-eefc14e090cea2ac697fc1146820497a2644655068fe2f2289aac04dac187554?context=explore), [2023-02-10](https://hub.docker.com/layers/ecpe4s/exawind-snapshot/2023-02-10/images/sha256-e6d5e0436cd1395041f6949707397a112e472b90f4de121cd9ec2011efff30f6?context=explore)

**Comment by psakievich** [comment]
Thanks for posting this. I thought we had an issue open on it but it looks like #979 is the closest one. I believe I know what the issue is here but I haven't had time to fix it yet. We turn off the openfast based unit tests in the CI right now because of this. It doesn't fail on the nightly test platforms. Which is fun. 🫠

**Comment by marchdf** [comment]
@psakievich is this still an issue? Seems to me like the docker container is running ok AFAIK.

**Comment by psakievich** [comment]
Seems like it is okay to me looking at CI.
