### ISSUE TITLE
Building Nalu Wind - Step 4: Machine name not found

### ISSUE THREAD

**Issue by matheusseidel** [Exawind/nalu-wind#1138]
Greetings,

I'm trying to install and learn to use Nalu Wind by fallowing the step by step on the User Manual ([https://nalu-wind.readthedocs.io/en/latest/source/user/build_spack.html](url)). I'm using WSL - Ubunto subsystem on a Windows 11 computer.

Step 4 consistis of

`cd ${HOME} && git clone https://github.com/exawind/build-test.git`
`cd ${HOME}/build-test/configs && ./setup-spack.sh`

But when I try to run `./setup-spack.sh` I only get `Machine name not found`.

I tried running `spack info nalu-wind`and it seemed to work. It shows the description, homepage, versions, variants and dependencies.

How can I solve the `Machine name not found` problem?

Thanks.

**Comment by psakievich** [comment]
The machine name not found message doesn't really matter. It just means the machine you are working on isn't one that the script is configure for i.e. modules to load and bee built binaries. Spack will install the missing tpl's for you so it shouldn't really be an issue.

**Comment by psakievich** [comment]
@jrood-nrel do we want to update this section of the docs? Is that script still usable on eagle and other platforms? It seems like for a raw Linux install it doesn't really do anything.

**Comment by matheusseidel** [comment]
Ok. Thanks!

**Comment by psakievich** [comment]
Closing for now. Please re-open if that was premature.
