### ISSUE TITLE
What is the minimum requirement for workstation hardware required to install nalu-wind

### ISSUE THREAD

**Issue by drijazfazil** [Exawind/nalu-wind#1149]
Hi I need to a CFD analyses of wake effect of a single wind turbine in different atmospheric boundary layer. I have mobile workstation with 16 gb RAM. It has windows installed in default but I have installed ubuntu 14.04 via VMware. Is it good enough ?

**Comment by psakievich** [comment]
This will work to install the code and run basic cases. We develop and run it on laptops regularly. In terms of running a single wind turbine for scientific purposes it is likely much too small to do ABL's with different stability states.  ABL's are going to require a large domain to form the right structures, they need to run for a long time, and further more to do turbines you will need to locally refine.  Without further details of what you are hoping to run it is hard to give a more specific answer.

**Comment by psakievich** [comment]
I am going to close this. Feel free to reopen if it is not resolved
