### ISSUE TITLE
Help for using Nalu-Wind for the first time

### ISSUE THREAD

**Issue by matheusseidel** [Exawind/nalu-wind#1152]
Hello,

I'm just starting to use Nalu-Wind and I'm having lots of troubles installing it. Sorry if my questions seem silly.

I tried installing Nalu-Wind on WSL fallowing the step by step on the user manual, but I had some errors I coudn't solve. I tried solving them as stated in [https://github.com/Exawind/nalu-wind/issues/1140](url), but I couldn't, so I started using Docker on windows 11.

I was able to install and load the container by running `docker run -it ecpe4s/exawind-snapshot bash` and `spack load nalu-wind`.

I kept reading the user manual and I got to the "Examples" section [https://nalu-wind.readthedocs.io/en/latest/source/user/examples/introduction.html](url), but all the instructions don't seem to apply to docker. Is there any documentation dedicated to running Nalu-Wind on docker? Once I'm inside the docker container, how can I get the input files and run them?

I would like to run the exemple files avaiable in [https://github.com/Exawind/nalu-wind/tree/master/examples](url), but I don't know how to get to them through docker container. 

By the way, the download of the Nalu-Wind folder ([https://github.com/Exawind/nalu-wind](url)) isn't part of the step by step shown in the user manual. Only the command file `cd ${HOME} && git clone https://github.com/exawind/build-test.git` is given on Step 4. Shouldn't the download of the Nalu-Wind folder (where the examples are) be a part of the installation process?

Thanks.

**Comment by psakievich** [comment]
@matheusseidel there are a lot of things going on here. You have pointed out many valid issues.  Many of the things you point out are holes in our current documentation and support to external users.  Also concerning the examples cases please be aware of #836 and #1070. Perhaps to streamline supporting you, it would be helpful to understand what your end goal is for the software. Do you wish to use it primarily for engineering and/or scientific analysis, or are you going to be building the code and testing it to develop?

Part of the reason I ask is your machine running WSL may not be beefy enough to do anything substantial.  We do run the code on laptops, but it is primarily for software development and running small scale tests.  We also almost exclusively use Mac's and linux machines so you may be the first person trying to install on WSL and are pioneering new territory.

The docker container was generated to drive our CI process here on github. It is a bonus that it makes it easier for users to start running the code without having to build it, but it hasn't been fleshed out to make it an end user tool.

To run files in the docker container you need to activate the nalu-wind executable through spack:

`spack load nalu-wind`

and, yes, you will also need to clone the repo or mount the files you want to run inside the container as well. As stated in #836 and #1070 many of the examples are currently out of date and need to be updated. It would be a good idea to reference the regression tests (see #836).

**Comment by matheusseidel** [comment]
> @matheusseidel there are a lot of things going on here. You have pointed out many valid issues. Many of the things you point out are holes in our current documentation and support to external users. Also concerning the examples cases please be aware of #836 and #1070. Perhaps to streamline supporting you, it would be helpful to understand what your end goal is for the software. Do you wish to use it primarily for engineering and/or scientific analysis, or are you going to be building the code and testing it to develop?
> 
> Part of the reason I ask is your machine running WSL may not be beefy enough to do anything substantial. We do run the code on laptops, but it is primarily for software development and running small scale tests. We also almost exclusively use Mac's and linux machines so you may be the first person trying to install on WSL and are pioneering new territory.
> 
> The docker container was generated to drive our CI process here on github. It is a bonus that it makes it easier for users to start running the code without having to build it, but it hasn't been fleshed out to make it an end user tool.
> 
> To run files in the docker container you need to activate the nalu-wind executable through spack:
> 
> `spack load nalu-wind`
> 
> and, yes, you will also need to clone the repo or mount the files you want to run inside the container as well. As stated in #836 and #1070 many of the examples are currently out of date and need to be updated. It would be a good idea to reference the regression tests (see #836).

Ok. Thank you.
