### ISSUE TITLE
Overset issue with mesh motion

### ISSUE THREAD

**Issue by neilmatula** [Exawind/nalu-wind#1179]
There appears to be some strange behavior when multiple mesh blocks are defined, but mesh motion is only provided on some of them.
This was observed for a case with rigid-body rotation prescribed for the rotor, but a stationary tower.
In this case, the overset seems to be calculated wrong for the tower, as in the attached screenshot.  The residuals also blow up, particularly TKE.
However, if zero mesh motion is explicitly provided for the tower in the mesh motion input block, everything is fine.
So it would seem that mesh motion has to be explicitly defined on all blocks, even if they are not intended to move.
![Screen Shot 2023-04-27 at 5 56 28 PM](https://user-images.githubusercontent.com/72527988/235249147-0a85cd87-ac13-49b1-beb0-bee0ca779cf1.png)

**Comment by ashesh2512** [comment]
Note, this behavior has only been seen with hybrid solver. Traditionally, nalu-wind overset runs have always made use of stationary blocks. However, this is a nalu-wind bug because this most likely has to do with the current coordinates not being updated properly before being sent to TIOGA.
