### ISSUE TITLE
Registration of interior algs needs to use a partvec instead of a part

### ISSUE THREAD

**Issue by psakievich** [Exawind/nalu-wind#1183]
The current infrastructure is looping over parts where a partvec could be assembled instead. It will require a lot of code changes but it will improve things.

https://github.com/Exawind/nalu-wind/blob/472317ff83d8b20f0775a0ea1ea66030d5bb13f9/src/EquationSystems.C#L342-L359

**Comment by marchdf** [comment]
I think this is fixed, looking at the history. Closing. Please reopen if not.

**Comment by psakievich** [comment]
It's partially complete but not needed unless someone plans to pursue the SmartFields concept further. I don't see myself having time to devote to that in the near future.
