### ISSUE TITLE
Unit Test Failure (in ScratchViews) on (NERSC) Perlmutter

### ISSUE THREAD

**Issue by ajpowelsnl** [Exawind/nalu-wind#1186]
Running the unit test executable (`./unittestX`) hits this test failure:

```
[ RUN      ] Hex8MeshWithNSOFields.NGPScratchViews
:0: : block: [0,0,0], thread: [0,0,0] Assertion `ERROR, femGradOp and femShiftedGradOp both requested.: /global/homes/a/ajpowel/nalu_wind_ECP_supercontainers/nalu-wind/include/ScratchViews.h:672` failed.
cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /global/homes/a/ajpowel/nalu_wind_ECP_supercontainers/nalu-wind/nw_packages/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:133
```

Here is my dev environment:

```
ajpowel@perlmutter:login29:~/nalu_wind_ECP_supercontainers/nalu-wind/nw_packages/Trilinos> echo $MPICH_CXX
/global/homes/a/ajpowel/nalu_wind_ECP_supercontainers/nalu-wind/nw_packages/Trilinos/packages/kokkos/bin/nvcc_wrapper

ajpowel@perlmutter:login29:~/nalu_wind_ECP_supercontainers/nalu-wind/nw_packages/Trilinos> module list

Currently Loaded Modules:
  1) craype-x86-milan                        7) craype-accel-nvidia80  13) craype/2.7.20            19) cudatoolkit/11.7
  2) libfabric/1.15.2.0                      8) gpu/1.0                14) gcc/11.2.0               20) evp-patch
  3) craype-network-ofi                      9) PrgEnv-gnu/8.3.3       15) perftools-base/23.03.0   21) python/3.9-anaconda-2021.11
  4) xpmem/2.5.2-2.4_3.44__gd0f7936.shasta  10) cray-dsmml/0.2.2       16) cpe-cuda/23.03           22) cmake/3.24.3
  5) cpe/23.03                              11) cray-libsci/23.02.1.1  17) Nsight-Compute/2022.1.1
  6) xalt/2.10.2                            12) cray-mpich/8.1.25      18) Nsight-Systems/2022.2.1
```

I can provide the Trilinos configuration, if that would be helpful.

**Comment by psakievich** [comment]
What version of Trilinos are you using? @overfelt this looks like it could be related to some of the recent refactors.  I don't think we've really done much work on Pearlmutter. @jrood-nrel is the only one I know on the team who has worked on that machine for this application.

**Comment by ajpowelsnl** [comment]
Hi @psakievich -- I am using a recent pull of `develop` for this build.

**Comment by overfelt** [comment]
I can not duplicate this with Cuda-11.2.2 / gcc-10.3.0 on Linux and looking at the code, it does not appear the test uses FEM_GRAD_OP or FEM_SHIFTED_GRAD_OP. If we do not have access to Perlmutter, is there something similar we could run on?

**Comment by ajpowelsnl** [comment]
> I can not duplicate this with Cuda-11.2.2 / gcc-10.3.0 on Linux and looking at the code, it does not appear the test uses FEM_GRAD_OP or FEM_SHIFTED_GRAD_OP. If we do not have access to Perlmutter, is there something similar we could run on?

@overfelt - I can pair with you on Perlmutter.  FWIW, both my gcc + cuda versions were ahead of those you mention above.

**Comment by overfelt** [comment]
I can pair program tomorrow sometime.  My schedule is wide open.  It looks like this line ElemDataRequestsGPU.C:42
    `hostDataEnums[ctype](i++) = d;`
would have to have entries that use d == FEM_GRAD_OP and d == FEM_SHIFTED_GRAD_OP for the same value of ctype in order to trigger this error later on about using both at the same time.  We could start there.

**Comment by overfelt** [comment]
The latest:
[ RUN      ] Simd.Views
Kokkos::View ERROR: attempt to access inaccessible memory space (label="DoubleView")
This test is host only and should not be run on Perlmutter.
