### ISSUE TITLE
New Warnings

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#12]
@sayerhs @rcknaus Lots of warnings showed up with Clang after https://github.com/Exawind/nalu-wind/pull/10 . Are these able to be resolved?

**Comment by sayerhs** [comment]
Clang expects us to use `override` on all overridden functions if we use it once, so the option now is to either be consistent or not use override on all the MasterElement subclasses. @rcknaus what option would you prefer?

**Comment by sayerhs** [comment]
The quickest fix is to remove `override` qualifier from `include/Hex8CVFEM.h:180`

**Comment by rcknaus** [comment]
I just removed the override specifier from that line.  The better solution is probably to use override consistently, but it's not a priority.

**Comment by jrood-nrel** [comment]
It looks like this fixed warnings and created new ones.

**Comment by sayerhs** [comment]
Now this is on `include/master_element/Tet4CVFEM.h`. Curious why these warnings weren't there in yesterday's CDash output. 🤔

**Comment by jrood-nrel** [comment]
@sayerhs Maybe because it cuts off after 50 warnings?

**Comment by spdomin** [comment]
I do not see the use-case for override - frankly. The compiler knows what is virtual and not. In this case, adding override on any virtual master element method seems to be extra work on our part in keeping it straight.

I vote to avoid override - that is, unless I am missing something?

**Comment by sayerhs** [comment]
@spdomin Actually, the C++ compiler will not be aware that the method is overriding a virtual method in the Base class unless the method signature matches exactly. In this situation, it will just treat this as an overloaded method and might still use the base class method depending on the arguments provided. The intent of the `override` specifier is to be explicit about the intent so that the compiler can generate an error if it detects that the signature doesn't match exactly. Obligatory [StackOverflow](https://stackoverflow.com/questions/13880205/is-the-override-keyword-just-a-check-for-a-overridden-virtual-method)

**Comment by spdomin** [comment]
@sayerhs, thank you for this info from StackOverflow. I suppose that I was assuming that a developer who wants to implement a viral method that is used in the derived class would have implemented the same signature. 

I guess I still do not have the end use case correct in my head. I know that in the past, virtual methods with the same name, however, different signature would provide a "hidden" warning. 

If someone has a StackOverflow example where using override is useful, that would be nice to see for my learning.

**Comment by spdomin** [comment]
agreed. thanks.

**Comment by jrood-nrel** [comment]
I think some changes to Trilinos on July 6 are causing new warnings with GCC 7.3.0. I don't see any commits near July 6 for Nalu-Wind that are causing these since the warnings began on July 7.
```
nalu-wind/include/CopyAndInterleave.h:88:32: warning: 'smemviews[1]' may be used uninitialized in this function
```

**Comment by alanw0** [comment]
@jrood-nrel I'll try to take care of this no later than tomorrow if nobody beats me to it.

**Comment by jrood-nrel** [comment]
@alanw0 It looks like the Intel compiler has some new warnings due to https://github.com/Exawind/nalu-wind/commit/1c170cafc6c3d196b706ce275692ee68c720cbbf . It's surprising that it's complaining it can't contain an expression though. I don't know if it's worth adding an extra variable to contain the expression results which would be my first guess at a solution.

```
nalu-wind/unit_tests/UnitTestShmemAlignment.C(18): warning #3464: the standard "alignof" operator does not accept an expression argument
```

**Comment by alanw0** [comment]
@jrood-nrel that is indeed weird, I'll add the variable.

**Comment by jrood-nrel** [comment]
So I am seeing a new set of warnings of deprecations due to a Trilinos update, for example:
```
nalu-wind/include/LinearSolver.h:31:32: warning: 'DefaultPlatform' is deprecated
trilinos-develop-tmv3bmqj4gfd23vyty6ddf6xebivdtth/include/TpetraClassic_config.h:32:47: note: expanded from macro 'TPETRA_DEPRECATED'
trilinos-develop-tmv3bmqj4gfd23vyty6ddf6xebivdtth/include/Tpetra_MpiPlatform.hpp:300:9: note: 'MpiPlatform >' has been explicitly marked deprecated here
```

**Comment by jrood-nrel** [comment]
Thanks for taking care of the warnings @sayerhs ! I'm going to close this since there currently aren't any warnings.
