### ISSUE TITLE
FAILED  Install need help

### ISSUE THREAD

**Issue by lylclclyl** [Exawind/nalu-wind#1211]
![eeab5c6d82d000edccb78fe3331b440](https://github.com/Exawind/nalu-wind/assets/101541789/20c0b9d1-f0f1-474f-9c2b-ce36647a4f5c)
We used the manual installation method and reported an error when performing the last step.
![72cd88f14391184ed298de699fc208c](https://github.com/Exawind/nalu-wind/assets/101541789/b76d94ff-7349-421f-8d14-a31824fd28af)
Which version of Trilions is it? How to solve this installation error problem?

**Comment by lylclclyl** [comment]
![a1ceb363bd2ac4e922ef9e12111e7db](https://github.com/Exawind/nalu-wind/assets/101541789/683254f6-db56-469a-9a62-8d06db4f38bc)

**Comment by ashesh2512** [comment]
Hi, could you please provide details of the system are you building this on?

**Comment by lylclclyl** [comment]
> 嗨，您能否提供您构建该系统的详细信息？

The library we are currently using is consistent with the recommendations on the website.Nalu version 1.2.0, Trilinos version 12.12.1. But the compilation to 89% reported an error.
![a3a647ed50264ebdc7e8411da0ec122](https://github.com/Exawind/nalu-wind/assets/101541789/d335c990-90d2-4b15-8f5a-64781d19c211)

**Comment by lylclclyl** [comment]
> 嗨，您能否提供您构建该系统的详细信息？

Do you mean the configuration of a supercomputer?

**Comment by ashesh2512** [comment]
> > 嗨，您能否提供您构建该系统的详细信息？
> 
> Do you mean the configuration of a supercomputer?

yes

**Comment by lylclclyl** [comment]
> > > 嗨，您能否提供您构建该系统的详细信息？
> > 
> > 
> > 你是说超级计算机的配置吗？
> 
> 是的

hi , PROCESSOR: 1 x 32-CORE 2.5GHZ FREQUENCY PROCESSOR;
Accelerators: 4 DCU accelerators;
Storage: Mount the shared storage system;

**Comment by ashesh2512** [comment]
Hi, it looks like the latest trilinos might have APIs that are incompatible with nalu-wind. We use a pinned version of trilinos. Could you please try trilinos commit `8b3e2e1db4c7e07db13225c73057230c4814706f` ?

**Comment by lylclclyl** [comment]
> 嗨，看起来最新的 trilinos 可能有与 nalu-wind 不兼容的 API。我们使用固定版本的trilinos。你能试试trilinos提交吗？`8b3e2e1db4c7e07db13225c73057230c4814706f`

What should be the library version of Trilinos?  Now, we use Nalu version 1.2.0, Trilinos version 12.12.1.

**Comment by lylclclyl** [comment]
> > 嗨，看起来最新的 trilinos 可能有与 nalu-wind 不兼容的 API。我们使用固定版本的trilinos。你能试试trilinos提交吗？`8b3e2e1db4c7e07db13225c73057230c4814706f`
> 
> What should be the library version of Trilinos? Now, we use Nalu version 1.2.0, Trilinos version 12.12.1.

![a3a647ed50264ebdc7e8411da0ec122](https://github.com/Exawind/nalu-wind/assets/101541789/a98dea39-659f-470c-887c-b3f70384ab86)

**Comment by ashesh2512** [comment]
Please use the master branch for nalu-wind and commit `8b3e2e1db4c7e07db13225c73057230c4814706f` for Trilinos.

**Comment by lylclclyl** [comment]
> commit for Trilinos.

Hello, I don't quite understand what you said commit for Trilinos. What does it mean, can you elaborate?

**Comment by ashesh2512** [comment]
Hi, are you using git to clone the repository? If not, please do so. Once you have cloned the repository, please do `git checkout -b branch_name <commit id>` from inside the master directory, to checkout a specific commit

**Comment by lylclclyl** [comment]
> 嗨，您是否使用 git 克隆存储库？如果没有，请这样做。克隆存储库后，请从主目录内部签出特定的提交`git checkout -b branch_name <commit id>`

![63a6870d0daa3bcd6b6ce8305667638](https://github.com/Exawind/nalu-wind/assets/101541789/b3358603-a9f7-4c0d-af98-b709f0b8cef7)
git checkout -b trilinos-release-12-12-1  8b3e2e1db4c7e07db13225c73057230c4814706f
git clone --recursive -b master https://github.com/Exawind/nalu-wind.git
This is our download step, but we get an error at the beginning. How can I solve it?

**Comment by ashesh2512** [comment]
Do you have hypre installed? @jrood-nrel Does anything stand out to you?

**Comment by lylclclyl** [comment]
> 你们安装了海普雷吗？有什么让你印象深刻的吗？
![50e3a8f5075df8e1803f28491b9e7b3](https://github.com/Exawind/nalu-wind/assets/101541789/578a291d-ad60-401f-aad8-71920c26cc0e)
Of course, but it still can not work, what could I do to slove the probloem.

**Comment by psakievich** [comment]
The trilinos version you are using is way too old.  Unfortunately due to the nature of this project software and hardware are evolving together and we have not had the bandwidth to cut a release consistently.

If you want to build `nalu-wind@1.3.0` try using `trilinos@13.0.1` since they are overlapping in dates.  

If you are using `nalu-wind@master` then try `trilinos@13.4.1` or the commit mentioned by @ashesh2512.

Your download step for trilinos should look like this
``` console
git clone https://github.com/trilinos/trilinos
git checkout -b master 8b3e2e1db4c7e07db13225c73057230c4814706f
```
Don't use the `trilinos-release-12-12-1` branch.

**Comment by lylclclyl** [comment]
> 您使用的trilinos版本太旧了。不幸的是，由于这个项目的性质，软件和硬件是一起发展的，我们没有足够的带宽来持续削减版本。
> 
> 如果要构建，请尝试使用，因为它们在日期上重叠。`nalu-wind@1.3.0``trilinos@13.0.1`
> 
> 如果您正在使用，请尝试或 .`nalu-wind@master``trilinos@13.4.1`
> 
> Trilinos 的下载步骤应如下所示
![9955c366c9b337f3a3fcc95c2d156a4](https://github.com/Exawind/nalu-wind/assets/101541789/1eaa8c33-56a5-41be-bf5d-1ebd23898a6f)

> 
> ```
> git clone https://github.com/trilinos/trilinos
> git checkout -b master 8b3e2e1db4c7e07db13225c73057230c4814706f
> ```
> 
> 不要使用分支。`trilinos-release-12-12-1`
![9955c366c9b337f3a3fcc95c2d156a4](https://github.com/Exawind/nalu-wind/assets/101541789/d791ee21-53ff-4c2d-872f-0b3af8d394e0)

Thanks for your reply. We compiled as you said, or failed, this is an error message. nalu-wind@1.3.0 try using trilinos@13.0.1
When editing NALU, it is said that the file is missing.
![9634a70a7070137bd0ac12ec3ef73f8](https://github.com/Exawind/nalu-wind/assets/101541789/d22220ab-6b35-44d8-987b-96b78741fd82)
I checked and this file is available in versions 14 and 12 of Trilinos, exactly what is not in version 13
git clone --recursive -b trilinos-release-13-0-1 https://github.com/trilinos/trilinos

This is my command to download trilinos, add the recursive option, I don't know what is wrong

**Comment by psakievich** [comment]
what about version 13.4.1?

**Comment by lylclclyl** [comment]
> what about version 13.4.1?
Too bad, I used 13.4.1 trilinos with the master version of nalu-wind. still having syntax compatibility issues.
![54575d12b114c700062628d785a4464](https://github.com/Exawind/nalu-wind/assets/101541789/6dffc8d0-6a15-4b68-8802-6e2c86950e4d)

**Comment by psakievich** [comment]
This case does not have trilinos configured correctly. Each post as I'm reading it has a different build error regarding trilinos. This one looks like Kokkos is not configured correctly.

Please try with the latest spack. I am going to close this issue to consolidate with the other open issues. We are not currently maintaining the old manual build instructions.
