### ISSUE TITLE
Neutral ABL example case fails, can't open mesh database

### ISSUE THREAD

**Issue by cmkaul** [Exawind/nalu-wind#122]
I am a new user of nalu-wind and, more generally, new to Trilinos. While attempting to run the Neutral ABL example case, I can't get past the following error:

Error occured at: stk_io/stk_io/InputFile.cpp:142
Error: ERROR: Could not open database 'mesh_abl.exo' of type 'exodus' 

(full error output here: https://github.com/Exawind/nalu-wind/files/2862274/nalu_abl.err.pdf ).

mesh_abl.exo was generated following the example case instructions and I don't see any glaring issues when I check it with ncdump. I've checked obvious things like the location and permissions of the mesh file, but I'm not sure how to trouble shoot beyond this.

I built nalu-wind manually with gcc/7.3.0, openmpi/1.10.1 and otherwise trying to follow the documentation as closely as possible.

Thanks!

**Comment by gantech** [comment]
Do you have this line in the input file?

`  automatic_decomposition_type: rcb`

**Comment by cmkaul** [comment]
Yes,  I do.

**Comment by jamelvin** [comment]
Hey Colleen,

Is it possible for you to upload your input file and the command you used to execute nalu-wind as well as an `ls` in your working directory?

**Comment by cmkaul** [comment]
Certainly! Thanks for the help @gantech  and @jamelvin .

My job script:
[job_script.csh.pdf](https://github.com/Exawind/nalu-wind/files/2862520/job_script.csh.pdf)
(I've also tried without the -p and -D options...)

My input file:
[abl_simulation.yaml.pdf](https://github.com/Exawind/nalu-wind/files/2862524/abl_simulation.yaml.pdf)

ls of the working directory:
<img width="719" alt="screen shot 2019-02-13 at 2 47 37 pm" src="https://user-images.githubusercontent.com/13728137/52750015-d1f04200-2f9f-11e9-96ec-6a9c4dfc35fa.png">

**Comment by jamelvin** [comment]
It seems weird to me that Nalu would try to generate 24 log files, is your parallel command being executed correctly?  Normally, I would execute 
`mpirun -np 24 naluX -i abl_simulation.yaml -o abl_simulation.log`
but each implementation can require different inputs.

If you get a chance, could you also upload abl_simulation.log?

**Comment by cmkaul** [comment]
I believe the 24 log files are a consequence of the -p flag  but this turns out not be useful as all these per-processor log files are empty. There are 24 processors per node on the machine I am using, so that checks out. 

Here is the log file:
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/2862650/abl_simulation.log)

**Comment by jamelvin** [comment]
So when I use your command, 
`mpirun naluX -p -D -i abl_simulation.yaml`
it produces some weird output for me as well.  Can you try with the command
`mpirun -np 24 naluX -i abl_simulation.yaml -o abl_simulation.log`?

**Comment by cmkaul** [comment]
So with that command, I get the single log file abl_simulation.log but everything else proceeds in the same manner as previously (same messages to stderr and stdout, same contents to abl_simulation.log)

**Comment by jamelvin** [comment]
Hey @cmkaul, I don't see anything that jumps out that could be causing this... Maybe @sayerhs can help?

**Comment by sayerhs** [comment]
@cmkaul It appears that the way Trilinos is setup, it is not doing automatic decomposition.  Can you clarify how you compiled NetCDF and Trilinos? Are you used a system provided NetCDF? If NetCDF isn't compiled properly with `parallel-netcdf` that could be the issue. Until we can troubleshoot this, can you try the following workaround: 

- Use `decomp` utility (look in `bin` directory of Trilinos install location) to pre-decompose the ExodusII file into 24 smaller files 

- Comment out the line `automatic_decomposition_type: rcb` and attempt to run the case

I also notice that your queue system is SLURM and usually uses `srun -n` instead of `mpirun -np`. You might want to change that in your job submission script also.

**Comment by sayerhs** [comment]
Can you share the output of `nc-config --all` and `pnetcdf-config --all` for your system, that might help troubleshoot this issue.

**Comment by cmkaul** [comment]
Here are the config files:
[pnetcdf_config.txt](https://github.com/Exawind/nalu-wind/files/2870540/pnetcdf_config.txt)
[nc_config.txt](https://github.com/Exawind/nalu-wind/files/2870541/nc_config.txt)
I configured hdf5 (version 1.10.4) with these options:
`./configure CC=mpicc FC=mpif90 CXX=mpicxx CXXFLAGS="-fPIC -O3" CFLAGS="-fPIC -O3" FCFLAGS="-fPIC -O3" --enable-parallel --with-zlib=${NALU_ROOT_DIR}/install/zlib --prefix=${NALU_ROOT_DIR}/install/hdf5`

The use of the mpirun command (rather than srun) with openmpi was suggested in the user guide for the cluster I am using, but I gave srun a try. On my first attempt, I forgot to specify processor number and on a single processor was able to get further:
[abl_simulation_1proc.log](https://github.com/Exawind/nalu-wind/files/2870572/abl_simulation_1proc.log 
After I corrected my job script to use  srun -n 24, I got stuck at a different point:
[abl_simulation_srun.log](https://github.com/Exawind/nalu-wind/files/2870585/abl_simulation_srun.log . I got no specific error output with this, only messages that (some) of the tasks were killed.

**Comment by cmkaul** [comment]
I was able to use the decomp utility to preprocess the decomposition of the mesh file successfully. I replaced the single mesh_abl.exo file with the decomposed files and commented out `automatic_decomposition_type: rcb` in the input [abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/2871031/abl_simulation.yaml.txt)

 But I am still seeing the error at stk_io/stk_io/InputFile.cpp:142

Output from the run below:
[abl_simulation.log.txt](https://github.com/Exawind/nalu-wind/files/2871034/abl_simulation.log.txt)
[nalu_abl.err.txt](https://github.com/Exawind/nalu-wind/files/2871032/nalu_abl.err.txt)

**Comment by sayerhs** [comment]
@cmkaul Thanks for trying that out. This is indeed a mystery. Looking at your `nc-config --all` output, it appears that NetCDF has been linked to PNetCDF correctly. The only difference I see that you are using `4.6.1` whereas we are using `4.4.1.1`, and you have linked `hdf5` to your custom `zlib` but the netcdf is linking to the system `zlib`? Not sure if this is the cause of the discrepancy. 

Were you able to get going on NREL Eagle, while we continue to troubleshoot this issue on your local system?

**Comment by cmkaul** [comment]
Thanks for persevering with me on this.  
I didn't realize I needed to also specify which `zlib` to use when building `netcdf` if I had already specified it for `hdf5`, but I'll give that a try. There are some other would-be users here, so it would be nice to figure out what works on our system.

I am planning to work again on getting going on NREL Eagle the rest of today. 

Thanks again!

**Comment by alanw0** [comment]
Usually that error message means that the mesh file is not in the current working directory. Can you attach your mesh file so that we can try reading it locally?

**Comment by cmkaul** [comment]
It's too large for me to attach here, so I've transferred it to Eagle scratch `/scratch/ckaul/neutral_abl`. I put both the single mesh and the mesh files produced by decomp and the simulation input file.

**Comment by sayerhs** [comment]
@alanw0 I can confirm that I am able to run the input file/mesh combination uploaded by @cmkaul to Eagle, both with `automatic_decomposition_type: rcb` and the single mesh and the decomposed mesh without that option in the input file.

**Comment by sayerhs** [comment]
@cmkaul For Eagle, you can use the build scripts in the projects directory under HFM allocation. Let us know if you have access to it, otherwise we will get you the relevant information.

**Comment by cmkaul** [comment]
Thanks @sayerhs, I don't have access to the build scripts under HFM.

**Comment by sayerhs** [comment]
@cmkaul Please follow the [exawind-builder](https://exawind-builder.readthedocs.io/en/latest/), use the [bootstrap script](https://exawind-builder.readthedocs.io/en/latest/installation.html#basic-installation-for-all-systems) to setup the directory structure and then skip to the `nalu-wind` [build instructions](https://exawind-builder.readthedocs.io/en/latest/basic.html#compiling-software). Note you don't have to build Trilinos on Eagle, the scripts are configured to pick the install from a central location.

**Comment by alanw0** [comment]
@sayerhs thanks for confirming that the mesh file works on eagle. So this seems to indicate that there is some issue either with her working-directory location, or with her build of one of the libraries. We'll try to make the STK IO message be more informative. I.e., it should say "file not found" or "file corrupt" or something more specific than what it produced in this case.

**Comment by cmkaul** [comment]
I was personally able to run the simulation using that mesh file on Eagle. So it is definitely some issue related to my system/my compilation of the code.
