### ISSUE TITLE
Regarding error in installation of naluwind via docker

### ISSUE THREAD

**Issue by drijazfazil** [Exawind/nalu-wind#1232]
Dear Scientists,

Dr. Ijaz Fazil from Singapore here. I apologize for contacting all of you since I'm not sure who I need to contact about installation.  We are utilizing ANSYS FLUENT to do CFD study of wind turbine rotor and wake aerodynamics. We are currently considering to employ Nalu-wind since we need to investigate the AL-LES modeling technique.

When I tried to install via docker as suggested in the link (https://nalu-wind.readthedocs.io/en/latest/source/user/build_spack.html#building-inside-docker-container) but I get the following error.

spec 'nalu-wind' matches no installed package

Kindly please let us know how to rectify this error. 
![naluwinderror](https://github.com/Exawind/nalu-wind/assets/121720634/5b963338-d61b-4d9f-9485-843c7523eb6d)

**Comment by psakievich** [comment]
There was a failure in the image build process yesterday. Can you try a slightly older image?

**Comment by psakievich** [comment]
I'm going to close due to inactivity. Feel free to reopen as needed.
