### ISSUE TITLE
When I used Spack to load the pre-installed version of Nalu-Wind, something went wrong.

### ISSUE THREAD

**Issue by Z0907Q** [Exawind/nalu-wind#1244]
Dear Scientists,
I apologize for contacting all of you since I'm not sure who I need to contact about installation.
When I run the “spack load nalu-wind” code, the following message appears.Error: Spec 'nalu-wind' matches no installed packages.
When I run the “spack install nalu-wind” code, Indicates a build problem with Trilinos。
I was worried that the description wasn't clear enough, so I took a screenshot of it.
![1](https://github.com/Exawind/nalu-wind/assets/157798348/4eb340d2-b3cb-474e-90c4-b70d210ab094)
![2](https://github.com/Exawind/nalu-wind/assets/157798348/89c4e7e3-b490-4996-9087-e6fb1fae4351)
Kindly please let us know how to rectify this error.
It would be my honor to hear from you.

**Comment by psakievich** [comment]
Have you tried this since the containers were fixed?

**Comment by psakievich** [comment]
Consolidating to #1247
