### ISSUE TITLE
About problems encountered during installation

### ISSUE THREAD

**Issue by Z0907Q** [Exawind/nalu-wind#1252]
Dear Scientist,：
I am sorry to write to you again. I am a beginner and I wanted to install and use nalu-wind, but I really ran into some problems. Please read my letter patiently. First I ran "docker pull ecpe4s/exawind-snapshot". Then I run "spack install nalu-wind". But along the way, trilinos kept running into problems that I really didn't know how to solve.
Perhaps you could write out the name of the command I should run for each step? If possible, thank you very much indeed.

**Comment by psakievich** [comment]
Steps were provided here. https://github.com/Exawind/nalu-wind/issues/1247#issuecomment-2009317280

Please try the steps and report back in that issue.

Closing as redundant to #1247.
