### ISSUE TITLE
 Assistance Needed with Overset Mesh Configuration in Nalu-Wind Using TIOGA

### ISSUE THREAD

**Issue by physicsWorks42** [Exawind/nalu-wind#1263]
Dear Exawind-Community

I am currently running a simulation that utilizes the overset method with the TIOGA library, involving three distinct meshes: the background mesh, wake refinement, and a cylinder. My interest in this setup was piqued by the Nalu-Wind documentation on TIOGA, which discusses a similar case ([see documentation](https://nalu-wind.readthedocs.io/en/latest/source/theory/overset.html)). Unfortunately, I could not find the specific mesh described, so I created a new one (see attachment).

After setting up and running Nalu-Wind with this new mesh, I encountered some issues with how TIOGA handles the mesh interfaces. Ideally, I would like the background mesh to only have hole-nodes corresponding to the wake (a square), and the wake to only have hole-nodes around the cylinder (a circle), as illustrated in the documentation here:
<img width="425" alt="image" src="https://github.com/Exawind/nalu-wind/assets/157244420/b15d00b7-566f-46a4-abb8-eb24d8c24c23">

However, my current mesh configuration appears as follows:
<img width="665" alt="hole-cells" src="https://github.com/Exawind/nalu-wind/assets/157244420/7d2a37b7-2c53-492b-801d-2f0de3dc0752">

Included in the attachment are the mesh file and the input YAML file configured for the latest Nalu-Wind release (2.0.0).

I would greatly appreciate any guidance on how to achieve a more accurate hole-cell configuration similar to the one shown in the documentation. Has anyone successfully run the original case or a similar one with a "neat" hole-cell setup? Any advice on adjusting my YAML input file to improve the mesh handling would be very helpful.

Thank you in advance for any assistance you can provide.

[bm_wake_cylinder.zip](https://github.com/Exawind/nalu-wind/files/15457530/bm_wake_cylinder.zip)

**Comment by itopcuoglu** [comment]
Does your simulation run to completion?

**Comment by physicsWorks42** [comment]
> Does your simulation run to completion?

Yes, the simulation runs to completion. However, the solution appears awkward because the nodes within the solid structure (the cylinder, in this case) are not designated as holes, as illustrated in my images.

**Comment by psakievich** [comment]
@itopcuoglu any updates on this one?

**Comment by itopcuoglu** [comment]
I haven't looked into this yet. This is potentially related to another bug we encountered, which I'm going investigate soon.

**Comment by itopcuoglu** [comment]
@physicsWorks42 You need to change the variable `symmetry_direction` under `tioga_options` from 2 to 3. The hole map functionality works differently when that value is not set to 3. The iblank fields look as expected when that is corrected.

Also, you do not need the `set_resolutions: no` option. That has recently been made obsolete, and it was not necessary even prior to that. Let me know if this resolves your issue.

![background](https://github.com/Exawind/nalu-wind/assets/114435459/b201e9f4-4c8c-4e06-9dcc-d66060acb482)
![sphere](https://github.com/Exawind/nalu-wind/assets/114435459/7eafd267-191d-4e39-9ed8-a97392a5a675)
![wake](https://github.com/Exawind/nalu-wind/assets/114435459/ad9ae71c-3fea-44eb-b4ba-5942d95c154c)

**Comment by jrood-nrel** [comment]
Please reopen this if @itopcuoglu 's suggestion hasn't helped.

**Comment by physicsWorks42** [comment]
Thanks @itopcuoglu, sorry for the late reply. Everything works fine now!
