### ISSUE TITLE
Problem with Naluwind installation

### ISSUE THREAD

**Issue by Chengyue810** [Exawind/nalu-wind#1264]
The following problem occurs when I install with spack on Ubuntu system. Is it caused by incompatibility of trilinos? How can I solve it

==> Installing nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r [45/45]
==> No binary for nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r found: installing from source
==> Using cached archive: /home/chy810/spack/var/spack/cache/_source-cache/git//exawind/nalu-wind.git/v2.0.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for nalu-wind
==> nalu-wind: Executing phase: 'cmake'
==> nalu-wind: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     196    [ 12%] Building CXX object CMakeFiles/nalu.dir/src/PostProcessingInfo.C.o
     197    /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/openmpi-5.0.3-r4kng7srrgnomjqjfgnjnmuipockizn2/bin/mpic++ -DNALU_HAS_MATRIXFREE -DNALU_USES_HYPRE -DNALU_USES_T
            RILINOS_SOLVERS -Dnalu_EXPORTS -I/tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/include -I/tmp/chy810/spack-stage/spack-stage-
            nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-build-ioqhzl3/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/trilinos-13.4.1-vhkjvysoa
            pjxdo5xb2fhg5f4magg7ayt/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hdf5-1.14.3-7bare5uietkdryuu34vavwtvqjqhqz7l/include -isystem /home/ch
            y810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/zlib-ng-2.1.6-e5kdwtmhcexszyk6qv7ajr4v744o6pcv/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc
            -11.4.0/parmetis-4.0.3-4dffusaoeuvtqztmvs77zvmbblscpsea/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/metis-5.1.0-2ao4az5q5ljlfw56tuu5ag7mgf
            rcxb5y/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/openblas-0.3.26-snxzq5ol42uhhahm6f6hb5lhrysbgx3j/include -isystem /home/chy810/spack/op
            t/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hwloc-2.9.1-nmia4pnv6ooixxdrhkczoucalvj4advi/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/netcdf-
            c-4.9.2-de324jekfkn5me5ox34bqw46h7yfhrqd/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/parallel-netcdf-1.12.3-72ctrso4zxniqhfinui3whj5pz26sz
            6q/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/cgns-4.4.0-ibjpdeekqe5edk5fvpwwdewqevt752pa/include -isystem /home/chy810/spack/opt/spack/l
            inux-ubuntu22.04-zen3/gcc-11.4.0/matio-1.5.26-sotpibbn7jiygi3taavi4ga4ipsnnapx/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hypre-2.31.0-ub
            4aotaev4mf2a2zsqorwmtksnyttkf7/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/yaml-cpp-0.7.0-63kpgfyw7yvt4vgzccbxa6eiipxdhx47/include -DUSE_S
            TK_SIMD_NONE -O3 -DNDEBUG -std=c++17 -fPIC -Wall -Wextra -pedantic -faligned-new -MD -MT CMakeFiles/nalu.dir/src/PostProcessingInfo.C.o -MF CMakeFiles/nalu.dir/src/PostProces
            singInfo.C.o.d -o CMakeFiles/nalu.dir/src/PostProcessingInfo.C.o -c /tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/src/PostPro
            cessingInfo.C
     198    [ 12%] Building CXX object CMakeFiles/nalu.dir/src/ProjectedNodalGradientEquationSystem.C.o
     199    /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/openmpi-5.0.3-r4kng7srrgnomjqjfgnjnmuipockizn2/bin/mpic++ -DNALU_HAS_MATRIXFREE -DNALU_USES_HYPRE -DNALU_USES_T
            RILINOS_SOLVERS -Dnalu_EXPORTS -I/tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/include -I/tmp/chy810/spack-stage/spack-stage-
            nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-build-ioqhzl3/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/trilinos-13.4.1-vhkjvysoa
            pjxdo5xb2fhg5f4magg7ayt/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hdf5-1.14.3-7bare5uietkdryuu34vavwtvqjqhqz7l/include -isystem /home/ch
            y810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/zlib-ng-2.1.6-e5kdwtmhcexszyk6qv7ajr4v744o6pcv/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc
            -11.4.0/parmetis-4.0.3-4dffusaoeuvtqztmvs77zvmbblscpsea/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/metis-5.1.0-2ao4az5q5ljlfw56tuu5ag7mgf
            rcxb5y/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/openblas-0.3.26-snxzq5ol42uhhahm6f6hb5lhrysbgx3j/include -isystem /home/chy810/spack/op
            t/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hwloc-2.9.1-nmia4pnv6ooixxdrhkczoucalvj4advi/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/netcdf-
            c-4.9.2-de324jekfkn5me5ox34bqw46h7yfhrqd/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/parallel-netcdf-1.12.3-72ctrso4zxniqhfinui3whj5pz26sz
            6q/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/cgns-4.4.0-ibjpdeekqe5edk5fvpwwdewqevt752pa/include -isystem /home/chy810/spack/opt/spack/l
            inux-ubuntu22.04-zen3/gcc-11.4.0/matio-1.5.26-sotpibbn7jiygi3taavi4ga4ipsnnapx/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hypre-2.31.0-ub
            4aotaev4mf2a2zsqorwmtksnyttkf7/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/yaml-cpp-0.7.0-63kpgfyw7yvt4vgzccbxa6eiipxdhx47/include -DUSE_S
            TK_SIMD_NONE -O3 -DNDEBUG -std=c++17 -fPIC -Wall -Wextra -pedantic -faligned-new -MD -MT CMakeFiles/nalu.dir/src/ProjectedNodalGradientEquationSystem.C.o -MF CMakeFiles/nalu.
            dir/src/ProjectedNodalGradientEquationSystem.C.o.d -o CMakeFiles/nalu.dir/src/ProjectedNodalGradientEquationSystem.C.o -c /tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-
            ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/src/ProjectedNodalGradientEquationSystem.C
     200    [ 13%] Building CXX object CMakeFiles/nalu.dir/src/Realm.C.o
     201    /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/openmpi-5.0.3-r4kng7srrgnomjqjfgnjnmuipockizn2/bin/mpic++ -DNALU_HAS_MATRIXFREE -DNALU_USES_HYPRE -DNALU_USES_T
            RILINOS_SOLVERS -Dnalu_EXPORTS -I/tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/include -I/tmp/chy810/spack-stage/spack-stage-
            nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-build-ioqhzl3/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/trilinos-13.4.1-vhkjvysoa
            pjxdo5xb2fhg5f4magg7ayt/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hdf5-1.14.3-7bare5uietkdryuu34vavwtvqjqhqz7l/include -isystem /home/ch
            y810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/zlib-ng-2.1.6-e5kdwtmhcexszyk6qv7ajr4v744o6pcv/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc
            -11.4.0/parmetis-4.0.3-4dffusaoeuvtqztmvs77zvmbblscpsea/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/metis-5.1.0-2ao4az5q5ljlfw56tuu5ag7mgf
            rcxb5y/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/openblas-0.3.26-snxzq5ol42uhhahm6f6hb5lhrysbgx3j/include -isystem /home/chy810/spack/op
            t/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hwloc-2.9.1-nmia4pnv6ooixxdrhkczoucalvj4advi/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/netcdf-
            c-4.9.2-de324jekfkn5me5ox34bqw46h7yfhrqd/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/parallel-netcdf-1.12.3-72ctrso4zxniqhfinui3whj5pz26sz
            6q/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/cgns-4.4.0-ibjpdeekqe5edk5fvpwwdewqevt752pa/include -isystem /home/chy810/spack/opt/spack/l
            inux-ubuntu22.04-zen3/gcc-11.4.0/matio-1.5.26-sotpibbn7jiygi3taavi4ga4ipsnnapx/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/hypre-2.31.0-ub
            4aotaev4mf2a2zsqorwmtksnyttkf7/include -isystem /home/chy810/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/yaml-cpp-0.7.0-63kpgfyw7yvt4vgzccbxa6eiipxdhx47/include -DUSE_S
            TK_SIMD_NONE -O3 -DNDEBUG -std=c++17 -fPIC -Wall -Wextra -pedantic -faligned-new -MD -MT CMakeFiles/nalu.dir/src/Realm.C.o -MF CMakeFiles/nalu.dir/src/Realm.C.o.d -o CMakeFil
            es/nalu.dir/src/Realm.C.o -c /tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/src/Realm.C
  >> 202    /tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-src/src/Realm.C:116:10: fatal error: stk_mesh/base/MeshBuilder.hpp: No such file or
             directory
     203      116 | #include <stk_mesh/base/MeshBuilder.hpp>
     204          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     205    compilation terminated.
  >> 206    make[2]: *** [CMakeFiles/nalu.dir/build.make:1087: CMakeFiles/nalu.dir/src/Realm.C.o] Error 1
     207    make[2]: *** Waiting for unfinished jobs....
     208    make[2]: Leaving directory '/tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-build-ioqhzl3'
  >> 209    make[1]: *** [CMakeFiles/Makefile2:708: CMakeFiles/nalu.dir/all] Error 2
     210    make[1]: Leaving directory '/tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-build-ioqhzl3'
  >> 211    make: *** [Makefile:139: all] Error 2

See build log for details:
  /tmp/chy810/spack-stage/spack-stage-nalu-wind-2.0.0-ioqhzl3bpqrufqbobx7cv46apgjbne5r/spack-build-out.txt

**Comment by psakievich** [comment]
Try adding `~trilinos-solvers` to your spec. I think we have some compatibility issues that need to get updated in the trilinos stack with the latest trilinos versions.

**Comment by tasmith4** [comment]
Hi @Chengyue810, we recommend using the master branch of nalu-wind (it looks like your spack may have picked up an old version).  Also, make sure you are using `trilinos@15.1.1`, if spack doesn't pick that up automatically you may need to force it by adding `^trilinos@15.1.1` to your spec.  I was successfully able to build `nalu-wind@master ^trilinos@15.1.1`, so I think these compatibility issues you notice are related to the older versions of nalu-wind and trilinos in your spack spec.

Closing this issue for now, but please feel free to reopen with additional information if a build of `nalu-wind@master` is not working for you.
