### ISSUE TITLE
FSI build with current OpenFAST dev can't find include

### ISSUE THREAD

**Issue by ndevelder** [Exawind/nalu-wind#1304]
I'm getting this when I build with +fsi

```
  >> 33    CMake Error at CMakeLists.txt:276 (target_link_libraries):
     34      Cannot find source file:
     35    
     36        /projects/wind/hpc/wind/ndeveld/em-exawind-flight/spack/opt/spack/linux-rhel8-sapphirerapids/intel-2023.2.0/openfast-develop-pgz3za5fkapqx45y4dekq6agvkr2oejj/MAP_Types.h
```

And this is because MAP_Types.h got moved to the subdirectory "mappp"

Attempting to add variable in CMakeLists.txt to directly target this directory. If anyone knows how to do this quickly, you'd probably save me time.

**Comment by mbkuhn** [comment]
what part of the build process leads to this? Is it while building openfast, nalu-wind, or exawind-driver?

**Comment by ndevelder** [comment]
It's while building Nalu-Wind

**Comment by marchdf** [comment]
I think this was fixed in openfast. I was able to build dev today.
