### ISSUE TITLE
Should I use exawind-manager to build Nalu-Wind and how to it

### ISSUE THREAD

**Issue by mstoell** [Exawind/nalu-wind#1318]
Hi,

I have successfully built  AMR-Wiind with the exawind-manager on my Red Hat Enterprise Linux 8.8 system. However, there are no instructions on how to build Nalu-Wind. I tried the basic "spack --debug --stacktrace install nalu-wind" but this fails (see attached log: 
[NaluWind.txt](https://github.com/user-attachments/files/17368634/NaluWind.txt)
).

"spack compilers" outputs:
==> Available compilers
-- gcc rhel8-x86_64 ---------------------------------------------
gcc@8.5.0

-- intel rhel8-x86_64 -------------------------------------------
intel@2021.3.0

-- oneapi rhel8-x86_64 ------------------------------------------
oneapi@2021.3.0

Before finding out about exawind-manager (learned about it in an email from Mike Sprague), I have tried all the steps to build Nalu-Wind with spack from here: https://nalu-wind.readthedocs.io/en/latest/source/user/build_spack.html

Since my machine is not in the list of machines of "build-test/configs/setup-spack.sh" the script does nothing so I would be just using the spack settings that come with the spack core for Nalu-Wind. I have tried to develop my specs following the examples given for mac and Eagle but have not succeeded.

Pleae let me know if I should post this issue with Nalu-Wind instead.

**Comment by jrood-nrel** [comment]
Hello. To use exawind-manager, you would copy a configuration from https://github.com/Exawind/exawind-manager/tree/main/configs for your machine and then create a way for exawind-manager to find the machine and then you could do something like this to build it:
```
git clone --recursive https://github.com/Exawind/exawind-manager.git && cd exawind-manager && source shortcut.sh && mkdir environments && cd environments && mkdir myenv && cd myenv && quick-create-dev -s exawind@master nalu-wind@master amr-wind@main && spack concretize -f && spack env depfile -o Makefile && nice make -j32
```

**Comment by mstoell** [comment]
Hi,

Thanks for your quick response! I'm sorry, I did not make my question very clear. If my goal is to eventually use the full ExaWind capabilities (blade-resolved wind turbine simulations with FSI), I will need to have AMR-Wind, Nalu-Wind, and  the ExaWind-Driver. Should building all three projects be accomplished with the exawind-manager (as the name kind of implies)? Or should one proceed individually e.g.
1) Build AMR-Wind using the exawind-manager (that worked on my system)
2) Build Nalu-Wind following the instructions https://nalu-wind.readthedocs.io/en/latest/source/user/build_spack.html (this failed on my system) 
3) Build the exawind-driver (I could not find instructions for that).

**Comment by jrood-nrel** [comment]
They're all in exawind-manager and Spack and this is how we build any Exawind application. It is not feasible to build these applications manually (except maybe AMR-Wind). Exawind-manager makes it easier than just using Spack through curation of machine configurations and shortcuts for dealing with Spack environments, and Spack offers multiple dimensions of parallelism to speed up building the entire stack. Building `exawind` by itself will build `amr-wind` and `nalu-wind` since they are dependencies. You can also build any of them by themselves using Spack or exawind-manager. The most difficult thing about Spack and exawind-manager in my opinion is getting the machine configured well. The command provided previously will build everything.

**Comment by mstoell** [comment]
Hi John,
I have tried to build using GCC 8.5.0 and OneAPI 2024.2.1 however the build always fails with trilinos 15.1.1 (see attached file for output when compiling with OneAPI). Would you happen to have any suggestions to get past this issue?
[build-outp.txt](https://github.com/user-attachments/files/17511744/build-outp.txt)

**Comment by jrood-nrel** [comment]
You need a newer GCC. Unfortunately Trilinos uses `std::filesystem`.

**Comment by mstoell** [comment]
I compiled with OneAPI 2024.2.1  (most recent)

**Comment by jrood-nrel** [comment]
Intel compilers, including OneAPI continue to require GCC, likely because it's still using GCC std libraries. The error you show means the compiler (or libraries) are too old to support `std::filesystem`. We use GCC 12 when using OneAPI.

**Comment by mstoell** [comment]
Got it, thanks!

**Comment by jrood-nrel** [comment]
To use a newer GCC underneath OneAPI, you merely need it in your PATH.

**Comment by mstoell** [comment]
I updated GCC via gcc-toolset-12 and now I could build on my RHEL 8 system. Thank's for your help!

**Comment by jrood-nrel** [comment]
Excellent.
