### ISSUE TITLE
FOWT simulations in Nalu-Wind

### ISSUE THREAD

**Issue by delloiacono** [Exawind/nalu-wind#1326]
Hi,

what are the capabilities of Nalu-Wind (also coupled with OpenFAST) for simulation of floating offshore wind turbines? Is there anything already developed or ongoing?

Thanks in advance.

**Comment by michaelasprague** [comment]
@delloiacono -- thanks for the question.  Floating offshore wind is a work in progress.  We have two-phase flow capabilities in both AMR-Wind and Nalu-Wind and we have done preliminary validation of wave loading on a fixed body.  Now through 2025, we will be doing verification and validation simulations of fixed and floating bodies where the near-body fluid is simulated with Nalu-Wind and the off-body fluid will be solved with AMR-Wind.   We are also implementing a 6-DOF rigid-body solver in OpenTurbine, which will be coupled to Nalu-Wind.
