### ISSUE TITLE
GCL mods (#160) introduces diffs in movingCylinder regression test

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#164]
Recent merge of #160 introduced a diff (`4.334477e-04`) for the `movingCylinder` test. With the change in formulation I would expect it to diff, but I am unsure of the magnitude of the diffs introduced. Hoping @ashesh2512 can confirm whether this requires further investigation before re-blessing the gold norm files. 

Cc: @jrood-nrel

**Comment by rcknaus** [comment]
I think it would be nice to have a simple freestream preservation test (constant velocity flow with some non-solenoidal mesh motion) added too.  On paper the old source-term style should have freestream preservation for backward Euler.

**Comment by ashesh2512** [comment]
[Uploading DISCRETE FORM OF THE GCL FOR MOVING MESHES AND ITS IMPLEMENTATION IN CFD SCHEMES - Zhang.pdf…]()

**Comment by rcknaus** [comment]
Yeah, the pulsating sphere test sounds like a good test to add to the suite if it's not too big.  The freestream preservation test you described is a good alternative if that test is too large.  

The volume/face velocity approach would definitely be a lot more cumbersome, but it's probably not too bad cost-wise.  We already break every low-order topology up into tets for the purpose of computing volumes and areas.  Anyway, the results are looking good as is.

**Comment by ashesh2512** [comment]
Holding on closing out to make sure the tests pass overnight before I finally close it.
