### ISSUE TITLE
Memory leak in HigherorderQuad2DSCS::set_boundary_info()

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#207]
Looks like #206 introduced a memory leak [reported by Clang](https://my.cdash.org/testDetails.php?test=46913868&build=1642835)

**Comment by jrood-nrel** [comment]
`Address 0x61f000003f88 is a wild pointer.` Careful now.

**Comment by psakievich** [comment]
@jrood-nrel I'll grab my code lasso, and spurs before I head after it.

**Comment by psakievich** [comment]
Addressing with PR #210

**Comment by jrood-nrel** [comment]
The victorious gaucho rides off into the sunset.
