### ISSUE TITLE
Too many fields warning message

### ISSUE THREAD

**Issue by jamelvin** [Exawind/nalu-wind#230]
In a case I am running in a development branch of mine, the following warning message

https://github.com/Exawind/nalu-wind/blob/b7f6a9756ababa5fd0a59d8de1f66d6d879c1196/include/MultiDimViews.h#L54

prints out an excessive number of times.  I can disable the warning, but @sayerhs wanted me to bring this up here to figure out the proper way to address this situation for NGP.

**Comment by alanw0** [comment]
@jamelvin Can you show the message it is printing? I'm curious about how many fields you have. We have a hard-coded stack-array in there which assumes you won't have more than 64 fields. If we need to raise that constant we can. I didn't think nalu-wind had that many fields.

**Comment by jamelvin** [comment]
`Too many fields (66), current limit in internal arrays is 64.  Code will crash...`

**Comment by alanw0** [comment]
ok. For now, in your development branch, go ahead and raise the maxFieldOrdinals constant in that file. @sayerhs and I will discuss how to make this more robust with a better solution.

**Comment by jamelvin** [comment]
In the development branch I am working on, I am using a bunch of additional fields

https://github.com/marchdf/nalu-wind/tree/TAMS-Hybrid

is the link to the branch.
