### ISSUE TITLE
Consolidated Elem + modified timestep algorithm broken since #227

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#233]
#227 introduced GPU friendly `sumInto` logic for the linear system and removed the call to [apply_coeff](https://github.com/Exawind/nalu-wind/blob/master/src/SolverAlgorithm.C#L151) in [AssembleElemSolverAlgorithm::execute](https://github.com/Exawind/nalu-wind/blob/master/src/AssembleElemSolverAlgorithm.C#L127). Now the momentum diagonal is no longer populated into the field as a _side effect_ of `apply_coeff` 

Related issue: we have no regression test to catch this behavior.

**Comment by alanw0** [comment]
oh, oops, I remember noticing that side-effect when I was working on the coeff-applier, and forgot about it before I finished. I'll take care of that.

**Comment by sayerhs** [comment]
@alanw0 A stopgap would be to revert 

https://github.com/Exawind/nalu-wind/blob/master/src/AssembleElemSolverAlgorithm.C#L127 

back to `apply_coeff` when executing on HostSpace.

**Comment by alanw0** [comment]
@sayerhs yes that would be fine. Do you want to go ahead and do that? I'm out of the office today, so I won't get to this until tonight or tomorrow.

**Comment by sayerhs** [comment]
@alanw0 I've reverted back to `apply_coeff` on host. I will leave this issue open until we have a proper fix to this issue, and a regression test to catch such issues in future.

**Comment by sayerhs** [comment]
Fixed in #438
