### ISSUE TITLE
Catalyst Tests Failing

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#256]
The 3 tests for Catalyst will fail until the Trilinos IOSS Catalyst Adapter is updated for Python 3 since I recently switched to Python 3. I have an issue for it here: https://github.com/trilinos/Trilinos/issues/5386

**Comment by jrood-nrel** [comment]
An update on this. It looks like they have replied to my issue and have agreed to get the IOSS adapter to work with Python 3.

**Comment by psakievich** [comment]
Let's close this issue since we have stopped testing with catalyst. I think getting it going again will require a new issue.
