### ISSUE TITLE
UnitTest2 Failures

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#257]
It seems like `UnitTest2` fails ever since we randomized the order of the unit tests in Google Test?

**Comment by alanw0** [comment]
@jrood-nrel I'll look into this. I saw the failure in one of my test runs, and it may be related to stk-mesh, probably something not being deleted from one test to another.

**Comment by jrood-nrel** [comment]
Solved with #263 thanks to @alanw0
