### ISSUE TITLE
nightly build configuration error

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#273]
@sayerhs @jrood-nrel 
I am looking at the dashboard and I see that all the builds on `rhodes.hpc.nrel.gov` and `mac.hpc.nrel.gov`.
Looking at the command line reported I see the following: `-DTrilinos_DIR:PATH= ` which is likely the source of the error.

**Comment by jrood-nrel** [comment]
If you look at the notes for the build, it appears Trilinos is failing to build due to this error:
```
stk_ngp_test/ngp_test.hpp: No such file or directory
```

**Comment by lucbv** [comment]
@jrood-nrel, sorry, I can only see the dashboard [here](https://my.cdash.org/index.php?project=Nalu-Wind) and this is what is displayed on it:
```
CMake Error at CMakeLists.txt:42 (find_package):
  By not providing "FindTrilinos.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Trilinos",
  but CMake did not find one.

  Could not find a package configuration file provided by "Trilinos" with any
  of the following names:

    TrilinosConfig.cmake
    trilinos-config.cmake

  Add the installation prefix of "Trilinos" to CMAKE_PREFIX_PATH or set
  "Trilinos_DIR" to a directory containing one of the above files.  If
  "Trilinos" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/projects/ecp/exawind/nalu-wind-testing/nalu-wind/build/CMakeFiles/CMakeOutput.log".
```

Is there another place where the build/configure errors can be looked at?

**Comment by alanw0** [comment]
@jrood-nrel The error about stk_ngp_test/ngp_test.hpp can possibly be due to the trilinos cmake command missing the option '-DTrilinos_ENABLE_STK_NGP_TEST:BOOL=ON'. Or better, would be to use this: '-DTrilinos_ENABLE_STK:BOOL=ON'.

**Comment by alanw0** [comment]
Do the dashboard builds use exawind-builder these days? If not, it may be a spack configuration that needs to be updated somewhere.

**Comment by sayerhs** [comment]
@alanw0 Jon's build system doesn't use `exawind-builder`, the trilinos build is entirely done within spack

**Comment by jrood-nrel** [comment]
Ok I will fix this. I put together a PR in Spack to use `-DTrilinos_ENABLE_STK:BOOL=ON` but I haven't submitted it yet because I also wanted to check whether or not I can also use `-DTrilinos_ENABLE_SEACAS:BOOL=ON` rather than all the specific Seacas options I have been setting in the past.

**Comment by jrood-nrel** [comment]
I made the pull request to Spack https://github.com/spack/spack/pull/11917 . I will change this locally for testing in the meantime though.

**Comment by jrood-nrel** [comment]
@lucbv You can read the notes attached to each build line that will show the output from the entire testing process and you can see how Trilinos fails building. The icon looks like a document.

I am going to close this as I switched to using `-DTrilinos_ENABLE_STK:BOOL=ON` and that seems to have solved it.
