### ISSUE TITLE
KokkosInterface `set_zero` function

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#289]
@alanw0 I noticed that the `set_zero` function in `KokkosInterface.h` is outside the `nalu` namespace and in `sierra` namespace. Wanted to check if this wasn't just a typo but intentional before I changed it. 

https://github.com/Exawind/nalu-wind/blob/718131130dc75e4da66fd64999b2ad3c07586237/include/KokkosInterface.h#L136-L151

**Comment by alanw0** [comment]
@sayerhs No reason for it to be outside the nalu namespace, that was a mistake.

**Comment by sayerhs** [comment]
Fixed in #298
