### ISSUE TITLE
Tasks towards ABL precursor demonstration on GPU

### ISSUE THREAD

**Issue by alanw0** [Exawind/nalu-wind#296]
1. loadComplete : unit-test to try it on device
2. field updates such as mdot, nodal gradient fields
3. start ScalarOpenEdge kernel conversion

**Comment by sayerhs** [comment]
Outstanding `LinearSystem` issues listed in #301

**Comment by sayerhs** [comment]
Field updates tracked in #336. Closing this issue in favor of the dedicated issues.
