### ISSUE TITLE
Unittest2 failing on Linux with Clang

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#30]
@rcknaus For some reason `PromoteElementQuadTest` is not within tolerance on Linux Clang (LLVM 6.0.0), https://my.cdash.org/testDetails.php?test=41139913&build=1492172 . Do you know why this would be happening or something we might be able to do about it?

**Comment by rcknaus** [comment]
I'm not able to reproduce this with my local clang 6 build, so I'm not sure what's happening.

**Comment by jrood-nrel** [comment]
I'm going to close this as I have not seen this behavior in a long time.
