### ISSUE TITLE
Merge nalu-wind-utils

### ISSUE THREAD

**Issue by tonyinme** [Exawind/nalu-wind#31]
Here is an idea that I believe would improve significantly the user experience for nalu.

Is it possible to merge nalu-wind-utils to this repository?
https://github.com/Exawind/wind-utils
It would be great to have these utilities in the main repository and for it to be a part of the compilation process.
The idea is that the users only have to compile once, and all the tools for running a case would be available.
Let me know what you think.

@sayerhs

**Comment by sayerhs** [comment]
Being handled in https://github.com/Exawind/nalu-wind/pull/36
