### ISSUE TITLE
Add unit test for #334

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#343]
#334 introduces new methods to `Edge2DSCS` and `Edge32DSCS` that don't have unit test coverage. Add the necessary unit tests.

**Comment by sayerhs** [comment]
Also according to [CDash](https://my.cdash.org/viewBuildError.php?type=1&buildid=1700065) seems like there are some out of bounds access?

**Comment by overfelt** [comment]
Yes, a fortran->C error. I'll fix it.

**Comment by sayerhs** [comment]
Done in #422
