### ISSUE TITLE
Symmetry BC leaking for fixed wing simulation

### ISSUE THREAD

**Issue by marchdf** [Exawind/nalu-wind#412]
I am seeing leakiness that eventually leads to a simulation crash for symmetry BC in the McAlister runs when using the new sym BC capabilities. Here is a screenshot and I am also attaching the input file [mcalister.txt](https://github.com/Exawind/nalu-wind/files/3740340/mcalister.txt). I can point to where the mesh is on Eagle (or any other system). 

![Screen Shot 2019-10-17 at 09 50 12](https://user-images.githubusercontent.com/15038415/67028839-477d5680-f0c9-11e9-9b35-8afeb66ca47d.png)

**Comment by psakievich** [comment]
Taking a look. Have you tried with projections turned on as well?

**Comment by marchdf** [comment]
Looks like this was an improper mesh configuration at the BC. Closing this as resolved.
