### ISSUE TITLE
Errors with OpenFAST test

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#44]
I have posted more detail about this here https://github.com/OpenFAST/openfast/issues/187 . This issue will just be used to track the status of this problem since it affects Nalu-Wind.

**Comment by psakievich** [comment]
Any idea what the last commit was where this issue wasn't broken?  I'd like to revert locally for some testing.

**Comment by jrood-nrel** [comment]
@psakievich The OpenFAST issue has the exact commits that are causing this.

**Comment by psakievich** [comment]
Okay thanks!
