### ISSUE TITLE
GPU nightly testing

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#450]
@sayerhs @jhux2 @alanw0 
I have been looking at the dashborad and noticed that we only have two tests in the GPU build on Eagle. 
While that made sense since we had not fixed issues regarding `ablNeutralEdge` until recently, I think we now add a new that runs on multiple GPUs to avoid regression in the future.

Any thoughts?

**Comment by sayerhs** [comment]
We already have `ablNeutralEdge` being tested for 1 GPU. I think @jrood-nrel can update it to test on two GPUs (max available per node).

**Comment by lucbv** [comment]
I see that @jrood-nrel has update the nightly test to include ablNeutralEdge on Eagle with 2 GPUs so I am closing this.
