### ISSUE TITLE
Failing tests - 2019 Nov 26

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#453]
[Six regression tests](https://my.cdash.org/viewTest.php?buildid=1735161&onlyfailed) have been failing since Nov 26. This appears to be caused by changes introduced in Trilinos on Nov 25, as the only commit introduced between Nov 25 (all passing) and Nov 26 (failing) is change in printout of the headers (#452). 

@jhux2 @lucbv @srajama1 I see that there were some commits to ifpack2 and zoltan on Nov 25. Are these changes significant enough for us to see the kind of changes in linear solver outputs? Or is there something deeper going on that we should look into?

**Comment by sayerhs** [comment]
Related Trilinos issue https://github.com/trilinos/Trilinos/issues/6358

**Comment by lucbv** [comment]
@sayerhs after work in trilinos this does not seem to be an issue anymore, should we close this?
