### ISSUE TITLE
MasterElement code deprecation – remove non-NGP HO elements

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#459]
@rcknaus has an alternate pathway for higher-order (HO) elements within Nalu-Wind. This issue will track the progress of the removal of the older design of HO elements (non matrix-free).

**Comment by rcknaus** [comment]
Hi,  I'll work on this.  There's a decent chunk associated with the HO master elements that can be deleted too, e.g. ElementCondenser.C
