### ISSUE TITLE
Adding test using MueLu for oversetRotCylinder

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#460]
@sayerhs @jhux2 
In order to harden capabilities of the Trilinos stack I would like to run/fix the `oversetRotCylinder` so that it can be added to the nightly tests using the trilinos stack.
The goal is to prepare the Trilinos stack to run on the McAlister test case.

**Comment by lucbv** [comment]
I see that I can create a milestone on github, could be handy...

**Comment by lucbv** [comment]
@sayerhs 
I have performed a local build with Tigoa enabled and I was able to run `oversetRotCylinder` using the following input file: [oversetRotCylinder_muelu.i.txt](https://github.com/Exawind/nalu-wind/files/3941944/oversetRotCylinder_muelu.i.txt)
As you can see the continuity solve is performed using MueLu, here are the non-linear norms that come out of this run: [oversetRotCylinder.norm.txt](https://github.com/Exawind/nalu-wind/files/3941946/oversetRotCylinder.norm.txt)
When I compare the norms I get to the gold norms, I see some differences but I don't know if I should expect one to one equivalence since I use a different linear solver.
Do you have any thoughts?

**Comment by sayerhs** [comment]
@lucbv Thanks. Can you upload the full log file please? I would expect some differences in the norms because of different solver settings, but looking at the rest of the log file will be useful.

**Comment by lucbv** [comment]
Of course here is the full log file: [oversetRotCylinder.log](https://github.com/Exawind/nalu-wind/files/3941989/oversetRotCylinder.log)
It is a bit more verbose than the usual output since I turn on the muelu and belos output to see how the linear solver is converging

**Comment by lucbv** [comment]
@sayerhs any opinion on the output?
I would like to investigate the singletons reported by MueLu, otherwise we might need a harder test case to stress MueLu some more.

**Comment by sayerhs** [comment]
@lucbv The linear/non-linear residual outputs look good to me.

**Comment by lucbv** [comment]
Alright so I have two questions:

1. Then should we try to promote a Trilinos version of the test?
That would only require to add an input deck and modify the `CTestList.cmake` a bit.

2. Do we have another test that uses overset capabilities?
I see that we are already running `oversetSphereTIOGA` with a specific muelu input deck for aspect ratio issues.
If we do not have another test then I will start looking at McAlister on Summit.

**Comment by sayerhs** [comment]
Go ahead and submit a pull request to add a muelu version of the rotating cylinder test. You have identified the two tests in the suite that exercise TIOGA based overset holecutting.
