### ISSUE TITLE
Missing gold files for TAMS PR?

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#464]
## Detailed description of the bug 

A bunch of new regression tests are failing [today](https://my.cdash.org/index.php?project=Nalu-Wind) and I suspect this is only due to a lack of `.norm.gold` files in PR #346 @marchdf @sayerhs can you look at this?

**Comment by sayerhs** [comment]
Yes we are aware of it. The gold files need to be reblessed.

**Comment by jrood-nrel** [comment]
I added the gold files for these generated from the test machine.
