### ISSUE TITLE
LinSys::GlobalOrdinal typedef 

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#475]
Tpetra recently deprecated the option to enable multiple global ordinal types, and as of this week it is an error to have multiple types turned on. Since Tpetra by default turns on `LONG_LONG`, and Nalu currently has 

https://github.com/Exawind/nalu-wind/blob/c04b5bc4ee337dfe17e0a53d2ed618423f2dfb96/include/LinearSolverTypes.h#L66-L68

the user must explicitly turn off `LONG_LONG` or end up with Configure errors. It would be good for Nalu-Wind to switch to Tpetra's default for GlobalOrdinal.  Is there a compelling reason for Nalu to stick to `long` or can we replace that typedef to use Tpetra default?

```
-- Tpetra: Tpetra_INST_INT_LONG_LONG is enabled by default.
-- Tpetra: Tpetra_INST_INT_UNSIGNED is disabled by default.
-- Tpetra: Tpetra_INST_INT_UNSIGNED_LONG is disabled by default.
-- Tpetra: Tpetra_INST_INT_INT is enabled by default.
-- Tpetra: Tpetra_INST_INT_LONG_LONG is disabled because Tpetra_INST_INT_LONG wa
s enabled by user option.
-- Tpetra: Tpetra_INST_INT_LONG is enabled.
--
-- Tpetra: Validate global ordinal setting ...
CMake Warning at packages/tpetra/CMakeLists.txt:1193 (MESSAGE):
  Tpetra requires only one global ordinal, but more than one are set:
  {int;long}.  Building with more than one global ordinal type in Tpetra is
  deprecated.
```

**Comment by alanw0** [comment]
ok, I think it should be easy to obtain the type from a tpetra macro/typedef.
I'll look into how to do this.

**Comment by lucbv** [comment]
@sayerhs would it make sense to actually use the same types as Tpetra instead of redefning these types in Nalu? That you would not have to worry about compile Trilinos in a certain way for a Nalu to work correctly.
It seems that @alanw0 is looking into a similar idea?

**Comment by alanw0** [comment]
@lucbv yes that's what I meant and didn't say clearly. If you already know how to do this or have a change in progress to do it, please go ahead.

**Comment by lucbv** [comment]
@alanw0 sure I'll take care of this and have a PR soon

**Comment by sayerhs** [comment]
@lucbv Thanks for taking this on. What you said in your post was exactly what I was trying to say in my original post when I said _It would be good for Nalu-Wind to switch to Tpetra's default for GlobalOrdinal._.

**Comment by aprokop** [comment]
There is an ongoing issue that with that change, the spack's Trilinos package has to also be updated, as currently it enables both `long` and `long long`.

**Comment by sayerhs** [comment]
@aprokop That is very likely because @jrood-nrel created the spack Trilinos package :)
