### ISSUE TITLE
Memory errors in nightly tests from #470

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#479]
#470 introduced SIGSEGV errors in [nightly tests](https://my.cdash.org/testDetails.php?test=52668260&build=1747633). 

@lawrenceccheung: Were regression tests passing on your machine when you submitted the pull request?

**Comment by lawrenceccheung** [comment]
@sayerhs Thanks for bringing this to my attention, I can also replicate the problem in that regression test.  

I think I know what the issue is: the SyntheticLidar module is making a call to the dataprobes and will also need to be updated.  I'll provide a fix to this shortly.

Lawrence
