### ISSUE TITLE
Directory creation logic in `DataProbePostProcessing`

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#484]
The current logic for directory creation in https://github.com/Exawind/nalu-wind/blob/db7f81549c54c9caedcf30b0b6698b0ef4de7370/src/DataProbePostProcessing.C#L915-L920 always expects the user to pass a filename with parent directory. If the user requests a file to be created in the current working directory, it creates a directory with the filename instead and so there is no output. The check for `/` might return `string::npos` and the code doesn't check for that. Since we are already using `boost::filesystem` in the code, using `parent_path()` might be a better solution.

**Comment by sayerhs** [comment]
Cc: @lawrenceccheung

**Comment by lawrenceccheung** [comment]
@sayerhs Yes, that's right.  The current code assumes that `fileName` is of the form `"./filenameprefix"` if it is to be put in the working directory.  As you mentioned, it should be a relatively easy fix with `parent_path()` or possibly some other calls from `boost::filesystem`.  Let me make some modifications to that section.

**Comment by sayerhs** [comment]
@lawrenceccheung @tonyinme also observed that the Exodus output isn't working correctly. Please take a look at that also when you update the code.

**Comment by lawrenceccheung** [comment]
Sure.  @tonyinme, what do you see in the Exodus output?   I didn't make any changes to the exodus output code (so sample planes should be output as sample points in the exo file), but I can take a look at anything wrong.

**Comment by tonyinme** [comment]
hey @lawrenceccheung, I was getting empty exodus files when I tried it.
Were you able to try the code with the exodus file format?
The text format works fine, but not the exodus format.

**Comment by lawrenceccheung** [comment]
Hi @tonyinme, when I tried the exodus file format, the output files were written correctly and I didn't see any empty ones.  I tried it for both exodus+text and exodus only options, but haven't yet tried various filename combinations.  What did your input file look like?

**Comment by tonyinme** [comment]
Hey @lawrenceccheung, here is the input I am using.
`
    data_probes:
      output_frequency: 1
      #output_frequency: 100
      #output_format: text
      output_format: exodus
      search_method: stk_kdtree
      search_tolerance: 1.0e-5
      specifications:
        - name: planes
          from_target_part: fluid

#          line_of_site_specifications:
#            - name: probes/probe_profile
#              number_of_points: 100
#              tip_coordinates: [0, 0.0, 10.0]
#              tail_coordinates: [0.0, 2.0, 10.0]

          plane_specifications:
            - name: planes/sample_plane
              corner_coordinates:  [0.0, -8.0, 4.2]
              edge1_vector:    [0.0, 16.0, 0]
              edge2_vector:    [0, 0.0, 16.0]
              edge1_numPoints: 100
              edge2_numPoints: 100
              #offset_vector:   [1, 0, 0]
              #offset_spacings: [10, 20]
          output_variables:
            - field_name: velocity
              field_size: 3
`

**Comment by lawrenceccheung** [comment]
Hi @tonyinme, I tried out that set of inputs, and the exo files also seemed to be generated correctly.  Let me message you separately on Slack or via email, I'm curious if you can try running a case or two for me to see what's going on.

Lawrence

**Comment by lawrenceccheung** [comment]
Hi @sayerhs, @tonyinme, I just put in a pull request [485](https://github.com/Exawind/nalu-wind/pull/485) to take of the directory creation logic.  

Regarding exodus file creation, the code looks like it is writing the file correctly, except that the exodus format for point probe data is not immediately usable in paraview (but the data is there).  There will need to be some larger changes to the exodus io routines, but there also might need to be a discussion of how people intend to use the exodus format for probe and plane data.

**Comment by sayerhs** [comment]
Fix implemented in #485
