### ISSUE TITLE
Adding airfoil test using MueLu

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#492]
@sayerhs @jhux2 
Setting up airfoilRANSEdge/airfoilRANSElem tests using Trilinos to allow easier testing of inflow/outflow and Dirichlet boundary conditions on Summit once Kokkos refactor is completed.
This also would show which input deck/xml should be used for high aspect ratio elements with MueLu.

**Comment by sayerhs** [comment]
That would be great, but please don't change the `airfoilRANSEdge` to `airfoilRANSEdgeHypre`, I'm too used to `ctest -R airfoilRANSEdge` 😉

**Comment by lucbv** [comment]
Yep, I already started with `airfoilRANSEdge_trilinos` but it might make more sense to name it `airfoilRANSEdgeTrilinos`...
