### ISSUE TITLE
TpetraLinearSystem creation fails on Summit

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#497]
## Detailed description of the bug 

All unit-tests are failing on summit with the following error:
```
1: terminate called after throwing an instance of 'std::logic_error'
1:   what():  Requirement( colGid != 0 && colGid != std::numeric_limits<LinSys::GlobalOrdinal>::max() ) FAILED
1: Error occured at: nalu-wind/src/TpetraLinearSystemHelpers.C:290
1: Error:  insert_communicated_col_indices
```
I have hacked CMakeFiles.txt to allow `ctest -V -R` to run correctly on summit...

### Details to reproduce bug/build error

1. SHA ID of the Nalu-Wind: `c678ef0587d33bed781a22b98f06bf0241b641d8`
1. Configure command [configure_nalu_host.sh.txt](https://github.com/Exawind/nalu-wind/files/4093005/configure_nalu_host.sh.txt)
1. CMake configure output [configure_nalu_host.log](https://github.com/Exawind/nalu-wind/files/4092986/configure_nalu_host.log)
1. Output of make step [make_nalu_host.log](https://github.com/Exawind/nalu-wind/files/4093033/make_nalu_host.log)
1. Details of your simulation: `ctest -V -R`
1. Stack trace of the runtime error output [summit_tests.log](https://github.com/Exawind/nalu-wind/files/4093333/summit_tests.log)

**Comment by sayerhs** [comment]
@lucbv Do you have the output of your Trilinos build? Particularly 

```
-- Tpetra: Tpetra_INST_INT_LONG_LONG is enabled by default.
-- Tpetra: Tpetra_INST_INT_UNSIGNED is disabled by default.
-- Tpetra: Tpetra_INST_INT_UNSIGNED_LONG is disabled by default.
-- Tpetra: Tpetra_INST_INT_INT is disabled by default.
-- Tpetra: Tpetra_INST_INT_LONG is disabled by default.
--
-- Tpetra: Validate global ordinal setting ...
-- Tpetra: global ordinal setting is OK
--
```

**Comment by lucbv** [comment]
Yes I kept my trilinos configuration output:
[configure_trilinos_host.log](https://github.com/Exawind/nalu-wind/files/4093365/configure_trilinos_host.log)

**Comment by lucbv** [comment]
@sayerhs I have a CUDA build that works fine and I also have a local build on my workstation that works fine but for some reason Serial on Summit is causing problems...

**Comment by psakievich** [comment]
I was seeing this error as well on Ghost, but I updated Trilinos and it seems to have abated.

**Comment by sayerhs** [comment]
@lucbv I am unable to reproduce this error on ORNL Summit with a CPU-only build

```
   Nalu-Wind GIT Commit SHA: 705c5ab6779d6cc9b9834545972cab2fe6663f4d
   Trilinos Version: 12.17-g1d68e34cd4
```

**Comment by lucbv** [comment]
@sayerhs a new trilinos was required, I'm surprised that this problem was not seen within trilinos...
