### ISSUE TITLE
StkFieldAdapter::set_all does not reset all components

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#502]
Pull request #495 removed 

```C++
stk::mesh::field_fill(0.0, *gradPhi);
``` 

and replaced it with 

```C++
ngpGradPhi.set_all(ngpMesh, 0.0);
```

However, this does not work as intended on [`StkFieldAdapter::set_all` interface](https://github.com/trilinos/Trilinos/blob/496de8209c83846169d0651de19aaa24d10a2ac6/packages/stk/stk_ngp/stk_ngp/NgpField.hpp#L104-L110). The implementation only sets the first entry of a multi-dimensional data structure per entity and does not loop over `field_scalars_per_entity`.

**Comment by alanw0** [comment]
@sayerhs I will open a bug-report ticket for the stk team and we'll get this fixed right away.
