### ISSUE TITLE
Failing test 'airfoilRANSElemTrilinos' on macOS

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#504]
`airfoilRANSElemTrilinos` is failing with a very high diff on macOS ([CDash](https://my.cdash.org/testDetails.php?test=53751805&build=1764871)). Is this expected behavior or is there something peculiar going on that must be investigated?

**Comment by lucbv** [comment]
@sayerhs unfortunately I cannot reproduce these since the only macOS machine I have access to right now is my laptop which I do not use for development so it does not have a tool-chain ready to build code.
Is there a way to get a little more output to have an idea of where things might go wrong?

**Comment by sayerhs** [comment]
@lucbv Let me turn up the verbosity and rerun the case and share the log files. Hopefully, that is useful.
