### ISSUE TITLE
Bug in BdyHeightAlgorithm

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/nalu-wind#509]
## Detailed description of the bug 

I created a mesh with deltaZ = 20/3 = 6.666666... meters, and it seems to have screwed up the ABL height algorithm.  Every third height seems to record NaNs for the statistics, like in the below  `abl_velocity_stats.dat`:

```
# Time = 0.000000
# Height, <Ux>, <Uy>, <Uz>, Ux, Uy, Uz, rho
0 4.11648 -4.11536 0 3.5365 -3.53553 0 1.164
6.667 -nan -nan -nan -nan -nan -nan -nan
13.333 4.11863 -4.11536 0 3.53834 -3.53553 0 1.164
20 4.12065 -4.11536 0 3.54008 -3.53553 0 1.164
26.667 -nan -nan -nan -nan -nan -nan -nan
33.333 4.12215 -4.11536 0 3.54136 -3.53553 0 1.164
```

I''m going through the code, and it looks like the problem is coming from `BdyHeightAlgorithm.C`.  In [`RectilinearMeshHeightAlg::calc_height_levels()`](https://github.com/Exawind/nalu-wind/blob/master/src/wind_energy/BdyHeightAlgorithm.C#L69),
```c++
  // Determine unique height levels local to this proc
  std::unordered_set<uint64_t> hLevels;
  for (auto b: bkts) {
    for (size_t in = 0; in < b->size(); in++) {
      auto node = (*b)[in];
      const double* crd = stk::mesh::field_data(*coords, node);
      const double ht = crd[iz] - hMin_;

      const int htInt = static_cast<int>(std::round(ht * heightMultiplier_));
      hLevels.insert(htInt);
    }
  }
```
It looks like the heights are cast into ints with `heightMultiplier_`.  The default value is set to 1000.0, so all of the height values are rounded to 3 decimal places.

Later on when populating the mesh index, the mesh z-coordinates are nudged upward by 1.0e-6:
```c++
  // Perturb the z-coordinate value when comparing against available height levels
  const double eps = 1.0e-6;
  // Populate indexing so that all averaging can use this index for lookup
  for (auto b: bkts) {
    for (size_t in = 0; in < b->size(); in++) {
      auto node = (*b)[in];
      const double* crd = stk::mesh::field_data(*coords, node);
      int* hIdx = stk::mesh::field_data(indexField, node);
      const double ht = crd[iz] + eps;

      auto idx = utils::find_index(heightVec, ht);
      hIdx[0] = idx.second;
    }
  }
```
and then the appropriate height index is found.  I think what is going on is that for mesh coordinates like 6.6666666..., adding epsilon makes it 6.6666676, which isn't large enough for it to be classified in the 6.667 bin by `find_index()`.  Consequently, the 6.667 bin doesn't get indexed by any mesh points, and the statistics in there don't get computed properly.

Changing `eps` to be a function of `heightMultiplier_`, like
```c++
  const double eps = 1.0/heightMultiplier_;
```
could ensure that `eps` is always large enough to bin properly.

I'm testing this out on a couple of ABL meshes to see if it works.

### Details to reproduce bug/build error

1. SHA ID of the Nalu-Wind commit you are using 
1. Configure command [attach file]
1. CMake configure output [attach file]
1. Output of make step [attach file]
1. Details of your simulation (input file, mesh description, etc.)
1. Stack trace of the runtime error output

**Comment by sayerhs** [comment]
@lawrenceccheung Did you try changing the `height_multiplier` to `1e6`? 

https://github.com/Exawind/nalu-wind/blob/6457a66312f3b36e0cb222dc26143528f44b2253/src/wind_energy/BdyHeightAlgorithm.C#L42

**Comment by lawrenceccheung** [comment]
@sayerhs Good thought.  I just tried that on my test case, and it also works.  I'll still put in a bug fix, though, so future users don't have to worry about the right value to use for their mesh.

**Comment by sayerhs** [comment]
My preferred pathway would be to change the defaults of `heightMultiplier_` to be a large value instead of tweaking `eps`. We want the _nudge value_ to be smaller than `1 / heightMultiplier_` if you want to do something like `eps = 0.01 / heightMultiplier_` that might be OK, but I would still be leery of that.

**Comment by lawrenceccheung** [comment]
@sayerhs Because of the way things are rounded, I think the minimum value for eps would have to be something like `eps = 0.5/heightMultiplier`.  (I just tried `0.01/heightMultiplier_` on my test case, and that didn't work).

Another option would be to `floor` instead of `round` in the int conversion, like:
```
  const int htInt = static_cast<int>(std::floor(ht * heightMultiplier_));
```
so that adding any epsilon value will make `find_index()` bin upwards appropriately.

However, changing the default `heightMultiplier_` to something larger like 1.0E6 would be fine too.  There's probably finite precision in the stk meshes anyway, although I don't know what that limit would be.

**Comment by lawrenceccheung** [comment]
Problem addressed in pull request [510](https://github.com/Exawind/nalu-wind/pull/510).
