### ISSUE TITLE
MueLu CMake messages

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#516]
I am seeing the following message when configuring Trilinos 

```
-- MueLu: Enabling deprecated code
-- MueLu's tutorial requires for a correct build that if Tpetra is enabled, then GlobalOrdinal=int must be enabled, and either the Serial or OpenMP Nodes in Tpetra be enabled.  Since this is not the case, I am disabling MueLu's tutorial by default.  See Trilinos GitHub Issue #1726 for details: https://github.com/trilinos/Trilinos/issues/1726
-- You chose to enable MueLu's tutorial, even though I told you that it may not build correctly.  You are responsible for whatever build or link errors may occur as a result.
```

[Trilinos CMake configure](https://github.com/sayerhs/exawind-builder/blob/e0accb09de1db55cf5541f23c077fc73a7a03148/codes/trilinos.bash#L103-L105) only has

```
            -DTrilinos_ENABLE_MueLu:BOOL=ON
            -DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON
            -DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON
```

So what should I add/remove to make this message go away. 

Trilinos SHA ID: trilinos/trilinos@1d68e34cd4b78b762fc38a0f585b9f30bdfeb6c4

**Comment by lucbv** [comment]
@sayerhs to disable deprecated code you need to add the following to your CMake configuration:
```
-D MueLu_ENABLE_DEPRECATED_CODE=OFF
```
we keep this on by default for nut-testing I think.
Regarding the tutorial message, I will have a look, I don't think you should see this since you are not requesting for the tutorial to be built.
