### ISSUE TITLE
STK drops BoostLib dependency impact on Nalu

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#518]
The latest snapshot of STK in Trilinos has removed some dependencies on Boost, it seems that the current logic in Nalu's CMake will not be sufficient to build with the new Trilinos version...
For instance the following line:
```
find_package(Boost REQUIRED QUIET COMPONENTS filesystem)
```
should also probably require `program_options` component as we are using it in Nalu.C

**Comment by sayerhs** [comment]
@lucbv This was supposed to have already addressed by @alanw0 in #513. Are you still having build issues?

**Comment by alanw0** [comment]
@lucbv You're right, that stk change did cause a link issue for nalu-wind, but like Shreyas says, #513 fixed it so if you pull nalu-wind it should resolve that.

**Comment by lucbv** [comment]
I was compiling Nalu on the Feb 3 commit,  just one commit away from @alanw0 fix : (
By the way going from
```
find_package(Boost REQUIRED QUIET COMPONENTS filesystem)
```
to
```
find_package(Boost REQUIRED QUIET COMPONENTS filesystem program_options)
```
in Nalu-Wind main CMakeFile.txt also fixes the issue without code changes,  but I guess that relying on boost a bit less is better...

**Comment by alanw0** [comment]
@lucbv your cmake fu is stronger than mine, I didn't know it was that easy to make nalu find boost. However, I do also like the idea of using boost less, especially non-header-only libs like program_options.

**Comment by DeeDiveT** [comment]
Hi @lucbv, I try your easy solution but it seems not working, do you know the reason? see https://github.com/Exawind/nalu-wind/issues/551#issuecomment-608904681 
Thanks you very much.

**Comment by lucbv** [comment]
Hi @DeeDiveT I am not sure I am the right person to help with this. Your problem is most likely not really related to a bad TPL installation. To debug this would require a lot more information on the system your are working with and the method of installation you are using.
@sayerhs is probably a better person to talk to as my installation method is the most basic one, i.e. install all the components one after each other by hand and specify the right library paths to CMake at configure time.
