### ISSUE TITLE
Actuator disk problems in clang

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#519]
The actuator disk test has been having errors with clang. Clang runs the address sanitizer, but I can't tell if it is reporting any issues due to the error or if it's just an error clang exposes.

https://my.cdash.org/testDetails.php?test=54287434&build=1774125

**Comment by psakievich** [comment]
I'm working on this.  Trying to throw a clang build together.  Doesn't look like asan based on the output though.

**Comment by psakievich** [comment]
I could not reproduce this error with clang 7.0.0.  I'm trying turning on address sanitizer but I can't seem to get past the memory leak in yaml-cpp with asan.  I've tried copying @jrood-nrel 's blacklist script from the nightly test, but it's still hanging there.  I'll look at it more tomorrow.

**Comment by psakievich** [comment]
I was able to reproduce with asan turned on.  Some entity in the map isn't tagged correctly when the actuator disk is looping over elements to spread the forces but it doesn't appear to affect the results. I'll give it a little look today, but unless I see a clear fix I'd rather just wait for the refactor which will eliminate this.

**Comment by psakievich** [comment]
I stand corrected.  Pretty bad memory leak.  Addressed in #524

**Comment by jrood-nrel** [comment]
Thanks for fixing this @psakievich ! Looks good now.
