### ISSUE TITLE
Failed running turbine_uniform_inflow & wind_farm/case3 example cases.

### ISSUE THREAD

**Issue by yoonc5536** [Exawind/nalu-wind#521]
## Detailed description of the bug 

Failed running turbine_uniform_inflow & wind_farm/case3 example cases. It is difficult to track which part of the code causes the issue.

### Details to reproduce bug/build error

1. SHA ID of the Nalu-Wind commit you are using 
d503c4e7fef16d0d7ec5ebfcb306d00e66f54e77

1. Configure command [attach file]
No errors
1. CMake configure output [attach file]
No errors
1. Output of make step [attach file]
No errors

1. Details of your simulation (input file, mesh description, etc.)
Used all inputs files as provided in the example directories.

**Console output:**

 **************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.2.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Feb  3 2020
  - Time: 15:04:12
 Execution Info:
  - Date: 02/14/2020
  - Time: 13:06:55-0500

 OpenFAST input file heading:
     FAST Certification Test #01: NREL 5.0 MW Baseline Wind Turbine (Onshore)

 Running ElastoDyn.
 Running AeroDyn.
 Running AirfoilInfo.
 Running BEM.
 Running UnsteadyAero.
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0.  BladeNode = 1, Blade = 1
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0.  BladeNode = 1, Blade = 2
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0.  BladeNode = 1, Blade = 3
 Running ServoDyn.
 Running ServoDyn Interface for Bladed Controllers.

 **************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory
 Copyright (C)  Envision Energy USA LTD

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST-v2.2.0
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
  - Date: Feb  3 2020
  - Time: 15:04:12
 Execution Info:
  - Date: 02/14/2020
  - Time: 13:06:55-0500

 OpenFAST input file heading:
     FAST Certification Test #01: NREL 5.0 MW Baseline Wind Turbine (Onshore)

 Running ElastoDyn.
 Running AeroDyn.
 Running AirfoilInfo.
 Running BEM.
 Running UnsteadyAero.
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0.  BladeNode = 1, Blade = 1
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0.  BladeNode = 1, Blade = 2
 Warning: Turning off Unsteady Aerodynamics because C_nalpha is 0.  BladeNode = 1, Blade = 3
 Running ServoDyn.
 Running ServoDyn Interface for Bladed Controllers.
Application 3377 exit codes: 139
Application 3377 exit signals: Killed

Log file of simulation: 

===============================================================================
                                  Nalu-Wind                                    
       An incompressible, turbulent computational fluid dynamics solver        
                  for wind turbine and wind farm simulations                   
===============================================================================

   Nalu-Wind Version: v1.2.0
   Nalu-Wind GIT Commit SHA: d503c4e7fef16d0d7ec5ebfcb306d00e66f54e77
   Trilinos Version: 12.17-gb42c5a1586

   TPLs: Boost, HDF5, netCDF, STK, Trilinos, yaml-cpp and zlib   
   Optional TPLs enabled: OpenFAST, Hypre, TIOGA
   Copyright 2017 National Technology & Engineering Solutions of Sandia, LLC   
   (NTESS), National Renewable Energy Laboratory, University of Texas Austin,  
    Northwest Research Associates. Under the terms of Contract DE-NA0003525    
    with NTESS, the U.S. Government retains certain rights in this software.   
                                                                               
           This software is released under the BSD 3-clause license.           
   See LICENSE file at https://github.com/exawind/nalu-wind for more details.  
-------------------------------------------------------------------------------

Actuator::load

Realm Options Review: realm_1
===========================
Element-based scheme will be activated
Warning: When using automatic_decomposition_type, one must have a serial file
Nalu will deactivate aura ghosting

Turbulence Model Review:   
===========================
Turbulence Model is: laminar 0

PPE review:   
===========================
Realm::create_mesh(): Begin
Realm::create_mesh() End

Boundary Condition Review: 
===========================
Inflow BC name:      bc_1 on west
Open BC name:        bc_2 on east
Symmetry BC name:    bc_3 on north
Symmetry BC name:    bc_4 on south
Symmetry BC name:    bc_5 on lower
Symmetry BC name:    bc_6 on upper

Initial Condition Review:  
===========================
Initial Is Type constant 
constant IC: name: ic_1 , target[0] = Unspecified-2-HEX

Material Prop Review:      
===========================
density is a constant property: 1
viscosity is a constant property: 1e-05

EqSys/options Review:      
===========================
Edge projected nodal gradient for velocity: 0
Edge projected nodal gradient for pressure: 0

Realm memory Review:       realm_1
===========================
Node count from meta data = 612977
Total memory estimate for Matrix solve (per core)= 0.061655 GB.
Total memory estimate (per core) = 0.061655 GB.

Time Integrator Review:  
=========================
StandardTimeIntegrator 
 name=              ti_1
 second order =     0
 maxTimeStepCount = 10000
 fixed time step is active   with time step: 0.125
StandardTimeIntegrator realm_name[0]= realm_1

Transfer Review:         
=========================
Realm::initialize() Begin 
Created algorithm = Alg0000_elem_HEXAHEDRON_8_geometry
Created algorithm = Alg0000_algorithm_momentum_nodal_grad
Created the following interior elem alg: MomentumEQS_AssembleElemSolverAlg_HEXAHEDRON_8
Built Kernels for momentum are `lumped_actuator', `lumped_momentum_time_derivative', `upw_advection_diffusion'.
Created algorithm = Alg0000_algorithm_continuity_nodal_grad
Created algorithm = Alg0000_algorithm_mdot_elem_interior
Created the following interior elem alg: ContinuityEQS_AssembleElemSolverAlg_HEXAHEDRON_8
Built Kernels for continuity are `advection'.
Created algorithm = Alg0001_face_QUADRILATERAL_4_geometry
Created algorithm = Alg0002_face_QUADRILATERAL_4_momentum_nodal_grad
Created algorithm = Alg0002_face_QUADRILATERAL_4_continuity_nodal_grad
Created algorithm = Alg0002_face_QUADRILATERAL_4_mdot_inflow
Created algorithm = Alg0005_face_QUADRILATERAL_4_momentum_nodal_grad
Created algorithm = Alg0005_algorithm_continuity_nodal_grad
Created algorithm = Alg0005_algorithm_mdot_open_elem
Created algorithm = Alg0008_face_QUADRILATERAL_4_momentum_nodal_grad
Created algorithm = Alg0008_face_QUADRILATERAL_4_continuity_nodal_grad
Time step ratio  dtNalu/dtFAST: 20
Realm::ioBroker_->populate_mesh() Begin
Realm::ioBroker_->populate_mesh() End
Realm::ioBroker_->populate_field_data() Begin
Realm::ioBroker_->populate_field_data() End
Realm::create_output_mesh(): Begin
Realm::create_output_mesh() End
ActuatorLineFAST alg will ghost a number of entities: 977835
EquationSystems::initialize(): Begin 
EquationSystems::initialize(): End 

Realm memory Review:       realm_1
===========================
Total memory estimate for Matrix solve (per core)= 0.061655 GB.
Total memory estimate for Fields (per core)= 0.00469933 GB.
Total memory estimate (per core) = 0.0663543 GB.
Realm::initialize() End 

*******************************************************
Simulation Shall Commence: number of processors = 60
*******************************************************
Realm shall provide output files at : currentTime/timeStepCount: 0/0 (realm_1)
*******************************************************
Time Step Count: 1 Current Time: 0.125
 dtN: 0.125 dtNm1: 0.125 gammas: 1 -1 0
 Max Courant: 0.25 Max Reynolds: 3.2e+06 (realm_1)
   Realm Nonlinear Iteration: 1/1

realm_1::advance_time_step() 
NLI    Name           Linear Iter      Linear Res     NLinear Res    Scaled NLR
---    ----           -----------      ----------     -----------    ----------

**Comment by sayerhs** [comment]
@yoonc5536 Thanks for reporting the issue we will look into this. A couple of requests: 

- Instead of pasting the contents into the github issue comment box, can you please upload the file? It will be easier for us to parse those. 

- We recently had some updates to OpenFAST that requires a change in the AeroDyn input file. While we had made some updates to the regression tests, those might not have made it to the examples folder. So if you can confirm that your build works correctly with the `nrel5MWActuatorLine` and `nrel5MWActuatorDisk` regression tests, that would be great.

**Comment by yoonc5536** [comment]
Thank you for your feedback. I will try this these regression test cases and update you.

**Comment by yoonc5536** [comment]
Quick question. Is there a way not to use OpenFAST for Nalu?

**Comment by sayerhs** [comment]
@yoonc5536 Currently, using actuator models (disk or line) requires integration with OpenFAST.

**Comment by yoonc5536** [comment]
Confirmed the regression test cases, nrel5MWActuatorLine and nrel5MWActuatorLine properly. The example cases seem to be the trouble. Thank you!
