### ISSUE TITLE
GPU build errors

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#528]
GPU testing is showing this build error: `trilinos-develop-c2jq4kismzf5j6ml7shj4cnyqju5hq4r/include/Cuda/Kokkos_Cuda_Parallel.hpp(608): error: identifier "stk::simd::Double::Double" is undefined in device code`

**Comment by sayerhs** [comment]
Trilinos/trilinos#6856

**Comment by sayerhs** [comment]
Fixed in trilinos/trilinos#6857
