### ISSUE TITLE
max Reynolds number going down in a URANS simulation

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#533]
Hi Nalu-Team,

I see an issue while running ABL-URANS case. Depending on the boundary conditions, it may or may-not show up. I see this most of the times when running a periodic test case with uniform Temperature profile. (I keep the enthalpy Solver on.)

Even though my solution starts with the max Reynolds of ~ 10^7 (which is what I should get for a cell Reynolds number), after sometime it drops to ~ 5000 or even lower.  Looked at AssembleCourantReynoldsElemAlgorithm.C, I could not see the max Reynolds number depending on something time dependent other than velocity. And in the URANS simulation I see the average velocity ~ 8m/s which I prescribed in  the initial condition. I am unsure of this inconsistent outcome. Any suggestions? Log file attached.

[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4237358/abl_simulation.log)

**Comment by sayerhs** [comment]
The default SST model in Nalu-Wind is probably not suitable for running ABL cases, so I am not sure what to expect from the run. Looking at the log file, it appears that you are running a periodic BC case, and that would mean that the mean flow would slowdown without appropriate `dp/dx` forcing. Can you share the input file to see what `abl_forcing` parameters are set to? 

What do you mean by the following?
>And in the URANS simulation I see the average velocity ~ 8m/s which I prescribed in the initial condition. I am unsure of this inconsistent outcome.

**Comment by tchatte3** [comment]
[abl_simulation.txt](https://github.com/Exawind/nalu-wind/files/4245097/abl_simulation.txt)
Hi Shreyas,

Thanks for the quick comment. I have attached the input file. Yes, I am running a periodic boundary condition, and that where we observe Reynolds number going down after a long time (after the simulation has gone past several thousand timesteps.) I do not observe this in inlet-outlet condition.

``And in the URANS simulation I see the average velocity ~ 8m/s which I prescribed in the initial condition. I am unsure of this inconsistent outcome."

I dump a netcdf file, from the boundary layer statistics block, and when I do time average of the velocity profile, it looks like the velocity profiles are still at 8 m/s (same when viewing the snapshot files in paraview). So, I am bit confused, why the average velocities are ~ 8 m/s, while the Reynolds number go down.

**Comment by sayerhs** [comment]
@tchatte3 have you looked at the `effective_viscosity_u` field? Since you are running SST, Reynolds computation uses that instead of the viscosity you specify the input file. That field could be quite off leading to a very low Re.

**Comment by tchatte3** [comment]
@sayerhs. Thanks for pointing out. No, I haven't looked into the effective_viscosity_u -- will dump it out to check. Just, a quick follow-up, Re going down would then mean that the turbulence Reynolds number is going down, right? That would mean, that the flow is not sustaining turbulence?

-Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 You mentioned that the average velocity stays around 8m/s at the forcing height. Since density is constant and the mesh is not deforming, a drop in Re would indicate that your viscosity is too high following the relation `Re = (rho * U * edge_length) / effective_viscosity`?

**Comment by tchatte3** [comment]
I see that. Might be related to setting up the tke and specific dissipation rate BC. Thanks, for clarifying !
-Tanmoy
