### ISSUE TITLE
Trouble running abl_neutral test case

### ISSUE THREAD

**Issue by rd-contr** [Exawind/nalu-wind#535]
I have installed Nalu-Wind on an SGI ICE X and am trying to run the abl_neutral test case. The simulation log file shows that it gets to "EquationSystems::initialize(): Begin" before it throws the following errors to stderr:

terminate called after throwing an instance of 'std::logic_error'
  what():  Requirement( colGid != 0 && colGid != std::numeric_limits<LinSys::GlobalOrdinal>::max() ) FAILED
Error occured at: nalu-wind/src/TpetraLinearSystemHelpers.C:291
Error:  insert_communicated_col_indices

I examined the line of code referenced in TpetraLinearSystemHelpers but quickly got lost in STK related calls.

I'm more than happy to provide build details, system details, case inputs as needed.

**Comment by sayerhs** [comment]
The error is most likely from inconsistent Ordinal types between Tpetra (Trilinos build) and Nalu-Wind 

https://github.com/Exawind/nalu-wind/blob/7985704766ebbbe26b2cc13cc57ecbdeb39c2b4a/include/LinearSolverTypes.h#L67-L69

We will need output of CMake configuration phases from Trilinos and Nalu-Wind builds (along with Git SHA IDs of the trilinos and nalu-wind versions you are using) to confirm this.

**Comment by rd-contr** [comment]
I know that I had to roll to an older version of Trilinos to get the compile to work (it would complain about global ordinals). So perhaps that’s the source of the inconsistency you reference. Is there a specific release of Trilinos that I should be attempting to use in conjunction with the current source for Nalu-Wind?

 

In the meantime, I have attached the CMakeCache.txt files for both Trilinos and Nalu-Wind. HEAD for Trilinos is lined up to SHA 98104b00c35220e7b4ed1465189040f064583e88 and HEAD for Nalu-Wind is d0809065bb26b8b531da04ed8f80a80adfda8485.

**Comment by sayerhs** [comment]
@rd-contr Trilinos/Tpetra changed their default Ordinal behavior in Dec 2019 (see #475) and newer versions of nalu-wind introduced a change to adopt the new ordinal (668bb2e04914f). This means older Trilinos with OrdinalType set to `long` won't work anymore. You can either update your trilinos and use newer [a Trilinos CMake configuration](https://github.com/sayerhs/exawind-builder/blob/9e238eaa8a42496e7704df583deda34bde568fb0/codes/trilinos.bash#L75), or you can checkout an older nalu-wind commit (56043d1bcb167 or earlier) and build that against your current Trilinos build.

**Comment by rd-contr** [comment]
Copy. I was able to roll back to nalu-wind commit 56043d1 and that allowed the abl_neutral example case to run without issue.
