### ISSUE TITLE
Memory leak during ABL simulations

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/nalu-wind#538]
## Detailed description of the bug 
I'm seeing a big memory leak when I'm running ABL cases on skybridge/chama at Sandia.  Currently I'm manually tracking memory usage using `show_job_memory_usage` (a Sandia wrapper around the [`free`](http://man7.org/linux/man-pages/man1/free.1.html) utility).  The situation is repeatable, and I see the same result (an eventual OOM) if I run different cases using same mesh/number of nodes.

This is the result for a 6M mesh run on 24 nodes/384 cores:  
![image](https://user-images.githubusercontent.com/15526007/75906087-f2817900-5dfa-11ea-8001-b34046a9aaf2.png)
Eventually the case crashes due to OOM after ~28,000 iterations.   

The memory leak isn't as bad on some larger runs, but still noticeable.  This is the result for a 95.8M mesh on 64 nodes/1024 cores, showing the min/max/avg memory usage across all nodes:
![image](https://user-images.githubusercontent.com/15526007/75906116-03ca8580-5dfb-11ea-8434-46d68aafe967.png)

I'm repeating this study with the most recent build to see if the problem still persists.  Including Phil on this conversation as well (@psakievich).

### Details to reproduce bug/build error

Nalu-Wind SHA: 2cc1d5d4a8d0ed597cd48b97adcf459eb1db4bec
Built using `intel/18.0.2.199`, `openmpi-intel/2.1`
Sample input file: [abl_DanAeroREF1_iter02_run5.yaml](https://github.com/Exawind/nalu-wind/files/4288873/abl_DanAeroREF1_iter02_run5.yaml.txt)

**Comment by sayerhs** [comment]
@lawrenceccheung I assume you are already aware of #240

**Comment by psakievich** [comment]
@sayerhs I don't think is the same issue as #240.  There is no matrix reinitialization going on, it's just straight ABL.

**Comment by sayerhs** [comment]
@psakievich I was suggesting that you should try another MPI library other than OpenMPI.

**Comment by lawrenceccheung** [comment]
@sayerhs @psakievich Is there a good non-openMPI option to try on skybridge/chama?  I see intel-mpi available, but I haven't tried using it before.

**Comment by psakievich** [comment]
@lawrenceccheung I believe that will be the best option.

**Comment by lawrenceccheung** [comment]
@psakievich @sayerhs I recompiled everything with the latest `sierra-devel` module (using `intel/19.0.3.199` and `openmpi-intel/4.0`), and that seems to solve the memory leak.

Here is another 6M mesh on 24 nodes/384 cores on skybridge, and the memory usage seems pretty stable:
![image](https://user-images.githubusercontent.com/15526007/76876661-78f07e80-682f-11ea-982b-b63ea181aa86.png)

I'm not sure what it is between openMPI/2.1 and 4.0, but I'll keep running simulations and see if notice any other differences.  My initial attempt at compiling things with `intel-mpi` also failed, but if I get that working I will also try it out.

Lawrence
