### ISSUE TITLE
Issue with URANS when buoyancy and capping inversion are ON

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#539]
Hi Nalu-Wind Team,

I notice a strange issue, when running URANS simulation with the buoyancy term. I also add a temperature capping inversion in the initial condition. 

![Velocity_Magnitude_22347_secs_snapshot](https://user-images.githubusercontent.com/14302216/76325942-4b02bb80-62be-11ea-8642-8c62c21fed04.PNG)
![Velocity_Magnitude_33511_secs_snapshot](https://user-images.githubusercontent.com/14302216/76325944-4b02bb80-62be-11ea-87ba-10317dbce0dd.PNG)
![Velocity_Magnitude_55982_secs_snapshot](https://user-images.githubusercontent.com/14302216/76325947-4b9b5200-62be-11ea-9f19-a81352b9db05.PNG)
![Velocity_Magnitude_129933_secs_snapshot](https://user-images.githubusercontent.com/14302216/76325948-4b9b5200-62be-11ea-9f55-7aa09f0e12bf.PNG)

I see that after 20K seconds (of flow time) roughly, the specific dissipation rate does not converge and the residuals are as high as 10^8. When I look at the paraview snapshots, I see that  the velocity profile does not converge at all,  and their are strange oscillations in the capping inversion layer, which eventually propagate inside the inner log layer. The temperature profile, however maintains the capping inversion trend throughout, without showing any deviations. 

I am not a URANS expert, but I think they should not take so much time to converge. When I switch off buoyancy, the specific dissipation rate (all variables, infact) converge pretty quickly.  Any comments why this could be happening? 

.yaml input file and snapshot files at different time in secs are attached for reference. 

[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4313031/abl_simulation.yaml.txt)

The log file is big, so a log-header is pasted for details related to version, SHA.

```
===============================================================================
                                  Nalu-Wind
       An incompressible, turbulent computational fluid dynamics solver
                  for wind turbine and wind farm simulations
===============================================================================

   Nalu-Wind Version: v1.2.0
   Nalu-Wind GIT Commit SHA: d503c4e7fef16d0d7ec5ebfcb306d00e66f54e77
   Trilinos Version: 12.17-gb42c5a1586

   TPLs: Boost, HDF5, netCDF, STK, Trilinos, yaml-cpp and zlib
   Optional TPLs enabled: OpenFAST, Hypre, TIOGA
   Copyright 2017 National Technology & Engineering Solutions of Sandia, LLC
   (NTESS), National Renewable Energy Laboratory, University of Texas Austin,
    Northwest Research Associates. Under the terms of Contract DE-NA0003525
    with NTESS, the U.S. Government retains certain rights in this software.

           This software is released under the BSD 3-clause license.
   See LICENSE file at https://github.com/exawind/nalu-wind for more details.
-------------------------------------------------------------------------------
```

**Comment by gantech** [comment]
I believe the k-w-SST model in Nalu-wind is not calibrated for the atmospheric boundary layer. I'm not sure about how or whether the model will perform in that scenario.

**Comment by tchatte3** [comment]
@gantech : OK, I see. Atleast, I see the oscillation is a grid phenomenon, since it is observed is very coarse LES as well.
