### ISSUE TITLE
mesh_adapt in percept module

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#540]
Hi NALU-wind team, 

Not sure, if I should be asking this question here, But since mesh_adapt is inherently tied to mesh refinement procedures in Nalu-meshes, so decided to post this.

When we first installed the Trilinos package, we did not find the mesh_adapt model in percept. We have tried reinstalling percept model, but cant seem to find the mesh_adapt executable after the build. 

Could you kindly provide a guidance/example on how to build percept or mesh_adapt in particular?

Best,
Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 [PerceptTools/percept](https://github.com/PerceptTools/percept)  is not part of the Trilinos package. You'll need to install it separately, we use [spack](https://github.com/spack/spack) to build it.

**Comment by tchatte3** [comment]
@sayerhs OK, thanks, understood.
