### ISSUE TITLE
SNL machines: yaml_cpp/0.6.2 installed

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#542]
@jrood-nrel @sayerhs @jhux2 @jvo1012 @alanw0 
the sems team has installed yaml_cpp/0.6.2 at Sandia.
I have reconfigured, built and tested Nalu-Wind with the new TPL and it works just fine.
This should allow @jrood-nrel to upgrade the CMake yaml requirement, which should allow for a cleaner CMake logic.
@jrood-nrel can you remind me what other tpls might be desirable to continue to upgrade the CMake infrastructure in Nalu-Wind?

**Comment by sayerhs** [comment]
@lucbv Thanks for the update. We are currently using `CMake 3.10.x` as our minimum version in `CMakeLists.txt`. One of the updates we wanted was to go to CMake 3.14 or newer so that we can use more modern CMake commands in the build files.

**Comment by lucbv** [comment]
@sayerhs the CMake update will be requested next, it seemed to be a larger task than updating yawl so I decided to start with the easy one... in any case, moving in the right direction : )

**Comment by psakievich** [comment]
@lucbv is this for the SRN or SEN? I've got all the TPL's cached in `/projects/wind` for CEE machines and HPC's on the SRN.

**Comment by lucbv** [comment]
@psakievich I imagine that the TPL was installed on both side.
I certainly have been using it on the SON without problems.
If you have access to a machine with sems modules through the nfs you can simply try:
```
module load sems-env
module load sems-yaml_cpp/0.6.2
```
I do not have access to SRN or HPC at Sandia so I cannot confirm myself.

**Comment by lucbv** [comment]
On the other hand I can tell @sayerhs and @jrood-nrel that we now have `sems-cmake/3.17.1` installed so if you want to look into upgrading the CMake infrastructure, I would be able to test on the Sandia side : )
