### ISSUE TITLE
Case 3 in wind farm example

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#543]
Hi NALU-wind team,

I was working with the wind farm/case 3 example (I was able to run case 1/ and case 2/ in my machines successfully), but stuck with the preprocessing in case 3.

```
nalu_preprocess:
  # Name of the input exodus database
  input_db: ../case1/restart/restart_abl.rst
  output_db: ../case1/restart/restart_abl.rst

```
The input_db with .rst framework is having some issues. The .stdout error shows the following

```
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
_pmiu_daemon(SIGCHLD): [NID 01827] [c1-1c1s8n3] [Fri Mar 13 14:41:01 2020] PE RANK 0 exit signal Aborted

Exodus Library Warning/Error: [ex_open_int]
	ERROR: failed to open ../case1/restart/restart_abl.rst of type 0 for reading. Either the file does not exist, or there is a permission or file format issue.
ERROR: Unable to open input database '../case1/restart/restart_abl.rst' of type 'exodusII'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Expr '!(Teuchos::is_null(m_database) || !m_database->ok(true))' eval'd to true, throwing.
Error occured at: stk_io/stk_io/InputFile.cpp:144
Error: ERROR: Could not open database '../case1/restart/restart_abl.rst' of type 'exodus'

_pmiu_daemon(SIGCHLD): [NID 01827] [c1-1c1s8n3] [Fri Mar 13 14:41:06 2020] PE RANK 0 exit signal Aborted

```
.exo file format in input db does not create any problem. Could somebody share if there has been a similar issue before, and if yes, what the solution might be? 

The log file is pasted below:

```

Nalu Preprocessing Utility
Input file: /hpc/scratch/ecn/de800784/NALUWIND_for_CRAY_test_Tanmoy/nalubp/examples/wind_farm/case3/case_3_preprocess.yaml
Application 55265 exit codes: 134
Application 55265 resources: utime ~0s, stime ~0s, Rss ~17220, inblocks ~10124, outblocks ~0
```

**Comment by sayerhs** [comment]
Looks like there are two errors: a YAML error and a STK error. There is not enough information to guess on the reason for `YAML::InvalidNode` error. 

Regarding the STK error, is the `restart_abl.rst` a decomposed file? if so you'll need to combine it into a single mesh file to be able to run the preprocess utility on a single MPI rank. What pre-processing tasks are you attempting to perform on the mesh/restart file?

**Comment by lawrenceccheung** [comment]
Hi Tanmoy @tchatte3, 

Just in case there's any confusion, in case 3 of that example, there's no need to run the pre-processor on the `case_3_preprocess.yaml` input file.  Once you have the boundary data collected from the case 2 run, you can jump directly to running it with `case_3_wind_farm.yaml`.  (See https://nalu-wind.readthedocs.io/en/latest/source/user/examples/WFexample.html#case-3-wind-farm-simulation)

However, that uses the same mesh as the ABL solution, so if you would like to do some mesh refinement around the turbine, you'll need to run the [nalu-wind utils](https://naluwindutils.readthedocs.io/en/latest/user/tuts/alm_refine.html#refine-using-percept) separately, or generate one in a mesher manually. 

Lawrence

**Comment by tchatte3** [comment]
@sayerhs @lawrenceccheung Thanks for the clarification. 
I was using case_3 preprocessing example to read one set of .rst file (one mesh) and output another set of .rst file (on a different sized mesh) - serving me a toy example to read, .rst files as input. 

@sayerhs I will look into the YAML::invalid node error. But, the .rst file is a decomped file (decomposed by MPI rank). Is there a way to combine the .rst files into a file readable by single MPI rank using nalu pre-processing?

**Comment by sayerhs** [comment]
Trilinos/SEACAS provides an executable called `epu` that combines the decomposed files into a single exodus file. https://gsjaardema.github.io/seacas/

**Comment by tchatte3** [comment]
@sayerhs Thank you !
