### ISSUE TITLE
Problem with running NALU-wind with non-zero Nacelle-Yaw: Failing at Elastodyn@openFAST

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#547]
Hi Nalu-wind team, 

A question regarding wind-farm simulation (its coupled to openFAST in a sense). In an ADM simulation, if my wind flow direction is not dominantly in x direction, i.e., say at angle = 250 degrees (270 degrees being from west to east wind) is the actuator disc by default orthogonal to the wind direction, or is it in-plane with y-z? I also see a value for NacelleYaw in the Elastodyn file @ OpenFAST. I was trying to change it to 250 degrees as well. But whenever that value is not zero, I get segmentation faults and the code terminates. 

A snippet of Elastodyn file shown here. 
```
---------------------- INITIAL CONDITIONS --------------------------------------
          0   OoPDefl     - Initial out-of-plane blade-tip displacement (meters)
          0   IPDefl      - Initial in-plane blade-tip deflection (meters)
       -0.5   BlPitch(1)  - Blade 1 initial pitch (degrees)
       -0.5   BlPitch(2)  - Blade 2 initial pitch (degrees)
       -0.5   BlPitch(3)  - Blade 3 initial pitch (degrees) [unused for 2 blades]
          0   TeetDefl    - Initial or fixed teeter angle (degrees) [unused for 3 blades]
        180   Azimuth     - Initial azimuth angle for blade 1 (degrees)
       11.8   RotSpeed    - Initial or fixed rotor speed (rpm)
     253.46   NacYaw      - Initial or fixed nacelle-yaw angle (degrees)
          0   TTDspFA     - Initial fore-aft tower-top displacement (meters)
          0   TTDspSS     - Initial side-to-side tower-top displacement (meters)
          0   PtfmSurge   - Initial or fixed horizontal surge translational displacement of platform (meters)
          0   PtfmSway    - Initial or fixed horizontal sway translational displacement of platform (meters)
          0   PtfmHeave   - Initial or fixed vertical heave translational displacement of platform (meters)
          0   PtfmRoll    - Initial or fixed roll tilt rotational displacement of platform (degrees)
          0   PtfmPitch   - Initial or fixed pitch tilt rotational displacement of platform (degrees)

```

[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4370405/abl_simulation.log)

[user_script.stderr.txt](https://github.com/Exawind/nalu-wind/files/4370419/user_script.stderr.txt)
[user_script.stdout.txt](https://github.com/Exawind/nalu-wind/files/4370420/user_script.stdout.txt)

The log files and the user_script std error and output files are attached as well. Expectedly the code stops at Elastodyn when the nacelle yaw is ~ 250. 

I have tested this for arbitrary numbers like NacelleYaw = 10, 20, 100, 200, etc., things work till NacelleYaw < 200. I am not sure if the Yaw angle convention for NacelleYaw in Elastodyn@openFAST is the same as the wind direction convention in NALU (e.g., 270 degrees --> west to east wind flow)

Any help?

**Comment by gantech** [comment]
@tchatte3 Are you able to run this case with BEM in OpenFAST? Whenever you are unable to run any case coupled to Nalu-wind, please try and make sure you can run the standalone OpenFAST case.

I believe you'll also have to change the neutral yaw position in OpenFAST - Servodyn to get non-zero yaw to work.

```
          5   YCMode       - Yaw control mode {0: none, 3: user-defined from routine UserYawCont, 4: user-defined from Simulink/Labview, 5: user-defined from Bladed-style DLL} (switch)
          5   TYCOn        - Time to enable active yaw control (s) [unused when YCMode=0]
          250   YawNeut      - Neutral yaw position--yaw spring force is zero at this yaw (degrees)

```

**Comment by tchatte3** [comment]
@gantech .Thanks, I will look into running openFAST in standalone, also using BEM model. A couple of observations. When I actually, switched on Servodyn and added 250 to YawNeut, the code threw me an error, suggesting that value of YawNeut can be from [-180 to 180 degrees].  After a couple of tests I see that the same range is working for NacYaw in Elastodyn solver. I guess, this solves the problem. It is a convention issue. 

However, the follow up question is in what direction is the -180 degrees defined. For example in NaluWind, 0 degrees is south, 180 degrees is  north, etc.. Could you kindly specify at what direction the 180 degrees start from.

**Comment by gantech** [comment]
Ah.. in nalu-wind I believe the wind direction uses the compass direction. So 0 would be wind blowing from the north and going clockwise from there. You can see this document to understand the coordinate system conventions in OpenFAST. Specifically Figure 3 and 5 on printed page 8 and the convention written for `NacYaw` on printed page 61 might help

https://nwtc.nrel.gov/system/files/FAST.pdf

**Comment by tchatte3** [comment]
@gantech . Perfect, thanks for pointing out. This is really helpful.!
