### ISSUE TITLE
Nalu wind direction and Nacelle Yaw

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#548]
Hi Nalu-wind team,

I am running a case with ADM, with wind blowing at 253 degrees. When do not do any-changes in Nacelle-Yaw (untouched, kept at 0 degrees),  it seems like the actuator disc plane is taken orthogonal to the dominant wind direction. However, when  I add Nacelle Yaw to 253 degrees (actually 107 degrees, the convention is -180 to + 180 counter-clockwise in nacelle-yaw coordinates), it seems like the disc-plane is actually the y-z plane. See figure below.

![image](https://user-images.githubusercontent.com/14302216/77428416-6a194700-6dae-11ea-8e25-af0c9d6af2b6.png)

So the question: are the ActuatorSearch routines automatically assigning points in the plane such that it is orthogonal to the incoming velocity vector? Any help regarding this issue?

Would that mean using NacelleYaw @openFAST for defining just the fixed yaw conditions is not required? This is an extension to the closed/solved issue #547

**Comment by psakievich** [comment]
@tchatte3 the point locations are supplied from OpenFAST.  The actuator searches in Nalu-Wind are not aware of wind direction at all.  The communication between the two codes is as follows: 

1. OpenFAST supplies point locations to Nalu-Wind
2. Nalu-Wind interpolates the velocity at these locations and gives this value back to OpenFAST
3. OpenFAST computes the forces, and new point locations which are supplied Nalu-Wind
4. Nalu-Wind spreads the forces using a Gaussian to the fluid domain and updates the point locations accordingly

There is no communication regarding dominant wind direction, yaw, etc.

Can you try this problem with the actuator line method to compare?
For the actuator disk we compute an initial location, but never update it. 
I'm not totally sure I follow your results description.  Yaw=0 seems to be behaving as Yaw=273 and vice versa? Are you setting a wind direction parameter in OpenFast? Perhaps @gantech or @tonyinme have a better idea.

**Comment by tchatte3** [comment]
@psakievich, Thank you for the points. Yes, I would have thought so too, (i.e., pts 1 - 4), but the results are a bit counter intuitive/confusing. I will try it for ALM as well. Let me also do a couple of more debugs.

Let me reorganize my question a little bit. 

Case I: Yaw = 0, seems to be fine. If I have the wind at 253 degrees (I am just setting it up through velocity vectors in the input .yaml files), so nothing is setup from Elastyodyn in openFAST regarding nacelleYaw. By default nacelleYaw = 0

Case II: I have the wind at 253 degrees (I am just setting it up through velocity vectors in the input .yaml files). I set the nacelleYaw = 90 + (270 - 253) = 107 degrees in Elastodyn, so that the wind turbine now faces the wind.

I would expect, Case II, to be more realistic, but from the picture I shared it seem that the actuator disc location is now entirely in the y-z plane.

Right now, just wanted to make sure that Case II, is the right way to setup the case, if I want the wind turbine disc to directly ``face" the wind.

**Comment by psakievich** [comment]
@tchatte3 okay sounds good.  Yes I believe you've done things correctly.  Let me know if the ALM gives you the correct orientation.  It could be that in the AD we need to run fast for 1 step and then update the point locations to get the Yaw applied. That is what I suspect, but the ALM test will confirm it.

**Comment by tchatte3** [comment]
@psakievich Thanks for the inputs. Actually, I was also worried if the mesh resolution was issue, showing me illusory results because I was running things on a super-coarse mesh. I have now run another case with a 3-layer refinement mesh, where the grid sizes are pretty finer. I tried this in ALM framework, and this is how the ALM simulation looks like.

<img width="201" alt="velocity_ALM_yawed" src="https://user-images.githubusercontent.com/14302216/77800555-6b1bd400-704d-11ea-99b8-1e0de75641af.PNG">

So, I see similar stuffs for ADM too. I am under the impression, that I am somehow not specifying the correct Nacelle Yaw angle value, somehow. The disc is getting aligned with the wind vector somehow. Fortunately, with Nacelle Yaw = 0, the disc now looks aligned in the y-z plane, which it should be ideally. I was not able to see this on a coarse grid simulation (visual artifact probably). So, I have reference point now. I will look into the coordinate transformation of the nacelle coordinates some more. I thought for a wind angle of 253.46 degrees, nacelle yaw of 90 + (270 - 253.46) = 106.54, should face the disc/act. line towards the dominant wind vector. Seems like not the case.

**Comment by DeeDiveT** [comment]
Hi @tchatte3, I didn't find how to configure yaw misalignment in example files given in this repo, do you know where to set it or related documentation? 

Millions of thanks in advance.

**Comment by tchatte3** [comment]
@ DeeDiveT, It should be in line 36 in the file NRELOffshrBsline5MW_Onshore_ElastoDyn.dat inside the directory 5MW_Baseline/ in the examples.

@psakievich I was able to fix the issue related to Nacelle Yaw. I guess, for 253.46 degrees wind, the yaw should be set up as (270-253.46) ~ 16.54 degrees. This works.

**Comment by psakievich** [comment]
@tchatte3 okay great thanks for reporting back! Feel free to close this issue unless you have more questions.
