### ISSUE TITLE
Power and Thrust data extraction

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#553]
Hi Nalu-wind team,

I have a question related to dumping Power and Thrust data output. I am running Actuator Disk model simulation in NALU-wind. How can we get the power & Thrust data output as a function of time? (essentilally a time-series data file?). Can we get it by tapping openFAST? 

Best,
Tanmoy

**Comment by DeeDiveT** [comment]
Hi, @tchatte3, execuse me, I'm trying to do some experiments with nalu-wind and yaw misalignment, and it seems we are doing something similar. But I really have no idea of correct way to install nalu-wind on the machine and then perform that kind of experiment. Could you kindly provide some "roadmap" or experience for doing that. For now, I'm confused with installation procedure among 1.compile directly following the nalu-wind doc, 2. exawind-builder (for openfast integration, also is there any other dependencies needed?), and 3. spack install nalu-wind (with some customization, such as +openfast).
I've been trapped in this procedure for two days with careful search for past issues and docs.
I would really appreciate it if you could provide some help! Thx

**Comment by tchatte3** [comment]
@ DeeDiveT, it would be helpful if you could please post a separate question in GitHub to the NALU-wind team. They might help you better with your questions.

**Comment by DeeDiveT** [comment]
> @ DeeDiveT, it would be helpful if you could please post a separate question in GitHub to the NALU-wind team. They might help you better with your questions.

Thanks for your advice! A new separate question opened here https://github.com/Exawind/nalu-wind/issues/555, hope could also help others with same conditions.

**Comment by sayerhs** [comment]
@tchatte3 For AD/AL simulations currently the turbine outputs are through OpenFAST. The [NREL 5MW input files](https://github.com/Exawind/nalu-wind/blob/8b5aedeec541765b3878c1e290540d7d5cd4a170/reg_tests/test_files/nrel5MWactuatorLine/5MW_Baseline/NRELOffshrBsline5MW_Onshore_ElastoDyn.dat#L122) in the regression test suite is a good starting point, and already includes some of the sensors you are looking for.  You'll want to read up the OpenFAST documentation to see the other sensors you can output. The OpenFAST output is a simple text file that you can process with [matlab-toolbox](https://github.com/OpenFAST/matlab-toolbox) or python (numpy and pandas).

**Comment by tchatte3** [comment]
@sayerhs  Thanks!
