### ISSUE TITLE
Dashboard failures due to PR#473

### ISSUE THREAD

**Issue by jhux2** [Exawind/nalu-wind#554]
The new failures on the dashboard are due to the merge of PR#473.  I expected all of these except for `tamsChannelEdge` and `SSTChannelEdge`.  It's possible that I didn't have the correct options enabled to run these.

1) Are the errors in those two tests acceptable?
2) What's the process for reblessing tests?

https://my.cdash.org/index.php?project=Nalu-Wind

**Comment by sayerhs** [comment]
@jrood-nrel Usually reblesses the gold files.
