### ISSUE TITLE
Questions related to perform wind turbine simulation with yaw misalignment

### ISSUE THREAD

**Issue by DeeDiveT** [Exawind/nalu-wind#555]
Hi, I'm trying to do some experiments with Nalu-wind and yaw misalignment. But I really have no idea of the correct way to install nalu-wind on the machine and then perform that kind of experiment with numerous documentations for installation. Could you please kindly provide some "roadmap" or experience for doing that? 

For now, I'm confused with the installation procedure among 
1.compile directly following the Nalu-wind documentation (with -D option cmake -DENABLE_WIND_UTILS=ON to enable wind-utils, right? and also set openfast in the config file to ON)
2. exawind-builder (for openfast integration, also is there any other dependencies needed?), 
3. spack install nalu-wind (with some customization, such as +openfast).

I've been trapped in this procedure for two days with a careful search for past issues and docs.
It would be really appreciated if anyone could provide some help. Thx! Also, thanks for this great work on renewable energy!

**Comment by sayerhs** [comment]
Directly installing with `spack` is the recommended approach to get started with nalu-wind. If you want to use wind-utils, you can either modify the spack package.py definition to add the CMake options and have it installed alongside nalu-wind. Or you can install wind-utils separately after you've installed nalu-wind via spack. You'll need three dependencies (also dependencies nalu-wind And installed by spack): trilinos, boost, yaml-cpp. 

The [exawind-builder](https://exawind-builder.readthedocs.io/en/latest/basic.html) option is only necessary if you intend to develop nalu-wind and require fine-grained control over the build/debug process. This Is not as very user-friendly as the spack approach and is sensitive to the user's she'll environment, I.e., it requires three user to have a clean bashrc and not have activated anaconda environment that mighty provide its own MPI etc. that might conflict with the spack ones. The CMake errors/warnings you were seeing are an example. Another limitation of this process is that it requires you to perform all steps through invoking appropriate commands through the script and not source the script or execute make directly at the command prompt. All output to screen is also logged in `cmake_output.log` and `make_output.log` examining those files will give you the exact build time errors. If you can share those outputs, that might give us some more clues.

**Comment by DeeDiveT** [comment]
Hi @sayerhs, I see, thx. Btw, logs have been uploaded at https://github.com/Exawind/nalu-wind/issues/551#issuecomment-609037320. Also, anyone who have similar issues can refer to that issue.
