### ISSUE TITLE
nalu_Input_fileX bug report

### ISSUE THREAD

**Issue by DeeDiveT** [Exawind/nalu-wind#556]
## Detailed description of the bug 
SyntaxError bugs introduced in 
https://github.com/Exawind/nalu-wind/commit/2cc1d5d4a8d0ed597cd48b97adcf459eb1db4bec#diff-4344ce21c64fc3d75d3a7d5119743c3b

### Details to reproduce bug/build error

```
$ ../nalu_input_fileX -s setup.yaml
  File "../nalu_input_fileX", line 813
    for line in lines]
      ^
SyntaxError: invalid syntax
```
https://github.com/Exawind/nalu-wind/blob/7f65c3b29415307020b3872835352157daff1618/examples/nalu_input_fileX#L798-L821

**Comment by sayerhs** [comment]
@DeeDiveT The python script is a convenience script to auto-generate the YAML files. As a temporary workaround, please use the files in the regression test suite [ABL neutral example](https://github.com/Exawind/nalu-wind/tree/master/reg_tests/test_files/ablNeutralEdge) and edit them manually to run your cases.
