### ISSUE TITLE
Power/ Thrust from Nalu/OpenFAST

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#572]
Hi Nalu-wind team,

What is the best way to tap power and thrust time-series from openFAST. I am running NALU-wind, ADM at the moment. I looked at the openFAST manual but could not find anything related to fixing turbine power time-series. Any help in pinpointing how to do that will be very helpful.

Best,
Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 Have you looked at the [spreadsheet in OpenFAST git repo](https://github.com/OpenFAST/openfast/blob/master/modules/openfast-library/src/OutListParameters.xlsx) that lists the sensors for outputting data? I think you are looking for `GenPwr`, `RtAeroPwr`, `RtAeroCt` etc.? OpenFAST specific questions are probably best directed to [openfast issues](https://github.com/OpenFAST/openfast/issues).

**Comment by tchatte3** [comment]
Ok, thanks @sayerhs. I will look into these parameters
