### ISSUE TITLE
velocity gradients at output

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#576]
Hi Nalu-wind team,

Is there a way to directly tap the velocity gradients of vx, vy, and vz (also Temperature) at the outputs from the .yaml file. Does it dump out the projected nodal gradients.? It will be very helpful, if someone can pin-point me the variable to use, and I can look more. 

Best Regards,
Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 You can output fields like `dudx` and `dhdx` (we solve for enthalpy and not temperature, but you can convert to temperature as we normally run constant density and specific heat).

**Comment by tchatte3** [comment]
@ sayerhs Thanks. Is dudx a scalar, vector or a tensor field?

**Comment by gdeskos** [comment]
dudx  is a tensor field

**Comment by tchatte3** [comment]
@gdeskos, Thank you

**Comment by gdeskos** [comment]
To clarify my comment dudx is a tensor which is stored as a vector that contains all different  du_i/dx_j components. You may access any of the tensor components on device by doing duidxj=dudx.get(mi, ndim * i + j).
