### ISSUE TITLE
meshing using abl_mesh tool

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#580]
Hi Nalu-wind team,

I was trying to explore other options in the abl_mesh utility.
 With the spec_type = bounding_box, I was able to use constant spacing type/ geometric spacing type. 

I am wondering if I use spec_type = vertices, what can I implement there?. Can I manually implement, the x, y, and z coordinates of the nodes through this spec_type feature = vertices? 

In a more generic sense, I am curious if I can create a hexahedral mesh structure  just by assigning node-coordinates of x, y, z in the abl_mesh feature in nalu. How to implement this in a .yaml file.?
This way a more controlled variation of mesh can be generated.

**Comment by sayerhs** [comment]
@tchatte3 `spec_type: vertices` allows you to set the 8 corner vertices like `blockMeshDict` (in OpenFOAM) does for a single block mesh. If I understood your question correctly, you are asking about controlling the grid spacing in the three directions. IF that is the case there are two ways to do this:

- Use predefined grid stretching ratio: [example](https://github.com/Exawind/wind-utils/blob/master/tests/mesh/channel_mesh.yaml)
- User-specified spacing as an array in the 3 directions: [example](https://github.com/Exawind/wind-utils/blob/master/tests/mesh/user_specified_spacing.yaml)

**Comment by sayerhs** [comment]
See here for geometric mesh spacing https://naluwindutils.readthedocs.io/en/latest/user/abl_mesh.html#mesh-spacing

**Comment by tchatte3** [comment]
@sayerhs Thanks a lot. Ok, so vertices spec_type would not be suitable. I think User-specified spacing as an array in the 3 directions was something I was looking on. This is extremely helpful. 

Yes, we are relying on third party meshing tools, but I guess the abl_mesh utility, for our purpose, is still a powerful tool to generate script based simple box meshes.
