### ISSUE TITLE
Failing unit test for ActuatorDisk+FAST

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#582]
Unit tests are failing nightly [CDash](https://my.cdash.org/testDetails.php?test=57410265&build=1823730)

**Comment by sayerhs** [comment]
Unit tests when run through CTest are run from `<build_dir>/reg_tests/test_files/unitTest{1,2}`.

**Comment by psakievich** [comment]
ah okay.  I'll take a look

**Comment by psakievich** [comment]
PR #583 opened to address this.

**Comment by sayerhs** [comment]
CDash still shows [failure](https://my.cdash.org/testDetails.php?test=57474680&build=1824678)

**Comment by psakievich** [comment]
@sayerhs @jrood-nrel pretty sure I got it right this time see #586
