### ISSUE TITLE
CUDA warnings for ActuatorNGP 

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#588]
NGP code introduced for `Actuator` generates warnings when compiled for CUDA

```
/.../nalu-wind/include/actuator/ActuatorNGP.h(63): warning: calling a __host__ function from a __host__ __device__ function is not allowed
```

More details [CDash](https://my.cdash.org/viewBuildError.php?type=1&buildid=1825358)

**Comment by psakievich** [comment]
I'll take a look
