### ISSUE TITLE
warnings in DataProbePostProcessing

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#602]
CDash builds show out of order initialization warnings in DataProbePostProcessing constructor 

[CDash](https://my.cdash.org/viewBuildError.php?type=1&buildid=1830353) link

**Comment by lawrenceccheung** [comment]
Should be fixed in PR [603](https://github.com/Exawind/nalu-wind/pull/603).  I'm able to get rid of all warnings (using `-Wall -Wreorder`) during compilation with intel -- hopefully holds true for gcc as well.

Lawrence
