### ISSUE TITLE
Symmetry BC

### ISSUE THREAD

**Issue by rcknaus** [Exawind/nalu-wind#617]
Just to track what's left with the symmetry BC

  * Need a formal verification test made up, documented
  * Adjust so it applies as a slip condition for a moving wall
  * Adapt for the edge scheme
  * (Maybe) write the non-consolidated element implementation

**Comment by psakievich** [comment]
I'm closing this for now.  We have the no-slip version in place.  We can re-open in the future if we decide to do more work on this bc.
