### ISSUE TITLE
Issue with tke bc in precursor driven wind farm simulation

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#618]
Hi Nalu-wind team,

I am currently working with precursor driven wind farm simulation, starting with the example ``wind farm" case. All my steps are functionally working now. For step 2, I restart the precursor simulation, from a fully developed state and extract the inflow boundary plane only at various time-steps. 

<img width="690" alt="image_1" src="https://user-images.githubusercontent.com/14302216/84303046-53b89700-ab24-11ea-959c-9ef07306c079.PNG">

The image above shows the boundary plane extracted and the profiles match with the fully developed state. (note this is toy problem)

I also attach a profile of the tke bc I expect to see at the boundary plane, that would go to the wind farm simulation. 
<img width="335" alt="image_2" src="https://user-images.githubusercontent.com/14302216/84303070-5adfa500-ab24-11ea-8add-6cd9560230a1.PNG">

However, when I feed all the boundary-plane profiles (velocity, tke, sdr), I see two phenomenon in the simulations. 

i) Dispersion error in the inlet region. I know this is not mesh-related as running simulation with this mesh and presribed inlet outlet alleviates this dispersion error problem. 

<img width="560" alt="image_3" src="https://user-images.githubusercontent.com/14302216/84303079-5e732c00-ab24-11ea-981b-a319d5ffbc1e.PNG">

ii) This one is more concerning. I checked the tke profile at time = 0, and it matched perfectly with the boundary plane data I have. This suggest that the Transfer modules are working as expected, (atleast at time = 0). However,the tke profile at the inlet evolves to something like this and stays constant throughout the simulation. 

<img width="678" alt="image_4" src="https://user-images.githubusercontent.com/14302216/84303088-6206b300-ab24-11ea-89a9-2057a36bdfe2.PNG">

Please note, this is only happening to the tke bc. I checked the velocity profile and the specific dissipation rate profile;  they maintain their profile which was prescribed at the boundary planes. Only the tke-bc evolves to a different profile. 

I have attached the .log and .yaml file for reference. 
[abl_simulation.log](https://github.com/Exawind/nalu-wind/files/4760481/abl_simulation.log)
[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4760487/abl_simulation.yaml.txt)

I find ii) more concerning. Any suggestions as to why this might happen? I guess is that the ``wall-modelling" for RANS  is very sensitive to the grid size at the wall, specifically for tke, and the last grid point of the inlet is over-written by the wall-modelling value. Only then I can explain such a phenomenon.

 Note, the wind farm grid and the precursor grid are not exactly the same, but I am guessing a spatial interpolation is happening in between.

**Comment by tchatte3** [comment]
@sayerhs Based on your previous suggestion, I started using the same initial condition of ABL into the precursor driven wind farm simulation. I used the grid to grid interpolation with ``Nalu Transfers`` with initialization objective as in #621 . Started seeing the same dispersion errors. While my grid to grid interpolation is working perfectly and is sanity tested, I got rid of that for further sanity tests.

I simply restarted the ABL mesh with precursor driven inflow taken from ``west" boundary plane of a fully developed ABL simulation (getting rid of interpolation uncertainties). I still get that dispersion error, even though at time=0 (IC) I do see the initial condition and the boundary condition are the same. 

This dispersion error happens even without turbine simulations. 

This is time=0 snapshot. There is no mismatch between initial and boundary conditions. 
![image](https://user-images.githubusercontent.com/14302216/86404671-05f40200-bc7e-11ea-883f-4858bc63f69d.png)

But the dispersion error starts cropping in from the next snapshot and do not go away.

![image](https://user-images.githubusercontent.com/14302216/86405204-faeda180-bc7e-11ea-9903-7dc49281f43d.png)

The final .yaml file (for the precursor driven simulations is added for reference)
[abl_simulation.yaml.txt](https://github.com/Exawind/nalu-wind/files/4866477/abl_simulation.yaml.txt)

Any suggestions/hints as to why this might happen?

Best Regards,

**Comment by sayerhs** [comment]
@tchatte3 in the transfers section can you also add another entry (for `cont_velocity_bc`) and try? 

```yaml
transfers:
- name: west
  type: geometric
  realm_pair: [ioRealm, fluidRealm]
  mesh_part_pair: [west,west]
  objective: external_data
  search_tolerance: 5.0e-6
  transfer_variables:
  - [velocity_bc, velocity]
  - [velocity_bc, velocity_bc]
  - [velocity_bc, cont_velocity_bc]
  - [turbulent_ke_bc, turbulent_ke]
  - [turbulent_ke_bc, tke_bc]
  - [specific_dissipation_rate_bc,specific_dissipation_rate]
  - [specific_dissipation_rate_bc,sdr_bc]
```

Tagging @psakievich and @rcknaus in case they have other suggestions ideas.

**Comment by tchatte3** [comment]
@sayerhs , Thank you for the suggestion. Will modify and test it out again.

**Comment by tchatte3** [comment]
@sayerhs @psakievich @rcknaus Thank you, this suggestion of transferring velocity_bc to cont_velocity_bc from ioRealm to fluidRealm works now, and I  am not seeing those standing dispersion errors in the velocity field at the inlet. I am closing this issue as it is resolved.
