### ISSUE TITLE
ablNeutralStat Python dependency

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#624]
I am wondering if it would be possible to remove the Python NetCDF package dependency for the `ablNeutralStat` test to be in line with the other tests? A regular Python dependency is no problem, but I would prefer if Python package dependencies can be avoided just so I don't have to spend the time setting them up on the three test machines.

**Comment by lawrenceccheung** [comment]
Hi @jrood-nrel, that's a good question.  I wasn't 100% sure what packages were available on the test machines when I set up the test.

An alternative to the python dependency would be to use the netcdf command line utilities (like `ncdump`), I might be able to use that to extract the same information.  Are those utilities already installed on the test machines?

Also tagging @sayerhs in this issue, he might also know of other methods of processing the netcdf file.

Lawrence

**Comment by jrood-nrel** [comment]
Yeah since netcdf is required, it should be easy to have netcdf utilities in the path for the test.

**Comment by lawrenceccheung** [comment]
Ok that works.  I'll try modifying it to use those utilities then.  Probably won't get to it until later this week or next, so you can ignore the `ablNeutralStat` test for now.

Lawrence

**Comment by sayerhs** [comment]
@jrood-nrel How difficult would it be to install [nccmp](https://gitlab.com/remikz/nccmp/-/blob/master/README.md) through spack. I see that spack has a package for it already? this would provide the ability to do `fcompare` type checks on the files, instead of some python utility that we write around `ncdump`. The `abl_statistics.nc` file is quite small and can be part of either the `mesh` repo or even the `reg_tests`.

**Comment by jrood-nrel** [comment]
`nccmp` looks simple. That would be fine.

**Comment by lawrenceccheung** [comment]
@jrood-nrel @sayerhs I made the modifications in [PR 638](https://github.com/Exawind/nalu-wind/pull/638).  Test it out and let me know if everything works properly on the test machines.

Thanks,

Lawrence
