### ISSUE TITLE
Regression test for simple fixed wing actuator pathway

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#629]
The NGP team (@alanw0, @overfelt, @jrood-nrel, and myself) have an upcoming ECP Q4 milestone to demonstrate a CPU-GPU simulation of actuator line simulations running on Summit. To achieve this, we will need to figure out that all the field syncs are working correctly on GPU builds. 

To help the NGP team (and possibly members of STK team who might to help with debugging) we would like to have two regression tests in the Nalu-Wind suite: 1. simple actuator fixed wing (without OpenFAST dependency), and 2. convert NREL-5MW actuator line case to NGP. The second test will be the basis for the demonstration simulation that we will perform for the Q4 milestone. 

TODO: @lawrenceccheung and @psakievich  can you please create a new regression test for the non-OpenFAST version of actuator line pathway? From what I can tell #577 only introduced a unit test and not a regression test. 

DONE means: A nightly regression test that exercises the simple fixed wing actuator case that runs on CPUs.

**Comment by psakievich** [comment]
@sayerhs as written the current fixed wing implementation is host only.  Is maximizing GPU execution for that section of code part of this issue, or just a nice bonus if we have time to pull it off?

**Comment by sayerhs** [comment]
@psakievich As written maximizing GPU execution is just a nice bonus if we have time to pull it off.

**Comment by lawrenceccheung** [comment]
Hi @sayerhs -- Yes, I can set up a fixed wing regression case based on some test cases I already have.

Lawrence
