### ISSUE TITLE
Newton-Raphson method in ComputeWallFrictionVelocityAlgorithm::compute_utau()

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#634]
Hi Nalu-wind team,

I am reaching out to understand better the Newton-Raphson iteration that is used to compute u_tau.

    const double wrk = std::log(A*utau);
    // evaluate F

    const double fPrime = -(1.0+wrk);

    // evaluate function
    const double f = kappa_*up- utau*wrk;

    // update variable
    const double df = f/fPrime;

    utau -= df;
    if ( std::abs(df) < tolerance_ ) {
      converged = true;
      break;

I understand the motivation is to find the root of f - kappa*up - utau*wrk, which would correspond to u+ ~ 1/kappa* ln (Ey+)
However, when I look at fPrime, I see it is calculated as fPrime = -(1+wrk). fPrime, being the derivative of the function f, wrt u_tau, so fPrime = df/du_tau = kappa*du_p/du_tau - work. From here, I could not figure out why kappa*du_p/du_tau = -1 ?  Any help/guidance regarding this matter?

Best Regards,

**Comment by sayerhs** [comment]
https://github.com/Exawind/nalu-wind/blob/180441f3ac6aab09bb6704e6953f33b1f32f5c86/src/ngp_algorithms/ABLWallFrictionVelAlg.C#L36-L44

**Comment by sayerhs** [comment]
@mchurchf Has been recently working on updating this part of the codebase, so I am assigning him to this issue. He would be the best person to answer this.

**Comment by tchatte3** [comment]
@sayerhs Thank you. I guess the algorithm I was pointing to is more relevant for RANS calculations where u+ = u_tau/kappa *log(Ey+) and any direction would be helpful.

Best Regards,
Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 do you still need help with this?

**Comment by tchatte3** [comment]
@sayerhs , I guess yes since I am trying to write my own algorithm of u_tau iteration and understanding what has been done is certainly helpful. However, it is not of high priority and I am will wait more for an answer.

**Comment by psakievich** [comment]
Closing due to lack of traffic.  If the question is still relevant then please reopen.
