### ISSUE TITLE
Compile Nalu-wind with Trilinos_STK

### ISSUE THREAD

**Issue by ShenglinYan** [Exawind/nalu-wind#645]
According to document of Nalu-wind, an error information shown the nalu-wind need the package of STKBalance of Trilinos during the compilation process. I modified the _do-config-trilinos_ script, and added the new option with -DTrilinos_ENABLE_STKBalance:BOOL=ON . I recompiled the Trilinos, and came across an error. The following is the error message.

Scanning dependencies of target stk_balance
[ 90%] Building CXX object packages/stk/stk_balance/stk_balance/CMakeFiles/stk_balance.dir/balance_main/balanceMain.cpp.o
[ 90%] Linking CXX executable stk_balance.exe
/usr/local/lib/liblapack.a(strtri.o): In function `strtri_':
strtri.f:(.text+0x218): undefined reference to `_gfortran_concat_string'
/usr/local/lib/liblapack.a(dtrtri.o): In function `dtrtri_':
dtrtri.f:(.text+0x219): undefined reference to `_gfortran_concat_string'
/usr/local/lib/liblapack.a(ctrtri.o): In function `ctrtri_':
ctrtri.f:(.text+0x25c): undefined reference to `_gfortran_concat_string'
/usr/local/lib/liblapack.a(ztrtri.o): In function `ztrtri_':
ztrtri.f:(.text+0x264): undefined reference to `_gfortran_concat_string'
/usr/local/lib/liblapack.a(xerbla.o): In function `xerbla_':
xerbla.f:(.text+0x53): undefined reference to `_gfortran_st_write'
xerbla.f:(.text+0x5e): undefined reference to `_gfortran_string_len_trim'
xerbla.f:(.text+0x73): undefined reference to `_gfortran_transfer_character_write'
xerbla.f:(.text+0x83): undefined reference to `_gfortran_transfer_integer_write'
xerbla.f:(.text+0x8b): undefined reference to `_gfortran_st_write_done'
xerbla.f:(.text+0x94): undefined reference to `_gfortran_stop_string'
collect2: error: ld returned 1 exit status
packages/stk/stk_balance/stk_balance/CMakeFiles/stk_balance.dir/build.make:155: recipe for target 'packages/stk/stk_balance/stk_balance/stk_balance.exe' failed
make[2]: *** [packages/stk/stk_balance/stk_balance/stk_balance.exe] Error 1
CMakeFiles/Makefile2:8920: recipe for target 'packages/stk/stk_balance/stk_balance/CMakeFiles/stk_balance.dir/all' failed
make[1]: *** [packages/stk/stk_balance/stk_balance/CMakeFiles/stk_balance.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

The following is cmake options of  do-config-trilinos script.
```
cmake \
-DCMAKE_INSTALL_PREFIX=$trilinos_install_dir \
-DTrilinos_ENABLE_CXX11=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTpetra_INST_DOUBLE:BOOL=ON \
-DTpetra_INST_INT_LONG:BOOL=ON \
-DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
-DTpetra_INST_COMPLEX_DOUBLE=OFF \
-DTrilinos_ENABLE_TESTS:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DTPL_ENABLE_MPI=ON \
  -DMPI_BASE_DIR:PATH=$mpi_base_dir \
-DTPL_ENABLE_SuperLU=ON \
  -DSuperLU_INCLUDE_DIRS:PATH=$superlu_inc_dir \
  -DSuperLU_LIBRARY_DIRS:PATH=$superlu_lib_dir \
-DTrilinos_ENABLE_Epetra:BOOL=OFF \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_ML:BOOL=OFF \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=OFF \
-DTrilinos_ENABLE_AztecOO:BOOL=OFF \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Ifpack:BOOL=OFF \
-DTrilinos_ENABLE_Amesos:BOOL=OFF \
-DTrilinos_ENABLE_Zoltan:BOOL=ON \
-DTrilinos_ENABLE_STKMesh:BOOL=ON \
-DTrilinos_ENABLE_STKSimd:BOOL=ON \
-DTrilinos_ENABLE_STKIO:BOOL=ON \
-DTrilinos_ENABLE_STKTransfer:BOOL=ON \
-DTrilinos_ENABLE_STKSearch:BOOL=ON \
-DTrilinos_ENABLE_STKUtil:BOOL=ON \
-DTrilinos_ENABLE_STKTopology:BOOL=ON \
-DTrilinos_ENABLE_STKBalance:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_tests:BOOL=ON \
-DTrilinos_ENABLE_STKUnit_test_utils:BOOL=ON \
-DTrilinos_ENABLE_Gtest:BOOL=ON \
-DTrilinos_ENABLE_STKClassic:BOOL=OFF \
-DTrilinos_ENABLE_SEACASExodus:BOOL=ON \
-DTrilinos_ENABLE_SEACASEpu:BOOL=ON \
-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON \
-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON \
-DTrilinos_ENABLE_SEACASIoss:BOOL=ON \
-DTPL_ENABLE_Netcdf:BOOL=ON \
 -DNetCDF_ROOT:PATH=${netcdf_install_dir} \
-DTPL_ENABLE_HDF5:BOOL=ON \
 -DHDF5_ROOT:PATH=${hdf_install_dir} \
-DHDF5_NO_SYSTEM_PATHS=ON \
-DPNetCDF_ROOT:PATH=${pnetcdf_install_dir} \
-DZlib_ROOT:PATH=${ZLIB_ROOT_DIR} \
-DTPL_ENABLE_Boost:BOOL=ON \
  -DBoost_INCLUDE_DIRS:PATH=$boost_inc_dir \
-DTrilinos_ASSERT_MISSING_PACKAGES=OFF \
```

**Comment by jrood-nrel** [comment]
@ShenglinYan I updated the example Trilinos configuration with the current configuration we are using https://nalu-wind.readthedocs.io/en/latest/source/user/build_manually.html#trilinos . Most notably we are using only `-DTrilinos_ENABLE_STK:BOOL=ON`.

**Comment by ShenglinYan** [comment]
@jrood-nrel  Thanks for your reply. The configuration of  the BLAS leads to the second error. To solve the second error, the configuration of BLAS need to be added. The option is ```
-DTPL_ENABLE_BLAS:BOOL=ON -DBLAS_LIBRARY_NAMES=blas 
-DBLAS_LIBRARY_DIRS= $blas_install_dir\lapack \
```.
