### ISSUE TITLE
Missing mesh file for new tests

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#647]
`mesh_actlinesimple.exo` needs to be added to the mesh repo and the submodule updated here.

**Comment by sayerhs** [comment]
@jrood-nrel @lawrenceccheung did commit it to meshes repo https://github.com/Exawind/meshes/commit/7b3180ce14e759c4c3745a3a84244686aab76945 I suspect we need to just update the submodule reference?

**Comment by jrood-nrel** [comment]
Ah I just read the commit message on the mesh repo and didn't realize it was there. Ok I can just update the submodule here.
