### ISSUE TITLE
variable time-step in Nalu-wind with openfast

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#653]
Hi Nalu-wind team,

Since the openfast time-integrations are fixed-time-step, I am curious about the recommendation of running ActuatorDisk/ ActuatorDiskNGP methods running with variable time-step method. While they are running fine, and prelimiary tests are not showing any discprepancies as such, I wanted to know if it is recommended and if not what are the potential pit-falls?

Best Regards,

**Comment by sayerhs** [comment]
The current implementation exchanges information with OpenFAST at the beginning of each time step. 

https://github.com/Exawind/nalu-wind/blob/52ec6a37ca62f11e006143961c6678ab8d7a45ed/src/Realm.C#L1818-L1834

OpenFAST is always going to advance the same time step, and if you do variable time-step sizes on Nalu-Wind side, your coupling is incorrect. It might run without crashing, but I am not sure how meaningful the results are.

**Comment by tchatte3** [comment]
@sayerhs OK, this makes perfect sense. Thank you for this information, very helpful.
