### ISSUE TITLE
Power curve establishment of 5MW NREL turbine with Nalu-wind+openfast

### ISSUE THREAD

**Issue by tchatte3** [Exawind/nalu-wind#659]
Hi Nalu-wind dev. team, 

When working with NREL 5MW turbine, I first validated the power curve by running stand-alone openfast at different operating conditions (with controller ON). The curve matched very well with the established Aero and Gen. power. When I am using Nalu-wind as CFD driver, I see some discrepencies. 

This velocity is a single point velocity at hub-height that openfast output channel provides. This velocity is less than the free stream velocity due to blockage/induction effect. 
![image](https://user-images.githubusercontent.com/14302216/87688564-1e235100-c755-11ea-96fa-33609f507fd9.png)

This velocity corresponds to the rotor average velocity that I postprocessed from Nalu-wind Data. 
![image](https://user-images.githubusercontent.com/14302216/87688661-41e69700-c755-11ea-9c4e-320df54aeba9.png)

This velocity corresponds to Free-stream velocity @ Nalu-wind inlet condition at hub-height
![image](https://user-images.githubusercontent.com/14302216/87688840-7ce8ca80-c755-11ea-937f-60e5253f8ebf.png)

Blue - Aeropower, Orange - Gen. power.  See the power curve best matches with rotor-averaged velocity data and worse match is with free-stream velocity data. 

Note, in nalu-wind I providing plug-flow velocity, so there is no really wind shear. I am using k-omega SST RANS model. I was under the impression that the power curve is derived from free stream velocity, but it seems it is not. Am I missing something? Could you please provide some guidance,/information as to whether the power curve for NREL 5MW was established without considering the blockage effects or not? 

Best Regards,

**Comment by sayerhs** [comment]
Questions regarding NREL-5MW power curves are best directed at Dr. Jason Jonkman.

**Comment by tchatte3** [comment]
@sayerhs , Thanks for the direction.
