### ISSUE TITLE
Errors when FFTW enabled

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#66]
@tslund Can you look at the errors that are caused when enabling FFTW? They are located at https://my.cdash.org/viewBuildError.php?buildid=1581674

**Comment by sayerhs** [comment]
Attempted to address these errors in commit d8810e2. Might have to update gold files as the original files in repository were generated on Mac OSX. They are causing diffs on Linux+GCC builds.

**Comment by jrood-nrel** [comment]
Fixed by commit in previous comment.
