### ISSUE TITLE
Restart not working - error about *.rst file?

### ISSUE THREAD

**Issue by petesilk** [Exawind/nalu-wind#662]
I am not able to get a case to restart.
I have successfully restarted cases in the past.
I have examined the *.rst file in paraview and it looks good.

I see the following message: 

IOSS: Input database contains 8-byte integers. Setting Ioss to use 8-byte integers.

IOSS: Using decomposition method 'RCB' for 11,422,969 elements on 200 processors.
terminate called after throwing an instance of 'terminate called after throwing an instance of 'std::logic_errorstd::logic_error'
'
  what():    what():  Requirement( ok_id ) FAILED
Error occured at: stk_mesh/stk_mesh/base/BulkData.cpp:686
Error: Bad id : 0
Requirement( ok_id ) FAILED
Error occured at: stk_mesh/stk_mesh/base/BulkData.cpp:686
Error: Bad id : 0

**Comment by petesilk** [comment]
here is all that I changed in the input file:

< #    mesh: ../Bolund_Ext_Domain.exo
<     mesh: restart/restart_abl.rst
---
>     mesh: ../Bolund_Ext_Domain.exo
> #    mesh: restart/restart_abl.rst


<       restart_time: 20.5
---
> #      restart_time: 3.2


< #      termination_step_count: 10000
<       termination_step_count: 14000
---
>       termination_step_count: 10000

**Comment by petesilk** [comment]
better format
[restart.txt](https://github.com/Exawind/nalu-wind/files/4948661/restart.txt)

**Comment by sayerhs** [comment]
@petesilk Usually it is better to attach the full YAML input file as it helps with debugging. In your situation, my guess is that you have not commented out. You need this variable when you are using a single Exodus file and you want it decomposed over multiple MPI ranks. However, if you already have a decomposed file, then you need to comment this variable out, otherwise you'll see errors about not being able to read a mesh file.

```YAML
automatic_decomposition_type: rcb
```

**Comment by petesilk** [comment]
Thank you...that's it.   

I had done a recombine on the restart file to view in paraview, but you are saying it still grabs the broken up files, even if a recombine is present in the directory, correct?

**Comment by sayerhs** [comment]
I am closing this since it appears that the issue has been resolved. Please reopen if you've further issues.
