### ISSUE TITLE
Regression test failures in Nalu-Wind

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#671]
It seems that we have failures in several of [Trilinos related tests](https://my.cdash.org/viewTest.php?onlyfailed&buildid=1864153). Looking at the changes since the previous day, I don't see anything obvious in Nalu-Wind commits that could cause these diffs. So I am wondering if the Ifpack2 and MueLu changes in trilinos could cause these diffs. The Aug 4 test used trilinos/trilinos@721370bdcc and the failing build used trilinos/trilinos@64d21a127

Can @jhux2 or @lucbv  comment if the diffs look like it could have originated due to MueLu/Tpetra/zoltan updates and we can rebless the golds, or if this warrants further investigation on nalu-wind side?

**Comment by sayerhs** [comment]
trilinos/trilinos#7776

**Comment by jhux2** [comment]
@sayerhs Yes, this change appears to be due to a change in the eigenvalue estimate in Ifpack2.

**Comment by jrood-nrel** [comment]
So it looks like I should just update the golds?

**Comment by jhux2** [comment]
> So it looks like I should just update the golds?

@jrood-nrel @sayerhs The largest diff is 1e-6, e.g., from [dgNonConformalThreeBlade](https://my.cdash.org/test/6186953).  Is this acceptable from the simulation side?
