### ISSUE TITLE
probe name

### ISSUE THREAD

**Issue by petesilk** [Exawind/nalu-wind#677]
I am running a  case with multiple   line_of_site_specifications:  probes.  They have names such as "- name: probeM0",  "- name: probeM2", etc.   However, if I include the name "- name: probeM1", the case will not start.  Does a core dump and creates the log and error files attached.  If I change that one probe name, even simply by removing the "o" to make it "prbeM1", the case runs fine.

is "probeM1" a reserved or special name?  why does this not work?

Thank you.
[user_script.stderr.txt](https://github.com/Exawind/nalu-wind/files/5069949/user_script.stderr.txt)
[TM.log](https://github.com/Exawind/nalu-wind/files/5069952/TM.log)

**Comment by petesilk** [comment]
Note that if I start from a mesh, instead of trying to use the "restart" from a previous solution.....I do not have the above problem.

**Comment by psakievich** [comment]
Interesting.  when you remove the "o" are you getting probe data from your probes? Also did you have these probes with the run you used to create your restart dataset?

**Comment by petesilk** [comment]
Yes, when I remove the “o” I do get data.

No, did not have these particular probes on in the run that created the restart data.
That said, other new probes (that were not on in the run that generated the restart file) with names other than probeM1 did work fine.

Thank you,
Peter

**Comment by spdomin** [comment]
I was just looking at Nalu-Wind and saw this bug report. The initial data probes implementation was really sensitive to restarting. There were plenty of use-cases that worked, however, may common ones that failed. You may want to check out Nalu for the fix. The nuance is the mapping of the probe to a mpi rank and and allowing for modifications at restart in addition to more details. The Nalu commit history has more info.

**Comment by petesilk** [comment]
Thanks much.

**Comment by psakievich** [comment]
@rcknaus and @pscrozi it looks like we have not applied the fix that @spdomin suggested. It would be worth updating the code for more parity with NaluCFD. However, it seems there are also workaround for the users.
