### ISSUE TITLE
Migrate Nalu-Wind to C++14 to keep up with Trilinos

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#705]
Trilinos develop branch requires C++14 at the end of this month. To keep up with Trilinos develop, Nalu-Wind needs to move to C++14 standard as well. @psakievich put in a pull-request #688 which did this, but had to be reverted due to compilation errors on our nightly testing infrastructure. The error is with missing symbols in Boost (which is used in DataProbePostProcessing). 

For nalu-wind to use C++14 and continue to depend on Boost `system` library, we need Boost.system also compiled with C++14 according to this issue https://github.com/boostorg/system/issues/26 However, since the error also shows up in GCC 7.4.0 builds, it is unclear if this is the correct fix.

**Comment by sayerhs** [comment]
@jrood-nrel Am I reading this correctly... spack has used `cxxstd=98`? Since @psakievich uses spack too and his boost didn't have this issue, is it something on our Eagle set up that is forcing this behavior? 

```
==> [2020-08-07-20:39:31.550499] './b2' 'install' 'threading=multi' '-j' '36' '--user-config=/scratch/jrood/.spack/stage/spack-stage-boost-1.68.0-fqayvcun3slndtnbibryqy3t4prvfd73/spack-src/user-config.jam' 'variant=release' '-s' 'BZIP2_INCLUDE=/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/bzip2-1.0.8-h44dqn5pllv22iparbomtz6witnf2ela/include' '-s' 'BZIP2_LIBPATH=/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/bzip2-1.0.8-h44dqn5pllv22iparbomtz6witnf2ela/lib' '-s' 'ZLIB_INCLUDE=/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/zlib-1.2.11-iode5iweyrwrwqi7vc4wbtvtszsqba5g/include' '-s' 'ZLIB_LIBPATH=/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/zlib-1.2.11-iode5iweyrwrwqi7vc4wbtvtszsqba5g/lib' '-s' 'NO_LZMA=1' '-s' 'NO_ZSTD=1' 'link=static,shared' '--layout=system' 'toolset=gcc' 'cxxstd=98'
```

**Comment by sayerhs** [comment]
OK. That seems to be the default in `spack/var/spack/repos/builtin/packages/boost`, @psakievich do you use a custom build where you reset this? Or do you not use a spack build of boost? 

```python
    variant('cxxstd',
            default='98',
            values=('98', '11', '14', '17', '2a'),
            multi=False,
            description='Use the specified C++ standard when building.')
```

**Comment by psakievich** [comment]
@sayerhs no I just used spack.  It looks like boost was still using `cxxstd=98` in my builds. I think I just built and tested on my mac though.  I'll re-test the PR on my laptop and the sandia hardware.

**Comment by sayerhs** [comment]
Yes, macOS builds were working on the test machine also. https://my.cdash.org/index.php?project=Nalu-Wind&date=2020-09-07

**Comment by psakievich** [comment]
@sayerhs @jrood-nrel any idea why the intel compiler for that day gave make_unique errors? Doesn't seem to have the boost issue.

**Comment by sayerhs** [comment]
@psakievich Intel compiler uses headers from the GCC installation, so it is likely that it picked up GCC 4.8.x from the default OS install.

**Comment by psakievich** [comment]
Ah okay

**Comment by jrood-nrel** [comment]
I think I should have some time to erase and update the tests either next week or when I'm back from vacation. I can make sure boost is built with c++14 and I can add a boost module with c++14 to eagle once I verify it in the testing.

**Comment by jrood-nrel** [comment]
I just need to get boost to build with clang, but do we need to reintroduce @psakievich 's c++14 changes now that I have boost built with c++14?

**Comment by sayerhs** [comment]
@jrood-nrel yes, we need to revert the revert.

**Comment by alanw0** [comment]
In case it matters, the Trilinos folks are now saying they will wait another month or so before they start requiring c++14. Apparently it's tied to the next kokkos snapshot into trilinos, which is expected in November.

**Comment by sayerhs** [comment]
@lucbv @lawrenceccheung Please see discussion in #712 also. Would it be possible for you to check about Boost `> 1.70.0` on Sandia machines and let us know whether we can require that for our builds?

**Comment by jhux2** [comment]
@sayerhs Is 1.70.0 sufficient?

**Comment by lawrenceccheung** [comment]
FYI, I just tested `boost-1.70.0`, compiled via spack, with the latest nalu-wind (56fd949) and trilinos (`83a0e3b`), and it seemed to work fine on skybridge at Sandia.

**Comment by psakievich** [comment]
@jrood-nrel @sayerhs 

Pretty sure these build errors are c++14 related
https://my.cdash.org/viewBuildError.php?buildid=1896373

I saw them earlier when I did a cuda build with c++14 on.  I'll try to resolve them tomorrow if no one else is working on it right now.

**Comment by sayerhs** [comment]
@psakievich If you can take a crack at this, it would be great!
