### ISSUE TITLE
Question running ABL example

### ISSUE THREAD

**Issue by mathbird** [Exawind/nalu-wind#719]
I tried to setup and run the examples in nalu_wind, following the instructions in the link

https://nalu-wind.readthedocs.io/en/latest/source/user/examples/ABLexample.html

But I could not find command `abl_mesh` there.  Where can I find it?

```
[ abl_neutral]$ ls
abl_plots.py  abl_preprocess.yaml  abl_simulation.yaml  pre_process.sh  setup.yaml  template_input_files
```

**Comment by tonyinme** [comment]
Hey @mathbird, thanks for reaching out.

You need to compile wind-utils as suggested in the [Introduction](https://nalu-wind.readthedocs.io/en/latest/source/user/examples/introduction.html).

abl_mesh is a mesh utility and it is available as one of the executables within wind-utils.

**Comment by mathbird** [comment]
thanks.
