### ISSUE TITLE
Broken SST regressions

### ISSUE THREAD

**Issue by marchdf** [Exawind/nalu-wind#720]
Even after rebless of the golds, two regression tests for SST/TAMS are broken: `airfoilRANSEdgeNGPTrilinos.rst` and `tamsChannelElem`

**Comment by jrood-nrel** [comment]
I can update `airfoilRANSEdgeNGPTrilinos.rst`. It takes two days to update restart test gold files. However, `tamsChannelElem` is complaining of NaNs.

**Comment by marchdf** [comment]
Oh right that makes sense. Thanks, Jon! Jeremy is looking into the other one

**Comment by jrood-nrel** [comment]
Actually `airfoilRANSEdgeNGPTrilinos.rst` has a sensitivity issue to other compilers where it's diverging beyond the even the loose tolerances. It's currently exact on GCC 7.4.

**Comment by marchdf** [comment]
@jrood-nrel the merge #721 s going to require another rebless of all SST/TAMS tests...
