### ISSUE TITLE
Segfault in MijTensorNGP.hex27_sim unit test 

### ISSUE THREAD

**Issue by mathbird** [Exawind/nalu-wind#724]
I built nalu-wind with Intel mpiicpx compiler. when I ran unittestX, it gave me the following errors. Have you met this issue before? Do you know usually what causes it? and how to fix it?

```
[d]$ unittestX
…
[----------] 2 tests from MijTensorNGP
[ RUN      ] MijTensorNGP.hex27
[       OK ] MijTensorNGP.hex27 (2 ms)
[ RUN      ] MijTensorNGP.hex27_simd
**Segmentation fault**

```

**Comment by sayerhs** [comment]
@mathbird can you provide more details on the operating system, processor, and the intel compiler version you are using?

**Comment by jrood-nrel** [comment]
This looks like a machine that probably shouldn't be discussed here.

**Comment by mathbird** [comment]
[d]$ uname -a
Linux  3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[d]$ mpiicpx --version
Intel(R) oneAPI DPC++ Compiler Pro 2021.1 (2020.8.0.0827)
Target: x86_64-unknown-linux-gnu
Thread model: posix

[d]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
...

**Comment by jrood-nrel** [comment]
I'm closing this and we will discuss this issue through a different channel.
