### ISSUE TITLE
SST IDDES implementation in MomentumOpenEdgeKernel

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#746]
I think the implementation of upwinding in `MomentumOpenEdgeKernel` for the SST IDDES model is incorrect, and has an out of bounds memory access. The field `peclet_factor` is declared on `EDGE_RANK` 

https://github.com/Exawind/nalu-wind/blob/cde12532bbba877e56da84b5d4782e817dca5ae2/src/edge_kernels/MomentumOpenEdgeKernel.C#L49

and is being registered to ElemDataRequests as `FACE_RANK`, with incorrect number of values

https://github.com/Exawind/nalu-wind/blob/cde12532bbba877e56da84b5d4782e817dca5ae2/src/edge_kernels/MomentumOpenEdgeKernel.C#L67

Unfortunately, the `ThrowRequireMsg` doesn't catch this 

https://github.com/Exawind/nalu-wind/blob/cde12532bbba877e56da84b5d4782e817dca5ae2/src/ElemDataRequests.C#L58-L59 because it checks for either face or edge whereas it should disallow `EDGE_RANK` when `MetaData::spatial_dimension() == 3u` 

```C++
  ThrowRequireMsg(
    ((field.mesh_meta_data().spatial_dimension() == 3u) &&
     (field.entity_rank()==stk::topology::FACE_RANK)) ||
    (field.entity_rank()==stk::topology::EDGE_RANK),
    "ElemDataRequests ERROR, add_face_field called with field "<<field.name()<<" which has entity-rank=="<<field.entity_rank()<<" but is expected to have rank==ELEM_RANK");
```

The out of bounds memory access occurs here 

https://github.com/Exawind/nalu-wind/blob/cde12532bbba877e56da84b5d4782e817dca5ae2/src/edge_kernels/MomentumOpenEdgeKernel.C#L116

because the ScratchView was only allocated with 1 scalar per face, but is accessing the array with `nodesPerFace`.

The usage here indicates that the `peclet_factor` should be accessed on the edge normal to the face and not on the face. 

https://github.com/Exawind/nalu-wind/blob/cde12532bbba877e56da84b5d4782e817dca5ae2/src/edge_kernels/MomentumOpenEdgeKernel.C#L231-L232

**Comment by sayerhs** [comment]
@alanw0 Can you also please take a look at the `add_face_field` usage here and comment?

**Comment by alanw0** [comment]
Yes, it's a little hard to tell if I'm seeing all of the code that matters, but it looks like the add_face_field call should take something like BcAlgTraits::numFaceIp_ instead of 1.

**Comment by sayerhs** [comment]
@alanw0 The field that is being registered is not declared on `FACE_RANK` but instead is on `EDGE_RANK` (this is for a 3D simulation).

**Comment by alanw0** [comment]
Yep, that's wrong, it needs to be a FACE_RANK field for 3D. I don't know the math well enough here, but do you think we would want to use EDGE_RANK fields here in 3D? If so, we would need to alter ElemDataRequests. That ThrowRequireMsg mentioned up above should possibly check against 'meta.side_rank()' which is automatically set to FACE_RANK for 3D and EDGE_RANK for 2D.

**Comment by sayerhs** [comment]
@alanw0 Thanks for confirming. Yes, I'd forgotten about `meta.side_rank()`. So this particular usage of `EDGE_RANK` field is a little tricky and not something I think ElemDataRequests on a face should support. In this case, we are looping over the faces of a sideset and for each of the nodes that make up the face we we want the field data on the edge connecting this particular face node to the opposing node for the volume element.

**Comment by psakievich** [comment]
@sayerhs yes I think you are right. @gantech and I were discussing this on slack not too long ago and we don't think we really need this open bc implementation to for the upcoming milestones.   I've also got doubts if it will give the desired behavior since the Strelets algorithm reduces upwinding in regions with eddies which is not what we'd want for an open bc.  A quick and good fix would be to just revert the changes to this file.  I'll open a PR for that change.

**Comment by psakievich** [comment]
@sayerhs I've opened a PR, but I can't assign any reviewers or give it the bug fix label.
