### ISSUE TITLE
Remaining issues 11-11-2020

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#750]
1. `ableUnstableEdge` - Mac GCC 7.4, Linux GCC 4.9.4, Linux Clang 7 - #698 @mchurchf 
```
`Belos::StatusTestImpResNorm::checkStatus(): One or more of the current implicit residual norms is NaN.`
```
2. `ablNeutralStat` - Linux Intel 2018 - @lawrenceccheung 
```
DIFFER : VARIABLE : resolved_stress_tavg : POSITION : [1,0,3] : VALUES : 3.66611 <> 3.66611 : PERCENT : 1.90204e-10
DIFFER : VARIABLE : resolved_stress_tavg : POSITION : [2,0,3] : VALUES : 2.57554 <> 2.57554 : PERCENT : 2.10773e-10
FAIL: resolved_stress_tavg
```
3. Golds updated in https://github.com/Exawind/nalu-wind/commit/16990b993763e66855905b7868bdfa5e42c4fe00 in response to #725 likely need to be reverted. They have not yet been vetted. @psakievich 

4. NGP test tolerance issues on Eagle are being dealt with by @sayerhs and @PaulMullowney .

**Comment by psakievich** [comment]
@jrood-nrel for `ablUnstableEdge` I don't think this is a platform thing.  When I was looking at the gold file re-bless from `16990b993` I noticed the norms jumped by 11 orders of magnitude for these files.

**Comment by jrood-nrel** [comment]
@psakievich Ok thanks. I will add that to the list then.

**Comment by lawrenceccheung** [comment]
@jrood-nrel Yeah, I noticed on the Sandia machines with linux/intel-19.0.3 that `ablNeutralStat` was failing on that variable as well.  The difference is so small and just at those locations, I think I can just adjust the tolerance and have it pass again.

Lawrence

**Comment by jrood-nrel** [comment]
@mchurchf So I think that last statement from your email is what’s left. Three different compilers are complaining of NaNs after #698. I can provide a script for you on the test machine that should be able to recreate the issue for any of the compilers in the tests. Probably best to use Clang. This following line might also help as Clang provides the most information:
```
terminating with uncaught exception of type std::logic_error: Requirement( src[simdIndex][0] == data[simdIndex]->get_2D_view_by_index(viewIndex).data()[0] ) FAILED
Error occured at: nalu-wind/include/CopyAndInterleave.h:76
```

**Comment by sayerhs** [comment]
@mchurchf @jrood-nrel The ABL unstable/stable tests are woefully out of date. For example, they were still using WALE. So I've opened #753 where I have updated these regression tests with input files that are based on the HFM Q3 milestone work. I think it is better to dump the old files and use the ones that are representative of how we run the code in production simulations.

**Comment by sayerhs** [comment]
@marchdf @jrood-nrel Seems like we didn't check our rebless for `airfoilRANSEdgeNGPTrilinos.rst` in response to #714 (see the changes to gold file 18b5ab4af5b6c6001ae48148793d4dd4d1fbb159). This test seems to really not like the new clipping algorithm.

```diff
-58.97355020867093 4 0.266667
-35.41074202415037 5 0.333333
-5.351114887646522 6 0.4
-1.349934574868489 7 0.466667
-0.8165216631799972 8 0.533333
-0.6383666200632478 9 0.6
-0.5153460342243623 10 0.666667
-0.4148737635192436 11 0.733333
-0.3318647400806257 12 0.8
-0.2613541824098754 13 0.866667
-0.21382515925498 14 0.933333
-0.1709023448611098 15 1
-0.1451533040500358 16 1.06667
-0.1240009499151366 17 1.13333
-0.1190131556641963 18 1.2
-0.1026264179120115 19 1.26667
-0.09634501221895699 20 1.33333
+425771.9252542811 4 0.266667
+175419.5910165003 5 0.333333
+684.4726867146017 6 0.4
+3.794885631015843 7 0.466667
+0.8114241379449301 8 0.533333
+0.6434928016575335 9 0.6
+0.5162667653731071 10 0.666667
+0.4208414087439341 11 0.733333
+0.3691350511249462 12 0.8
+0.3192890207072733 13 0.866667
+0.2533478677199941 14 0.933333
+0.2561620686583042 15 1
+0.2957178423395239 16 1.06667
+0.2553526969879484 17 1.13333
+463.7972075912386 18 1.2
+51867857414.33191 19 1.26667
+30704994769.82249 20 1.33333```

**Comment by lawrenceccheung** [comment]
Item 2 should be addressed in PR [755](https://github.com/Exawind/nalu-wind/pull/755).  Let me know if `ablNeutralStat` continues to have any issues passing.

Lawrence
