### ISSUE TITLE
documentation for manual installation is too outdated

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#76]
@sayerhs @jhux2 
I am trying to install nalu-wind manually (without spack).
I am able to install trilinos correctly, although the recommended configure file needs to be updated.
However I cannot build nalu-wind since the `do-configNalu` script does not exist anymore.
Is there a way to get a reasonable configuration script for Nalu?
Also the documentation does not mention `Tioga` which seems to be required.
Should I install Tioga or is it only optional?

**Comment by jrood-nrel** [comment]
@lucbv I will try to update these instructions today.

**Comment by sayerhs** [comment]
@lucbv You don't need Tioga to compile `nalu-wind`, by default `ENABLE_TIOGA` is off in Nalu-Wind's CMakeLists.txt 

The latest settings for Trilinos are available [here](https://github.com/Exawind/build-test/blob/master/configs/machines/peregrine/do-config-trilinos-peregrine.sh).

**Comment by lucbv** [comment]
@jrood-nrel thanks for updating the instruction!
@sayerhs thanks for the link to the Nalu configuration, I will use it as a baseline for my local configuration.
I will keep you posted on my progress.

**Comment by lucbv** [comment]
@jrood-nrel and @sayerhs, I have been able to modify the nalu configuration to use Sandia's sems modules.
I ran `unittestX` and it reported 283 tests passed so I guess I am good to go.
Thanks for the help!

**Comment by jhux2** [comment]
@DrBooom fyi
