### ISSUE TITLE
Failing nightly regression tests

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#792]
[CUDA tests](https://my.cdash.org/build/1937453/notes#note0) are failing on eagle because of errors in hypre build.

**Comment by jrood-nrel** [comment]
It feels like hypre needs a newer CUDA version now.

**Comment by jrood-nrel** [comment]
```
  >> 187    _hypre_utilities.hpp(765): error: identifier "cusparseIndexType_t" 
            is undefined
```

**Comment by sayerhs** [comment]
Yeah, this seems like a new development (related to hypre-space/hypre#163). @PaulMullowney have you tested the latest hypre with CUDA 9.2.88?

**Comment by PaulMullowney** [comment]
I used Cuda 10.2.89. On eagle, did the build of new Hypre master fail with Cuda 9?

I see other failing tests on other platforms. Some of them look like reasonable diffs like ablNeutralNGPHypre*, others don’t look reasonable like airfoilRANSEdgeNGPHyre.rst. I will investigate as this test was passing for me with Cuda 10 on eagle.

-Paul

**Comment by sayerhs** [comment]
@PaulMullowney there are two separate issues.

- [Test failures on non-CUDA builds](https://my.cdash.org/viewTest.php?onlyfailed&buildid=1937745) This is because of the mesh submodule being corrupted by #787 
- [Hypre build error for CUDA](https://my.cdash.org/build/1937453/notes#note0) - This seems like a new issue. I guess we could try with `--disable-cusparse`, but it shouldn't be required.

**Comment by PaulMullowney** [comment]
Hmmm. I just built Hypre master (commit b49727f1) with Cuda  9.2.148 just fine.

Here’s my config line:
./configure --prefix=/scratch/pmullown/hypre-master-gpu-install-cuda_9.2.148/ --without-superlu --disable-bigint --without-openmp --with-cuda --enable-unified-memory --enable-curand --disable-cub

I also have:
CFLAGS=”-O2”
CXXFLAGS=”-O2”
HYPRE_CUDA_SM=70

**Comment by sayerhs** [comment]
@PaulMullowney The nightly-test system is using CUDA 9.2.88. 

```
$ echo $MODULEPATH
/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/share/spack/modules/linux-centos7-x86_64:/nopt/nrel/ecom/hpacf/software/modules-2019-05-23/gcc-7.4.0:/nopt/nrel/ecom/hpacf/utilities/modules-2019-05-23:/nopt/nrel/ecom/hpacf/compilers/modules-2019-05-23

$ module list

Currently Loaded Modules:
  1) python/3.7.3   3) binutils/2.31.1   5) gcc/7.4.0
  2) git/2.21.0     4) cuda/9.2.88       6) gcc-7.4.0/openmpi/3.1.4

$ ./configure --with-cuda --enable-unified-memory --without-openmp --disable-bigint --enable-curand --disable-cub --without-superlu
```

**Comment by sayerhs** [comment]
Can you provide more details on where you're accessing CUDA 9.2.148 from?

```
--------------- /nopt/nrel/ecom/hpacf/compilers/modules-2020-07 ----------------
   cuda/9.2.88/6p52      cuda/10.1.243/4ch2 (D)    cuda/11.0.2/kvpv
   cuda/10.0.130/qmdg    cuda/10.2.89/rmcc

----------------- /nopt/nrel/apps/modules/default/modulefiles ------------------
   cuda/10.2.89             cudnn/7.6.1/cuda-10.1
   cudnn/7.4.2/cuda-10.0    dav_cuda/10.1.168

--------- /nopt/nrel/ecom/hpacf/software/modules-2019-05-23/gcc-7.4.0 ----------
   cuda/9.2.88 (L)    cuda/10.0.130 (D)    cuda/10.1.168

```

**Comment by sayerhs** [comment]
`git bisect` shows this as the commit with which we are no longer able to build with CUDA 9.2.88

```
commit 22f4d3f8c6a34fb5dcae4100579307aba0210aaa
Author: Luke <AerysL@users.noreply.github.com>
Date:   Thu Nov 5 22:57:57 2020 -0600

    Cuda 11 API (#163)

    This PR adds CUDA-11 support.
```

**Comment by sayerhs** [comment]
hypre-space/hypre#245

**Comment by PaulMullowney** [comment]
I think I pulled that form summit. I didn’t notice that it failed to find that module so it upgraded to Cuda 10 and built successfully.

Given that our default exawind_builder eagle config is Cuda10 and MPT, I echo Ruipeng’s comments. Do we need Cuda 9 anymore?

**Comment by jrood-nrel** [comment]
Are we fine switching to 10.2? I think I'm prepared to do so.

**Comment by sayerhs** [comment]
@jrood-nrel I've been using CUDA 10.2.89 for exawind-builder, and I do think we should switch to the newer version. However, @PaulMullowney just discovered some weird behavior with latest hypre/nalu-wind versions on CUDA 10.2 when he runs the regression tests. Apparently, the weird behavior only happens on eagle and not on Summit. So he is chasing that down.
