### ISSUE TITLE
CPU build not compiling on summit (Kokkos simd)

### ISSUE THREAD

**Issue by PaulMullowney** [Exawind/nalu-wind#817]
Here are the compilation errors ...

[3/645] Building CXX object CMakeFiles/nalu.dir/src/AssembleNodalGradBoundaryAlgorithm.C.o
FAILED: CMakeFiles/nalu.dir/src/AssembleNodalGradBoundaryAlgorithm.C.o
/sw/summit/gcc/7.4.0/bin/g++  -DNALU_USES_HYPRE -DNALU_USES_TIOGA -DTIOGA_HAS_NODEGID -I../include -Iinclude -isystem /gpfs/alpine/cfd116/scratch/mullowne/install/cpu/trilinos-devel-3-4-2021/include -isystem /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/zlib-1.2.11-tdykbkiueylpgx2rshpms3k3ncw5g3f6/include -isystem /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-2020-08/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/superlu-4.3-bdwzcj6u4rrwhnc26xvaeh5hzn6wrdll/include -isystem /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-2020-08/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/netcdf-c-4.7.3-hfb2wgdc2z45zl5vkn5xg2e4jzmsewwe/include -isystem /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-2020-08/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/hdf5-1.10.4-san7kbigg3es7v6n3tfj67uhfybbujix/include -isystem /autofs/nccs-svm1_proj/cfd116/shreyas/summit/exawind-2020-08/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/parallel-netcdf-1.12.1-jy5jjdxpxzgq534ylam72fcsyvl6hg5t/include -isystem /gpfs/alpine/cfd116/scratch/mullowne/install/cpu/hypre-ijassem-twostage-3-4-2021/include -isystem /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/include -isystem /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/lib -O3 -DNDEBUG   -Wall -Wextra -pedantic -faligned-new -pthread -std=c++14 -MD -MT CMakeFiles/nalu.dir/src/AssembleNodalGradBoundaryAlgorithm.C.o -MF CMakeFiles/nalu.dir/src/AssembleNodalGradBoundaryAlgorithm.C.o.d -o CMakeFiles/nalu.dir/src/AssembleNodalGradBoundaryAlgorithm.C.o -c ../src/AssembleNodalGradBoundaryAlgorithm.C
In file included from /gpfs/alpine/cfd116/scratch/mullowne/install/cpu/trilinos-devel-3-4-2021/include/stk_simd/kokkos_simd/simd.hpp:82:0,
                 from /gpfs/alpine/cfd116/scratch/mullowne/install/cpu/trilinos-devel-3-4-2021/include/stk_simd/Simd.hpp:58,
                 from ../include/SimdInterface.h:21,
                 from ../include/master_element/MasterElement.h:18,
                 from ../src/AssembleNodalGradBoundaryAlgorithm.C:19:
/gpfs/alpine/cfd116/scratch/mullowne/install/cpu/trilinos-devel-3-4-2021/include/stk_simd/kokkos_simd/vsx.hpp: In member function 'kokkos_simd::simd_mask<double, kokkos_simd::simd_abi::vsx> kokkos_simd::simd_mask<double, kokkos_simd::simd_abi::vsx>::operator&&(const kokkos_simd::simd_mask<double, kokkos_simd::simd_abi::vsx>&) const':
/gpfs/alpine/cfd116/scratch/mullowne/install/cpu/trilinos-devel-3-4-2021/include/stk_simd/kokkos_simd/vsx.hpp:222:52: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_and
     return simd_mask(vec_and(m_value, other.m_value));

**Comment by jrood-nrel** [comment]
This seems to work with GCC 9 on Summit. I've emailed STK about this.

**Comment by alanw0** [comment]
Tagging @tasmith4 to make sure Timothy is seeing this.
