### ISSUE TITLE
CDash: Failing tests 2020-03-10

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#821]
Two tests `ablNeutralStat` and `actLineSimple` are failing. These are likely related to PRs #810 and #783 respectively. 

- [First instance](https://my.cdash.org/test/27161977) of `actLineSimple` failure
- [First instance](https://my.cdash.org/test/27271248) of `ablNeutralStat` failure
- PR #810 also introduced [unused variable warnings](https://my.cdash.org/viewBuildError.php?type=1&buildid=1979016)

**Comment by psakievich** [comment]
The `actLineSimple` failure is a simple fix opened in #822.  However, I'm wondering if we should just totally remove the `actLineSimple` code path entirely.  It is a redundant and less performant branch of the code compared to `actLineSimpleNGP`.  We can keep the `ActLineSimple` key for the actuator type but just push that to the `ActLineSimpleNGP` code paths as well.  This is what I envisioned for all the actuator methods. Thoughts? @lawrenceccheung any input?

**Comment by sayerhs** [comment]
@psakievich I've no objections to removing `ActLineSimple` pathway.

**Comment by lawrenceccheung** [comment]
@psakievich Yes, I agree, the `actLineSimple` code is redundant and it's probably just more opportunities for bugs to appear.  I'd be onboard with removing this pathway and doing the same for all actuator methods as well.

**Comment by sayerhs** [comment]
@neilmatula @psakievich PR #810 also breaks the ABL neutral edge regression tests on GPUs. [CDash link](https://my.cdash.org/viewTest.php?onlyfailed&buildid=1979523).

**Comment by psakievich** [comment]
@neilmatula it looks like we're missing the modify and sync in the kernel. I can help you test this on a gpu build today.
