### ISSUE TITLE
Nightly regression test being run with lax tolerances 

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#839]
The GCC version on the nightly regression test machine was updated to GCC 8.4.0. However, the regression test tolerance logic in `reg_tests/CMakeLists.txt` was not updated. https://github.com/Exawind/nalu-wind/blob/176155dac78465d0686f2a1255b4796ca776a593/reg_tests/CMakeLists.txt#L24-L37 

As a result, nightly tests have been running with `absolute_tolerance = 0.05` check. The logic in `CMakeLists.txt` should be updated. The nightly regression test scripts should also explicitly provide tolerances as command line arguments to CMake configure phase (e.g., `-DTEST_TOLERANCE="1.0e-15" -DTEST_REL_TOL="1.0e-13"`) so that it is explicit for each build/test configuration.

**Comment by jrood-nrel** [comment]
Oops, sorry about that.

**Comment by sayerhs** [comment]
Explicitly added tolerance to CMake configure step in testing scripts (see exawind/build-test#14). Default GCC version updated to 8.4.0 in 50887e1
