### ISSUE TITLE
Extract surface data during run

### ISSUE THREAD

**Issue by gantech** [Exawind/nalu-wind#859]
Its would be great to be able to extract the surface data and geometry on specified boundaries during a run at much higher frequencies compared to the full field output. This would help calculation of load profiles on blades at much higher frequencies. The geometry information could be optimized for rigid body rotation runs, but would be necessary at the same frequency for FSI runs.

**Comment by psakievich** [comment]
@gantech thanks for putting this on the radar.  I don't think this will be too big of a lift.  Would you be okay with wrapping this into the Q4 milestone as a subtask or do you need it sooner?

**Comment by psakievich** [comment]
Just updating here that we talked about this today and are going to try using a transfer and input-output region.
