### ISSUE TITLE
Errors in ablNeutralEdge and unitTest2

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/nalu-wind#9]
It appears that https://github.com/Exawind/nalu-wind/commit/c8a7310cd16c66c55973431afcacde43f33de739 is causing runtime errors for the `ablNeutralEdge` test, and it resurfaced errors in the `unitTest2` test.

`ablNeutralEdge`
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ABL Forcing requires ABL Boundary Layer statistics
```

`unitTest2` nans are back:
```
/projects/ecp/exawind/nalu-wind-testing/nalu-wind/unit_tests/UnitTestKokkosMEBC.C:20: Failure
The difference between stk::simd::get_data(values(i,j,k),0) and oldValues[counter++] is nan, which exceeds tol, where
stk::simd::get_data(values(i,j,k),0) evaluates to -nan,
oldValues[counter++] evaluates to -0.30222829240841764, and
tol evaluates to 1e-10.
i:3, j:0, k:0
/projects/ecp/exawind/nalu-wind-testing/nalu-wind/unit_tests/UnitTestKokkosMEBC.C:20: Failure
The difference between stk::simd::get_data(values(i,j,k),0) and oldValues[counter++] is nan, which exceeds tol, where
stk::simd::get_data(values(i,j,k),0) evaluates to -nan,
oldValues[counter++] evaluates to -0.78566400196390185, and
tol evaluates to 1e-10.
```

Note, I have also noticed that GCC 4.9.4 has been differing in results than GCC 6, so I'm not worried about those types of failures at the moment.

@sayerhs

**Comment by jrood-nrel** [comment]
So it turns out the main problem is that `ablNeutralEdge` is run as a Catalyst test on one of the test machines and that input file just needs to be updated. That will probably be sufficient to close this.

**Comment by jrood-nrel** [comment]
https://github.com/Exawind/nalu-wind/commit/e0c28255fa6dd948a0f0c0355ae51a6a69a55375 Resolved this.

**Comment by rcknaus** [comment]
Unittest2 is failing intermittently thanks to some undefined behavior in the wedge face grad op.  I fixed it in https://github.com/NaluCFD/Nalu/commit/9a04c4aa22db0d2a2a1c9e83c4f46b63d4707e3e for NaluCFD.  What's the procedure for moving that to nalu-wind?  Should I open up a new pull-request here?
