### ISSUE TITLE
Can CDash send summary emails?

### ISSUE THREAD

**Issue by jhux2** [Exawind/nalu-wind#909]
Can the Nalu-Wind cdash be configured to send automatic emails in the case that there are failing tests?

**Comment by jrood-nrel** [comment]
Sure. Do you want it to email you about failing tests?

**Comment by jhux2** [comment]
I think that would be a nice feature to have.  See #908, for example.

**Comment by jrood-nrel** [comment]
I added your email to receive updates from the dashboard. However, I think in doing so it revoked my access to manage it.

**Comment by jhux2** [comment]
Thanks.  Where do I look to see my subscription?

**Comment by jrood-nrel** [comment]
You probably need to make a login for my.cdash.org

**Comment by jhux2** [comment]
Ok, logged in.  There's a warning message

  | *This project has not been configured to send emails.               Contact the project administrator."

Guess that's a red herring?

**Comment by jrood-nrel** [comment]
I don't have permission to the project anymore. I will have to email them.

**Comment by jhux2** [comment]
I'll let you know if I get any emails.

**Comment by jrood-nrel** [comment]
I did originally, but I turned them off. Maybe I disabled it for the whole project early on.

**Comment by jhux2** [comment]
Fyi, no email today, so I guess it's disabled for the whole project.
