### ISSUE TITLE
Failing tests on dashboard due to changes in Trilinos parameters

### ISSUE THREAD

**Issue by jhux2** [Exawind/nalu-wind#922]
## Detailed description of the bug 

Many Nalu-Wind tests on the dashboard are failing with this error:

```
Error, the parameter {name="aggregation: phase2a include root",type="bool",value="0"}
in the parameter (sub)list "ANONYMOUS"
was not found in the list of valid parameters!
```

**Comment by jhux2** [comment]
@jrood-nrel The failures due to the invalid MueLu parameter are gone, but every test I've looked at on the dashboard is  failing either with huge diffs or a memory issue.

**Comment by jrood-nrel** [comment]
Yeah now that the tests execute I need to fix some issues with the gold files.

**Comment by jhux2** [comment]
Closing as fixed.

**Comment by psakievich** [comment]
@Kp-cloud-stack the examples are out of date. See #1060 for more discussion on this. I would like to get them up to date soon, but in the mean time could you describe the cases you are interested in running?  We can help you set them up.
