### ISSUE TITLE
Coupled overset runs are broken

### ISSUE THREAD

**Issue by ashesh2512** [Exawind/nalu-wind#936]
## Detailed description of the bug 

Recently a few of us have noticed coupled overset runs failing in nalu. Not exactly sure where the issue lies. We have a regression test that does use coupled overset runs - overset cylinder. However - 1) The location of the hole does not change in that regression test which is the scenario where others have run into issues 2) The ghosting doesn't change significantly which is the case with turbine runs. Additionally, for a stationary mesh, coupled runs still appear to do fine.

### Details to reproduce bug/build error

SHA ID of the Nalu-Wind commit you are using -
This bug is present as of the latest commit. Not quite sure when it was introduced, but this capability was thoroughly tested and worked as of the following commits - 
   Nalu-Wind GIT Commit SHA: 50ef780f1afb7cc014f4e9df364f04ca68c57d34
   Trilinos Version: 12.17-gadef041e9e
 
Details of your simulation (input file, mesh description, etc.) -
[nrel5mw.txt](https://github.com/Exawind/nalu-wind/files/8035948/nrel5mw.txt)

Stack trace of the runtime error output -
[nrel5mw.log](https://github.com/Exawind/nalu-wind/files/8035849/nrel5mw.log)

**Comment by ddement** [comment]
@ashesh2512 Do you know where we can get access to the nrel5mw_overset.exo mesh used in this case?  Could you perhaps put it in the proj-shared folder on Frontier's Orion filesystem?  Also, what recipe did you use for running this case (number of nodes, GPUs, machine used, etc)?

**Comment by mbkuhn** [comment]
Due to the age of this issue, and that a merged PR claims to fix it, I'll consider this issue closed.
