### ISSUE TITLE
Unguarded use of variable "mempool_max_cached_bytes"

### ISSUE THREAD

**Issue by jhux2** [Exawind/nalu-wind#971]
In `HypreNGP.h`, the declaration of`mempool_max_cached_bytes` is guarded by an ifdef, but it is used a few lines later unguarded.

https://github.com/Exawind/nalu-wind/blob/5d6a3e8d34c551160cf9e269ffec15b8a638ef50/include/HypreNGP.h#L40-L53

**Comment by PaulMullowney** [comment]
I'll fix. Sorry

**Comment by PaulMullowney** [comment]
/gpfs/alpine/proj-shared/cfd116/mullowne/spack-manager/environments/exawind-dev_gcc-10.2.0_cuda-11.4.2/nalu-wind/src/Realm.C:112:10: fatal error: stk_mesh/base/MeshBuilder.hpp: No such file or directory

**Comment by jhux2** [comment]
@alanw0 @tasmith4

**Comment by jhux2** [comment]
Or is this a spack-manager issue?

**Comment by PaulMullowney** [comment]
This may be my fault. I think I need to update trilinos though I'm worried new trilinos won't build with GPU on summit

**Comment by jhux2** [comment]
I've been able to build but am getting unhelpful runtime errors:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaStreamSynchronize(stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /ccs/home/jjhu/exawind/sources/Trilinos-dev/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:162
```

**Comment by PaulMullowney** [comment]
Ok. I saw that also. That's why I didn't update Trilinos.

**Comment by jhux2** [comment]
What SHA of Trilinos are you using right now?

**Comment by PaulMullowney** [comment]
I was using:
0bbbbe2518c278bfc0e0a44d4c771c952c2f7633

I had to manually patch something in Kokkos in order to get stuff to run. I think the error you show above was introduced between April 26-30.

**Comment by jhux2** [comment]
I'll open an separate issue on this.

**Comment by jhux2** [comment]
Let's move any discussion of the Kokkos error to #973.

**Comment by PaulMullowney** [comment]
I just rebuilt with a new trilinos. I still see:
/gpfs/alpine/proj-shared/cfd116/mullowne/spack-manager/environments/exawind-dev_gcc-10.2.0_cuda-11.4.2/nalu-wind/src/Realm.C:112:10: fatal error: stk_mesh/base/MeshBuilder.hpp

**Comment by psakievich** [comment]
@jhux2 is it okay to close this issue?

**Comment by PaulMullowney** [comment]
I fixed this.
