### ISSUE TITLE
Tests that require hypre are enabled in a no-hypre build

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#976]
Specifically, these tests fail with `HYPRE support must be enabled during compile time`:
* ablNeutralEdgeAMS
* ablNeutralEdgeSST
* aslNeutralEdgeSST

@PaulMullowney I'm assuming these tests should just be disabled for builds without hypre.  If they instead need an edit to remove hypre from the input deck can you comment here?

**Comment by PaulMullowney** [comment]
I think those tests should be moved under the if(ENABLE_HYPRE) conditional
