### ISSUE TITLE
BoussinesqNonIso test uses a Python 3.7 feature

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#977]
The BoussinesqNonIso test is failing on CPU builds, with an error from `reg_tests/test_files/BoussinesqNonIso/norms.py` that `__init__() got an unexpected keyword argument 'capture_output'`.  A review of the Python subprocess documentation suggests that the `capture_output` parameter was not added until Python 3.7, but the nightly testing is using Python 3.6.

@psakievich @jrood-nrel do we have a minimum required Python version anywhere?  Do we want to declare Python 3.7 the minimum supported version and update spack-manager and the nightly testing scripts accordingly, or do we want to fix the script in question to be valid for older Pythons?

**Comment by psakievich** [comment]
I think we should fix the script to be valid for older pythons. I don't really want to start requiring python as a dependency for nalu-wind which is what we'd need to do to enforce this properly.
