### ISSUE TITLE
Dashboard issues

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#978]
Issues that need to be resolved to make the dashboard green:
* #976 
* #977
* #979 
* #973 
* #982
* #983
* #984
* #985
* #994
* #995
* #996
* #1026 
* #1027
* #1028
* #1041 

The list is complete as of this edit.  If new failures appear they can be added here.

**Comment by jhux2** [comment]
@tasmith4 Just a hunch, but I wonder if many of these test failures could have a similar root cause.  The current failure mode for #982  is

```
what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered
```

It appears there's a bad memory access upstream, and how it manifests changes (NAN, illegal mem access, out of memory, etc.).
