### ISSUE TITLE
Cuda out of memory errors

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#983]
Several tests give Cuda out-of-memory errors on the SNL dashboard.  Since these errors don't appear on the NREL dashboard, it's likely that it's either a machine-specific issue or a difference between `trilinos@stable` and `trilinos@develop`.

List of failures by platform (linked results are from the 6/15 build):
* [`Linux-gcc@9.3.0-cuda@11.2.2-Debug^trilinos@develop+uvm`](https://sierra-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=389830)
  * unitTestGPU
  * ActLineSimpleFLLC
  * ActLineSimpleNGP
  * airfoilRANSEdgeNGPTrilinos.rst
  * drivenCavity_p1
  * taylorGreenVortex_p3
* [`Linux-gcc@9.3.0-cuda@11.2.2-Release^trilinos@develop+uvm`](https://sierra-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=389828)
  * unitTestGPU
  * taylorGreenVortex_p3
* [`Linux-gcc@9.3.0-cuda@11.2.2-Release+fftw+hypre+openfast+tioga^trilinos@develop+uvm`](https://sierra-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=389829)
  * airfoilRANSEdgeNGPHypre.rst
  * airfoilRANSEdgeNGPTrilinos.rst
  * oversetCylNGPTrilinos

**Comment by ldh4** [comment]
This is odd. We've been able to build and run these regression tests on `ascicgpu22` for weeks without observing any out of memory error at any stage.
The spec I've been using is a variant of this: `nalu-wind+cuda+tioga+hypre cuda_arch=70 build_type=RelWithDebInfo ^trilinos+cuda+uvm`.  I am currently using Trilinos [7c98d83](https://github.com/trilinos/Trilinos/tree/7c98d835d5b3040e0254169aa5c22ca1651f9861)

**Comment by psakievich** [comment]
@ldh4 what version of cuda are you using? is it the one I installed?

**Comment by ldh4** [comment]
@psakievich I've been mostly using `cuda 11.2.2` that's pointed by spack-manager's `configs/ascicgpu/packages.yaml`. I think it is the one that you installed. There were a few days when I loaded up `cuda 11.2.1` from a sierra module, but I haven't seen either build producing this out of memory error.

**Comment by jhux2** [comment]
@tasmith4 It's possible that this is due to the same bug as in #973.  If you look at the failure symptom of oversetCylNGPTrilinos [here](https://sierra-cdash.sandia.gov/test/181728590) over the past few days, one of the symptoms is exactly #973.  I've attached my patch in case someone wants to try it on ascicgpu022.
[kokkos.patch.txt](https://github.com/Exawind/nalu-wind/files/8914587/kokkos.patch.txt)

**Comment by tasmith4** [comment]
@jhux2 the nightlies still show this error, even with the patch you list applied by default in Spack-Manager.  So I think it must be a separate issue, although potentially related to all the other cuda issues

**Comment by tasmith4** [comment]
combining into #994
