### ISSUE TITLE
CUBLAS error

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#984]
Some GPU regression tests are failing with the error:  `CUBLAS ERROR (code = 1, 0) at device_utils.c:1710`

Since it didn't appear a few days ago on eagle, it's likely to be an SNL-specific issue.

Affected tests (SNL internal link for 6/15 build):
* [Linux-gcc@9.3.0-cuda@11.2.2-Release+fftw+hypre+openfast+tioga^trilinos@develop+uvm](https://sierra-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=389829)
  * ablNeutralNGPHypre
  * ablNeutralNGPHypreSegregated
  * convTaylorVortex
  * oversetRotCylNGPTrilinos

@psakievich I don't know where CUBLAS comes from, is there a potential issue with our spack installs?

**Comment by tasmith4** [comment]
possibly related to #985

**Comment by alanw0** [comment]
I think cublas is one of the nvidia/cuda libraries. I wonder if there's an issue with our drivers/libraries installation.

**Comment by ldh4** [comment]
Since cuBLAS comes with `CUDA`, one quick thing to check is to see if this error can be reproduced with another version of `CUDA` (CUDA 10.2, for instance).

**Comment by tasmith4** [comment]
combining into #994
