### ISSUE TITLE
CUSPARSE error

### ISSUE THREAD

**Issue by tasmith4** [Exawind/nalu-wind#985]
Some GPU regression tests are failing with the error:  `CUSPARSE ERROR (code = 1, initialization error) at device_utils.c:1730`

Since it didn't appear a few days ago on eagle, it's likely to be an SNL-specific issue.

Affected tests (SNL internal link for 6/15 build):
* [Linux-gcc@9.3.0-cuda@11.2.2-Release+fftw+hypre+openfast+tioga^trilinos@develop+uvm](https://sierra-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=389829)
  * ablNeutralNGPTrilinos
  * ActLineSimpleFLLC
  * conduction_p4
  * drivenCavity_p1
  * nrel5MWactuatorLine
  * taylorGreenVortex_p3

@psakievich similarly to #984, is this a possible issue with our spack install?

**Comment by ldh4** [comment]
Similar to #984, I think it could be worth it to check if using another version of `CUDA` still produces this error.
