### ISSUE TITLE
Teuchos::make_rcp

### ISSUE THREAD

**Issue by rcknaus** [Exawind/nalu-wind#991]
We want to replace [make_rcp](https://github.com/Exawind/nalu-wind/blob/master/include/matrix_free/MakeRCP.h)  with `Teuchos::make_rcp` once the `stable` tag for the NREL dashboard moves past https://github.com/trilinos/Trilinos/commit/23883f0cf635781111b9169ba68bc5106b5dc4f6 .

**Comment by tasmith4** [comment]
fyi @psakievich this is some motivation to bump `trilinos@stable` once the dashboard is green for develop.

**Comment by psakievich** [comment]
@rcknaus @tasmith4 if you are looking for ECP work right now it would be reasonable to revisit this.

**Comment by marchdf** [comment]
This was done in #1082
